docs/root/start/building/building.rst
There was some confusion around _which requirements_ were needed for building Envoy Mobile. This should help clarify.
=> docs: point upstream link to specific section

docs/conf.py
Before: `© Copyright 2019-2019, Lyft`
After: `© Copyright 2019 Lyft, Inc.`
=> docs: fix copyright

.bazelrc
When doing android builds bazel crashes with GC overhead reached.
=> bazel: Remove JVM limit

library/common/BUILD
Description: Clean up of build opts.
Testing: Built and ran locally.
Fixes #52
=> build: remove unnecessary opts

examples/swift/hello_world/ViewController.swift
Description: noticed a missing single quote in the iOS example
Testing: None
=> ios example: add missing single quote to NSLog

library/common/BUILD
Description: Welp. Maybe we need this after all.
Testing: Saw more ceilf errors and this fixed them again.
=> build: reinsert possibly necessary opts

examples/java/hello_world/MainActivity.java, examples/kotlin/hello_world/MainActivity.kt, library/common/jni_interface.cc, library/java/io/envoyproxy/envoymobile/Envoy.java
Description: Updates Android interface to statically load and initialize the library, but allow multiple Envoy instances to be created with their own configuration and tied to their own thread.
Testing: Built and ran library and apps locally
=> lib: make Android interface instance-based and threadsafe

BUILD
Since we are circumventing bazel's normal input / output file checking
for building our aar, we discovered some issues. When building this dist
library, some changes would not cause overwrites of the aar that is
outside of the source tree. The easiest way for me to repro this was:
```
bazel build android_dist
ls dist # here you see envoy.aar
rm -f dist/envoy.aar bazel-bin/android_out
bazel build android_dist
ls dist # here you don't see envoy.aar
```
The actual issue we found with this was if you built this library, and
altered the linkopts of envoy_jni_interface_lib, the library in dist
would not have the updated binaries, resulting in seemingly flaky
behavior when building.
Fixes https://github.com/lyft/envoy-mobile/issues/148
=> bazel: Add stamping to android_dist genrule

BUILD, bazel/aar_with_jni.bzl, examples/java/hello_world/BUILD, examples/kotlin/hello_world/BUILD, library/java/io/envoyproxy/envoymobile/Envoy.java, library/java/io/envoyproxy/envoymobile/EnvoyEmptyClass.kt, library/kotlin/io/envoyproxy/envoymobile/EnovyKotlinEmptyClass.java, library/kotlin/io/envoyproxy/envoymobile/Envoy.kt, library/kotlin/io/envoyproxy/envoymobile/EnvoyKotlinEmptyClass.java, tools/check_format.sh
The primary goal this achieves is that it unlocks our ability to develop the Envoy mobile shim in kotlin rather than java. 
The gist of this change is that `android_library`'s implicit `aar` doesn't flatten its transitive dependencies. When using the kotlin rules, the `kt_android_library` rule creates a few underlying libraries, because of this the `classes.jar` in the `aar` we built was empty. This change separately builds the underlying `*kt.jar` file, and replaces the `aar`'s `classes.jar` with the kotlin one.
https://github.com/lyft/envoy-mobile/issues/99
Description: Enable …
=> kotlin: Create aar files from kotlin_library jar rather than relying on android_binary

CONTRIBUTING.md
Description:
As an uninitiated person improving the sample projects or documentation, running `./envoy/support/bootstrap` alone doesn't cut it. The `pre-push` hook uses a bunch of dependencies from the core envoy project (realpath, clang-format, buildifier).
This change clarifies this in Contributing.md since some folks may try to contribute without necessarily having full context on envoy's dependencies. An alternative would be to install dependencies in `bootstrap`.
Testing: None
Docs Changes: Only
Release Notes: N/a
=> docs: note using git hooks needs envoy dependences

examples/objective-c/hello_world/Info.plist, examples/objective-c/hello_world/ViewController.mm
Using `0.0.0.0` when connecting over a socket to Envoy doesn't work when building to a physical device even though it works fine on a simulator.
To fix this, we can use `localhost` and disable ATS for the demos.
As a long term fix, there are a few options, but the foremost/preferred is to call directly into Envoy over request interfaces instead of using a local socket. See [this section](https://docs.google.com/document/d/1eLbJEXog2Rn7wTBEbDIjpDV7dHecV_DV_dw8P5ZgbL4/edit#heading=h.nx6ynimf9ztp) for more details on this, slated for v0.2.
Discussion: https://envoyproxy.slack.com/archives/CKQ2LK23G/p1561146122069800
Testing: Done locally
=> objc: fix demo when building on device

examples/swift/hello_world/Info.plist, examples/swift/hello_world/ViewController.swift
Using `0.0.0.0` when connecting over a socket to Envoy doesn't work when building to a physical device even though it works fine on a simulator.
To fix this, we can use `localhost` and disable ATS for the demos.
As a long term fix, there are a few options, but the foremost/preferred is to call directly into Envoy over request interfaces instead of using a local socket. See [this section](https://docs.google.com/document/d/1eLbJEXog2Rn7wTBEbDIjpDV7dHecV_DV_dw8P5ZgbL4/edit#heading=h.nx6ynimf9ztp) for more details on this, slated for v0.2.
Discussion: https://envoyproxy.slack.com/archives/CKQ2LK23G/p1561146122069800
Testing: Done locally
=> swift: fix demo when building on device

BUILD, examples/objective-c/hello_world/AppDelegate.mm, examples/swift/hello_world/AppDelegate.swift, library/objective-c/BUILD, library/objective-c/Envoy.h, library/objective-c/Envoy.mm, tools/check_format.sh
Description: Allow multiple Envoy instances to be created with their own configuration and tied to their own thread.
Testing: Built and ran apps locally
=> lib: make iOS interface instantiable and internalize thread

.clang-format, examples/objective-c/hello_world/AppDelegate.h, library/common/jni_interface.cc, library/common/main_interface.cc, library/common/main_interface.h, library/java/io/envoyproxy/envoymobile/engine/EnvoyEngine.java, library/kotlin/io/envoyproxy/envoymobile/Envoy.kt, library/objective-c/Envoy.h, library/objective-c/Envoy.mm
Description: Adds configurable log-level to common interface, and support to both iOS and Android interfaces. Defaults to log-level info.
Testing: Locally compiled and tested.
=> logging: add configurable log-level to startup params

WORKSPACE
Resolves the following warning when building:
> DEBUG: Rule 'io_bazel_rules_kotlin' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556831609 -0700"
=> bazel: update rules_kotlin shallow_since

.pre-commit-config.yaml
Description: add spelling pre-commit hook. Note that I did not go with the tools in upstream because they are more entrenched in the organization of the upstream project. This suffices for now. Also note that none of the solutions (this one, or the ones upstream -- misspell, aspell) are 100% great; meaning that let through a significant amount of misspellings. For instance, `enfornced` was not caught by any of the solutions.
Risk Level: low -- new pre-commit hook.
Testing: ran locally.
=> pre-commit: add spelling

examples/objective-c/hello_world/AppDelegate.mm, examples/objective-c/hello_world/ViewController.mm, examples/objective-c/hello_world/main.mm, library/objective-c/Envoy.mm
The preformat `clang-format` checks don't run on `.m` or `.mm` files at the moment, so these files are malformatted. Pulls in upstream changes from https://github.com/envoyproxy/envoy/pull/7406 and runs the linter.
Resolves https://github.com/lyft/envoy-mobile/issues/191
=> ci: run preformat on Objective-C++ files

examples/objective-c/hello_world/Base.lproj/LaunchScreen.storyboard, examples/objective-c/hello_world/Info.plist, examples/swift/hello_world/Base.lproj/LaunchScreen.storyboard, examples/swift/hello_world/Info.plist
Without these, the iOS demos only display on a small subset of the device's screen.
Testing: Locally
|Before|After|
|-|-|
|![Simulator Screen Shot - TestDevice - 2019-06-27 at 15 24 16](https://user-images.githubusercontent.com/2643476/60304895-a2f3c080-98ef-11e9-8274-19a352084db7.png)|![Simulator Screen Shot - TestDevice - 2019-06-27 at 15 16 24](https://user-images.githubusercontent.com/2643476/60304910-abe49200-98ef-11e9-8cb3-a20c6ad9daeb.png)|
=> ios: add launch screens to fix sizing

azure-pipelines.yml
Description: previously the CI runs would only build the demos. However we did not run them, or check for liveliness. This is a first iteration of doing so for iOS.
Risk Level: low - improved CI
Testing: tested locally and on CI
Part of #117
=> ci: run the iOS apps in ci

CONTRIBUTING.md
https://github.com/lyft/envoy-mobile/issues/185
Removing the instructions for installing the envoy bootstrap since we will want to have our own.
Description: Remove envoy bootstrap install from docs
Testing: na
Docs Changes: CONTRIBUTING.md
Release Notes:
=> docs: Remove envoy bootstrap install from docs

docs/root/development/performance/battery_impact.rst, docs/root/development/performance/cpu_impact.rst, docs/root/development/performance/performance.rst
Description: adding docs for ios and android battery/cpu profiling
Testing: locally with `./docs/build.sh`
Docs Changes: `docs/root/development/performance/`
Release Notes:
=> docs: Add docs for battery/cpu analysis

library/common/BUILD, test/performance/test_binary_size.cc
Description: after #173 landed this target broke due to the breaking API change. This target will be added to CI once #181 closes, so breakages like this will not go undected.
Risk Level: low - updating API, deleting old build rules.
=> perf: update test binary size target

docs/root/development/performance/battery_impact.rst, docs/root/development/performance/cpu_impact.rst
Docs for the battery/cpu analysis
- CPU is slightly higher for Envoy
- Battery is about the same
Description: Docs for the battery/cpu analysis
Testing: local
Docs Changes: performance
=> performance: add Android battery/cpu profiling results

examples/common/config.yaml
There is a set of configurations that we can slow down on mobile from their defaults upstream because they aren't as relevant to mobile clients.
This change updates our example configurations to use new values based on [this discussion](https://github.com/lyft/envoy-mobile/issues/113#issuecomment-507421778).
When we switch to typed configurations, these should also be set automatically for production clients: https://github.com/lyft/envoy-mobile/issues/169
Testing: CI and locally
=> configs: slow down certain refreshes

envoy_build_config/extensions_build_config.bzl
Updating Envoy to include https://github.com/envoyproxy/envoy/pull/7453 (and subsequently https://github.com/libevent/libevent/pull/849), which should fix the performance issues we're seeing on iOS. Resolves https://github.com/lyft/envoy-mobile/issues/215.
=> perf: update envoy to include libevent patch

docs/root/development/performance/cpu_battery_impact.rst
Update the docs to reflect new analyses following the libevent fixes from https://github.com/lyft/envoy-mobile/issues/215.
=> perf: update iOS docs after libevent fix

WORKSPACE, bazel/BUILD, bazel/EnvoyMobileTestSuite.kt, bazel/kotlin_test.bzl, library/kotlin/test/SampleTest.kt
Creating test targets for Kotlin is a bit tedious. This change is to help alleviate that.
Some callouts:
1. This will *only* run tests within the `io.envoyproxy.envoymobile` package space
2. This will fail if there are no tests in the provided test target
I feel these are reasonable requirements for this project and can rely on this for the near future (we can revisit when we there is a solution which is more official).
Bazel out of the box:
```
load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_test")
kt_jvm_test(
name = "example_kotlin_test",
test_target = "com.example.myproject.mymodule.ExampleTest"
srcs = [
"ExampleTest.kt",
],
deps = [
"//:another_target",
"@maven//:org_assertj_assertj_core",
"@maven//:junit_junit",
]
)
```
With this change:
```
load("//bazel:kotlin_test.bzl", …
```
=> kotlin: Adding bazel macro for more convenient test target declaration

.bazelrc
When creating release builds we should pass `--config=fat`, when
iterating on the Android library we don't need to build multiple
architectures since this just doubles build times.
=> build: Remove an architecture for Android builds

.gitignore, azure-pipelines.yml, bazelw, ci/linux_ci_setup.sh, ci/mac_ci_setup.sh
This wrapper is a simple shell script that handles downloading bazel.
This ensures that all developers are using the same supported version of
bazel, as well as keeping it in lockstep with CI. This also means
developers who aren't already using bazel don't have to figure out how
to install it on their system globally.
=> build: Add bazel wrapper

azure-pipelines.yml, ci/linux_ci_setup.sh
I couldn't do this in the same PR since it checks out master and the
wrapper wasn't there yet.
=> ci: Change master job to use bazelw

library/objective-c/Envoy.h, library/objective-c/Envoy.mm, library/swift/BUILD, library/swift/Envoy.swift, library/swift/LogLevel.swift
This is implemented in Kotlin right now, and should be present in the Swift layer as well. Move the Objective-C logging types to Swift.
Resolves https://github.com/lyft/envoy-mobile/issues/244
=> ios: refactor LogLevel to Swift layer

.pre-commit-config.yaml, library/swift/Request.swift, library/swift/RequestBuilder.swift, library/swift/RequestMethod.swift, library/swift/RetryPolicy.swift
Introduces request interfaces for the Swift library.
**Builder pattern**
We elected to use a builder pattern for the following reasons:
- Allows us to avoid making all properties mutable (such as those on `Request`). This is especially valuable because these types are classes instead of structs due to the fact that they need to be visible to Objective-C from Swift
- Provides a clear separation between mutable/immutable states of these types since only builders can be modified
- Allows consumers to easily convert between builders and the models, which will become particularly useful when we introduce features such as runtime filters in the future:
```swift
func filter(request: Request) -> Request {
return request
.newBuilder()
.addHeader(name: "x-new-header", value: "foo")
.build()
}
``` …
=> swift: add library request interfaces

library/swift/src/BUILD
These aren't being compiled in right now.
=> swift: include missing library files

library/swift/src/BUILD
=> bazel: remove envoy_swift_lib

BUILD, dist/BUILD, examples/kotlin/hello_world/BUILD, examples/kotlin/shared/BUILD, examples/objective-c/hello_world/BUILD, examples/swift/hello_world/BUILD, library/kotlin/src/io/envoyproxy/envoymobile/BUILD, library/swift/src/BUILD, tools/check_format.sh
Description: These were originally inserted by the upstream check_format.py script. They're really only relevant to the core Envoy build tree. Cleaning them up now that we're able to selectively exclude paths from this check.
Testing: CI
=> build: remove extraneous inclusion of envoy_package

WORKSPACE, azure-pipelines.yml, bazel/swift_test.bzl, library/swift/test/BUILD
Conceptually similar to the macro added in https://github.com/lyft/envoy-mobile/pull/221 for Kotlin testing, this PR adds a `envoy_mobile_swift_test` macro for Swift unit testing.
- Prevents consumers from having to define both swift_library and ios_unit_test targets
- Provides a set of linker options that is required to properly run tests
- Sets default visibility and OS requirements
=> swift: add macro for unit testing

library/swift/src/RetryPolicy.swift, library/swift/test/BUILD, library/swift/test/RetryPolicyTests.swift
Because `RetryPolicy` inherits from `NSObject` in order to be visible to Objective-C, we need to implement our own equatable comparison in order for `==` to work as intended (using property comparison instead of pointer comparison).
Adds tests to verify this.
=> swift: fix RetryPolicy equatability & add tests

library/swift/src/RequestBuilder.swift
Updating these names to match up with the Swift header modification functions, as well as the Kotlin interfaces.
=> swift: fix naming of trailer removal functions

bazel/swift_test.bzl
=> bazel: fix incorrect reference in Swift test rule

azure-pipelines.yml
This has proven to be super flaky, failing on almost every PR once or twice. Disabling for now until we're able to debug.
Issue for re-enabling: https://github.com/lyft/envoy-mobile/issues/271
=> ci: temporarily disable mac_swift_helloworld

library/swift/src/Request.swift, library/swift/test/BUILD, library/swift/test/RequestBuilderTests.swift, library/swift/test/SampleTest.swift
Adds tests for the request builders similar to the ones available on master for Kotlin.
Also fixes the `Equatable` comparison of `Request` by overriding `isEqual`. This is required since this type subclasses `NSObject` to be visible to Objective-C, and we want property comparison instead of pointer comparison here.
Resolves https://github.com/lyft/envoy-mobile/issues/252
=> swift: add tests for request builders

bazel/kotlin_lib.bzl, library/java/io/envoyproxy/envoymobile/engine/BUILD, library/kotlin/src/io/envoyproxy/envoymobile/BUILD
We currently have to redeclare our sources in the `srcs` argument for the top level library consumed by the `aar_with_jni` macro. The reason is because the `aar_with_jni` doesn't get visibility onto the transitive dependencies of the provided library. Since we are using `kt_jvm_library`, which internally creates two rules and encloses the dependencies within them, the library we provide does not expose any dependencies for the `aar_with_jni` target.
This makes it very complicated to create new libraries because for every new library, we have to create a `filegroup` which the top level `envoy_lib` needs to depend on directly in the `srcs`.
This is a total bazel macro hack to hide away this detail for us. The limitation here is that the top level `envoy_lib` needs to directly depend on the …
=> kotlin: add bazel macros for easier kt target declaration

library/swift/src/Request.swift, library/swift/src/RequestBuilder.swift, library/swift/test/RequestBuilderTests.swift
As we bridge over the platform layers to talk to the C/C++ core, we'll need to be able to send headers such as `:method`/`:scheme`/`:authority`.
The `URL` type exposes optionals for these properties, which means we need to either handle them at initialization time or at the time when the request is executed by unwrapping them and throwing/failing.
In order to prevent throwing when deconstructing `URL` components, we are instead updating the interfaces to accept these 3 fields separately.
=> swift: expose URL components instead of URL type

.swiftlint.yml
This is not enforced in any other languages in this repo, and we have TODOs in other languages and upstream Envoy.
=> ci: disable Swift todo lint rule

library/swift/src/BUILD, library/swift/src/RetryPolicy.swift, library/swift/src/RetryPolicyMapper.swift, library/swift/test/BUILD, library/swift/test/RequestBuilderTests.swift, library/swift/test/RetryPolicyMapperTests.swift, library/swift/test/RetryPolicyTests.swift
Adds converters to go from `RetryPolicy` to a set of headers that upstream Envoy understands.
This will be utilized by the request logic in the `Envoy` class.
=> swift: add conversion from RetryPolicy to headers

library/kotlin/src/io/envoyproxy/envoymobile/Request.kt, library/kotlin/src/io/envoyproxy/envoymobile/RequestBuilder.kt, library/kotlin/test/io/envoyproxy/envoymobile/RequestBuilderTest.kt, library/kotlin/test/io/envoyproxy/envoymobile/RequestTest.kt
To mirror: https://github.com/lyft/envoy-mobile/pull/277
Description: expose URL components instead of URL type
Testing: unit
=> kotlin: expose URL components instead of URL type

library/swift/src/BUILD, library/swift/src/RequestMapper.swift, library/swift/src/RetryPolicyMapper.swift, library/swift/test/BUILD, library/swift/test/RequestMapperTests.swift, library/swift/test/RetryPolicyMapperTests.swift
Adds converters to go from `Request` to a set of headers that upstream Envoy understands.
This will be utilized by the request logic in the `Envoy` class.
Previous consideration: https://github.com/lyft/envoy-mobile/pull/275
=> swift: add conversion from Request to headers

library/swift/src/Client.swift
Xcode 10.3 complains that this file uses `@objc` without importing `Foundation`.
=> swift: add Foundation import

library/objective-c/EnvoyEngine.mm, library/objective-c/EnvoyTypes.h
- Makes `EnvoyStatus` a closed enum, since we guarantee a limited set of values
- Renames the enum cases to be more consistent with Apple's [guidelines](https://developer.apple.com/library/archive/releasenotes/ObjectiveC/ModernizationObjC/AdoptingModernObjective-C/AdoptingModernObjective-C.html#//apple_ref/doc/uid/TP40014150-CH1-SW6)
This has the effect of improving their usability in Swift.
```swift
let result = ... // EnvoyStatus
if result == .Success // Before change
if result == .success // After change
```
=> ios: update EnvoyStatus to be more Swift-friendly

library/objective-c/EnvoyEngine.h, library/objective-c/EnvoyTypes.h
Contents of these interfaces should be assumed to be nonnull.
=> objc: add nullability regions

library/objective-c/EnvoyEngine.h
Moves the streaming method requirements out of the `EnvoyEngine` class and into a protocol interface. Swift will then take a conformer to this protocol instead of calling directly into `EnvoyEngine`, which will allow us to inject mock conformers for better testing. We'll do this on Android as well.
=> objc: move EnvoyEngine streaming calls to protocol

library/objective-c/EnvoyTypes.h
This makes it clearer where the error is coming from (ObjC shim rather than Swift library) and will prevent name collisions with the Swift library layer (which will be `EnvoyError`).
=> objc: rename EnvoyError to EnvoyEngineError

docs/root/development/performance/device_conditions.rst
Updating based on https://github.com/lyft/envoy-mobile/issues/128#issuecomment-516260951.
=> docs: update iOS performance findings

azure-pipelines.yml
Description: These are failing in CI and passing locally and we're switching up CI soon, so let's just disable for now.
=> ci: temporarily disable swift lib tests

examples/kotlin/shared/AndroidManifest.xml
Prevents warnings when building:
```
WARNING:
CONFIGURATION: bazel-out/android-x86-fastbuild/bin/examples/kotlin/shared/hello_envoy_shared_lib_base_processed_manifest/AndroidManifest.xml has no minSdkVersion. Using 1.
[204 / 242] Merging Android resources for @androidsdk//com.android.support:support-vector-drawable-25.0.0; 1s local ... (4 actions running)
INFO: From Validating Android resources for //dist:envoy_mobile_android:
Aug 12, 2019 10:21:21 PM com.google.devtools.build.android.AndroidManifest parseFrom
WARNING:
CONFIGURATION: bazel-out/android-x86-fastbuild/bin/dist/envoy_mobile_android_processed_manifest/AndroidManifest.xml has no minSdkVersion. Using 1.
```
=> android: add missing minSdkVersion

library/objective-c/EnvoyEngine.h, library/objective-c/EnvoyEngine.m, library/swift/src/Envoy.swift
This was originally going to be done as part of https://github.com/lyft/envoy-mobile/pull/316, but we ran into build issues.
Making this change will allow us to mock `EnvoyEngine` from the Swift/Kotlin platform layers.
=> objc: convert EnvoyEngine into a protocol

library/objective-c/EnvoyEngine.m
This was being instantiated in the wrong order, and warning at compile time that the wrong closure types were being assigned to `envoy_observer`:
```
library/objective-c/EnvoyEngine.m:228:33: warning: incompatible pointer types initializing 'envoy_on_error_f' (aka 'void (*)(envoy_error, void *)') with an expression of type 'void (void *)' [-Wincompatible-pointer-types]
ios_on_complete, ios_on_error, context};
^~~~~~~~~~~~~~~
library/objective-c/EnvoyEngine.m:228:50: warning: incompatible pointer types initializing 'envoy_on_complete_f' (aka 'void (*)(void *)') with an expression of type 'void (envoy_error, void *)' [-Wincompatible-pointer-types]
ios_on_complete, ios_on_error, context};
^~~~~~~~~~~~
```
=> objc: fix envoy_observer native_init

examples/java/hello_world/MainActivity.java, examples/kotlin/hello_world/MainActivity.kt, library/common/jni_interface.cc, library/java/src/io/envoyproxy/envoymobile/engine/AndroidEngineImpl.java, library/java/src/io/envoyproxy/envoymobile/engine/AndroidJniLibrary.java, library/java/src/io/envoyproxy/envoymobile/engine/BUILD, library/java/src/io/envoyproxy/envoymobile/engine/EnvoyEngine.java, library/java/src/io/envoyproxy/envoymobile/engine/EnvoyEngineImpl.java, library/java/src/io/envoyproxy/envoymobile/engine/EnvoyHTTPStream.java, library/java/src/io/envoyproxy/envoymobile/engine/JniLibrary.java, library/kotlin/src/io/envoyproxy/envoymobile/Envoy.kt
Create an `AndroidJniLibrary` and move specific loader logic into the `*JniLibrary` classes. Cleaning up the other layers in Kotlin due to this change.
Description: Create an `AndroidJniLibrary` and move specific loader logic into the `*JniLibrary` classes
Testing: local
=> Create an AndroidJniLibrary and move specific loader logic into the respective JniLibrary classes

library/common/main_interface.cc
Description: comment describing current ordering between `setup_envoy` and `run_engine` in the main_interface.
Risk Level: low - code comment
=> core: comment on setup_envoy/run_engine ordering

library/common/include/c_types.c
Description: remove unnecessary pragma left as a merge comment in #342 
Testing: builds in CI
=> core: remove compiler pragma

WORKSPACE, bazel/kotlin_test.bzl
A few problems:
1. We don't take into account the java directory for test source dependencies
2. We don't take into account the transitive dependencies for sources
This change is to look also at the java directory (not really needed but it'll keep the symmetry between java and kotlin and to include dependencies as actual dependencies for transitive inclusion.
Additionally, add common mocking frameworks:
1. [`org.mockito:mockito`](https://github.com/mockito/mockito)
2. [`com.nhaarman.mockitokotlin2`](https://github.com/nhaarman/mockito-kotlin)
Description: Repeat dependencies for kt jvm test + add mocking deps
Risk Level: …
=> bazel: Repeat dependencies for kt jvm test + add mocking deps

library/swift/src/Client.swift, library/swift/src/Request.swift, library/swift/src/RequestBuilder.swift, library/swift/src/StreamEmitter.swift, library/swift/test/RequestBuilderTests.swift
Adds unary interfaces (related to https://github.com/lyft/envoy-mobile/issues/118) which will call into the streaming interfaces under the hood.
These are to be used as convenience convenience accessors for the common case of non-streaming requests, and will be added on Android as part of https://github.com/lyft/envoy-mobile/issues/119.
This also removes `data` and `trailers` from `Request`, as the unary function will take care of this for unary requests, and streams will be expected to handle this through the `StreamEmitter`.
The underlying implementation will look something like this:
```swift
public func sendUnary(_ request: Request, body: Data?,
trailers: [String: [String]] = [:], handler: ResponseHandler)
{
let emitter = self.startStream(with: request, handler: handler)
if let body = …
```
=> ios: add request unary interfaces

library/kotlin/src/io/envoyproxy/envoymobile/Client.kt, library/kotlin/src/io/envoyproxy/envoymobile/Request.kt, library/kotlin/src/io/envoyproxy/envoymobile/RequestBuilder.kt, library/kotlin/test/io/envoyproxy/envoymobile/RequestBuilderTest.kt, library/kotlin/test/io/envoyproxy/envoymobile/RequestTest.kt
The request object is no longer going to contain the body and trailers.
For the streaming case, the headers will be sent upon connection but the data/trailers will be handled by the user
For the unary case, the headers and body will be sent upon connection. The trailers will be sent once a response is sent back.
Description: kotlin: remove body and trailers from request object to Client interfaces
Testing: unit
=> kotlin: remove body and trailers from request object to Client interfaces

examples/swift/hello_world/ViewController.swift, library/swift/src/Client.swift, library/swift/src/Envoy.swift, library/swift/src/StreamEmitter.swift, library/swift/test/BUILD, library/swift/test/ClientTests.swift
Per the discussion [here](https://github.com/lyft/envoy-mobile/pull/312#discussion_r315820916), updating the unary and streaming interfaces.
- Moved the non-streaming convenience function into an extension on the protocol type so that it's available to all consumers
- Added a test to validate the default behavior of this extension function
- Added a `CancelableStream` protocol which includes a subset of functionality from the `StreamEmitter`, allowing consumers of the unary function to cancel requests without having the ability to send additional data into the stream
=> ios: update unary/streaming & add test

test/common/http/dispatcher_test.cc
https://github.com/lyft/envoy-mobile/pull/353 broke the `format_all` test on CI on master.
This fixes it by running the formatter and pushing the diff.
=> core: fix broken formatter on master

library/objective-c/BUILD, library/objective-c/EnvoyConfiguration.m, library/objective-c/EnvoyEngineImpl.m, library/objective-c/EnvoyHTTPStream.m, library/objective-c/EnvoyObserver.m
Description: Separates Objective-C sources into separate files, separating logic a little bit better. A single bridging header is still required (for now).
=> ios: split out objc sources with single bridging header

examples/java/hello_world/BUILD, examples/java/hello_world/MainActivity.java, examples/java/hello_world/res/raw/config.yaml, examples/kotlin/hello_world/BUILD, examples/kotlin/hello_world/MainActivity.kt, examples/kotlin/hello_world/res/raw/config.yaml, library/kotlin/src/io/envoyproxy/envoymobile/BUILD, library/kotlin/src/io/envoyproxy/envoymobile/Envoy.kt
Using new envoy builders in the example applications and the default config
Doing some clean up also
Description: Using new envoy builders in the example applications and the default config
Testing: ci/local
=> android: Use new envoy builder + clean up

bazel/swift_static_framework.bzl, examples/objective-c/hello_world/AppDelegate.mm, examples/objective-c/hello_world/BUILD, examples/objective-c/hello_world/Empty.swift, examples/objective-c/hello_world/ViewController.mm
This updates our static framework rule to properly copy the `-Swift.h` header file from the bazel output directory into our final `Envoy.framework/Headers/Envoy-Swift.h`.
There are a few workarounds here for issues that @kastiglione has been nice enough to file upstream:
**https://github.com/bazelbuild/rules_swift/issues/291**
The code required to find and copy the `-Swift.h` header file could be simplified with this issue.
**https://github.com/bazelbuild/rules_apple/issues/557**
From the Objective-C demo app, we also depend on an empty Swift library to force dependencies like `swiftFoundation` to link.
Resolves https://github.com/lyft/envoy-mobile/issues/230
=> bazel: fix Objective-C compilation & demo

.github/workflows/android.yml, .github/workflows/core.yml, .github/workflows/format.yml, .github/workflows/ios.yml, .github/workflows/perf.yml
Description: add tighter timeouts to CI than the default 360 mins.
=> ci: add timeouts

library/common/http/dispatcher.cc, library/common/main_interface.cc
Description: I noticed that the swift iOS demo was leaking streams. This PR fixes the issue by wiring up trailer sending code and causing the stream to close locally.
Testing: built and ran the demo app, verified correct closure and clean up via logging.
Co-authored-by: Mike Schore <mike.schore@gmail.com>
=> core: wire up send trailers

library/java/src/io/envoyproxy/envoymobile/engine/EnvoyConfigurationImpl.java
This is the fast solution for this problem
A few options to really root fix here:
1. We hide all `native` methods behind another method which mirrors the current `JniLibrary` interfaces but calls the static `load()` method prior to using any methods (super safe but removes some of the control from when we load the native lib)
2. Only call the `templateString()` method *after* the initialization of the `EnvoyEngine` (feels kind of brittle still)
3. (@goaway's suggestion) Move the configuration resolution down to the Engine layer since that is a lower level detail
Description: java: …
=> java: call Jni.load() before accessing the configuration template

.bazelrc
According to Bazel's [docs](https://docs.bazel.build/versions/master/user-manual.html#flag--spawn_strategy), `standalone` is deprecated, and `local` is now preferred.
=> bazel: use local spawn_strategy

library/kotlin/src/io/envoyproxy/envoymobile/ResponseHandler.kt, library/kotlin/test/io/envoyproxy/envoymobile/ResponseHandlerTest.kt
Description: add endStream to onHeaders callback signature
Testing: built locally
=> kotlin: add endStream to onHeaders callback signature

library/common/buffer/bridge_fragment.h, library/common/buffer/utility.cc, test/common/buffer/BUILD, test/common/buffer/bridge_fragment_test.cc, test/common/buffer/utility_test.cc
Description: add unit tests for buffer utility and bridge fragment in core code.
Testing: added unit tests.
=> core: buffer utility and bridge fragment unit tests

library/kotlin/src/io/envoyproxy/envoymobile/ResponseHandler.kt
Description: these fields should not be optional. The callbacks _must_ send up that data.
Testing: tested with e2e demo
=> android: make response handler arguments non-optional

library/common/buffer/utility.cc, library/common/http/dispatcher.h, test/common/http/dispatcher_test.cc
Description: remove todos that were done already.
=> cleanup: remove stale todos

library/common/http/dispatcher.cc
Description: delete dispatcher todo that is done. This TODO is done as when cleanup happens it is guaranteed that core Envoy will not fire anymore callbacks on that stream, and additionally the platform has also locally closed the stream.
=> cleanup: delete dispatcher todo that is done

library/common/jni_interface.cc, library/objective-c/EnvoyHTTPStreamImpl.m
Description: Our memory model requires a native retain on stream state that must be available for the duration of the lifecycle of the native stream. This partially addresses a race where the retain might not be in place before the stream is reset - resulting in a leak. In order to fully address this, the retain must be completed such that it prevents re-ordering and is visible to other threads.
=> core: partially address race with native retain on stream state

library/common/http/dispatcher.cc, library/common/http/dispatcher.h, library/common/jni_interface.cc, library/common/main_interface.cc, library/common/main_interface.h, library/common/types/c_types.h, library/java/src/io/envoyproxy/envoymobile/engine/BUILD, library/java/src/io/envoyproxy/envoymobile/engine/EnvoyEngine.java, library/java/src/io/envoyproxy/envoymobile/engine/EnvoyEngineImpl.java, library/java/src/io/envoyproxy/envoymobile/engine/EnvoyHTTPStream.java, library/java/src/io/envoyproxy/envoymobile/engine/JniLibrary.java, library/java/src/io/envoyproxy/envoymobile/engine/JvmCallbackContext.java, library/java/src/io/envoyproxy/envoymobile/engine/types/BUILD, library/java/src/io/envoyproxy/envoymobile/engine/types/EnvoyHTTPCallbacks.java, library/kotlin/src/io/envoyproxy/envoymobile/Envoy.kt, library/kotlin/src/io/envoyproxy/envoymobile/ResponseHandler.kt, library/kotlin/test/io/envoyproxy/envoymobile/ResponseHandlerTest.kt, library/objective-c/BUILD, library/objective-c/EnvoyEngine.h, library/objective-c/EnvoyEngineImpl.m, library/objective-c/EnvoyHTTPCallbacks.m, library/objective-c/EnvoyHTTPStreamImpl.m, library/swift/src/Envoy.swift, library/swift/src/ResponseHandler.swift, library/swift/test/EnvoyBuilderTests.swift, library/swift/test/EnvoyTests.swift, library/swift/test/MockEnvoyHTTPStream.swift, test/common/http/dispatcher_test.cc
Description: I've come to be of the opinion that 'observer' is an unfortunate and confusing name for the objects containing our callbacks:
- In Envoy itself these are called callbacks.
- In our filter proposal we're calling these callbacks.
- These entities have deviated from the reactive pattern from which they take their namesake.
Testing: CI
=> cleanup: rename instances of 'observer' to 'callbacks'

examples/objective-c/hello_world/ViewController.m, examples/swift/hello_world/ViewController.swift, library/objective-c/EnvoyEngine.h, library/objective-c/EnvoyHTTPStreamImpl.m, library/swift/src/EnvoyError.swift, library/swift/src/ResponseHandler.swift
Description: exposing the contents of envoy_error up to the platform. Note that this implementation differs slightly from Android. I have opened https://github.com/lyft/envoy-mobile/issues/409 to consolidate both platforms.
Risk Level: 
Testing: local, and CI
=> ios: wire-up error to platform callbacks

library/swift/test/EnvoyTests.swift
This was broken by https://github.com/lyft/envoy-mobile/pull/413, but wasn't caught by CI because of https://github.com/lyft/envoy-mobile/issues/383.
=> swift: fix function signature in EnvoyTests

library/swift/test/EnvoyBuilderTests.swift
This is no longer a protocol requirement.
=> ios: remove dead function

WORKSPACE, examples/objective-c/hello_world/BUILD, examples/objective-c/hello_world/Empty.swift
We can now remove the hack for building the Objective-C demo now that https://github.com/bazelbuild/rules_apple/pull/566 has merged (thanks @kastiglione!).
Description:
Testing: Locally
=> ios: update rules_apple & remove hack

library/java/src/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java, library/kotlin/src/io/envoyproxy/envoymobile/EnvoyBuilder.kt, library/objective-c/EnvoyConfiguration.m, library/objective-c/EnvoyEngine.h, library/objective-c/EnvoyEngineImpl.m, library/swift/src/Envoy.swift, library/swift/src/EnvoyBuilder.swift, library/swift/test/EnvoyBuilderTests.swift, library/swift/test/EnvoyTests.swift
This is a mirror of the Android change made in https://github.com/lyft/envoy-mobile/pull/385.
The change was originally motivated by the fact that Android was unable to obtain the configuration template within C++ before the JNI was loaded. Moving the template resolution logic to Java fixed this issue by allowing the JNI to be initialized before loading the template.
Key changes in this PR:
- Moved template resolution to Objective-C
- Custom YAML files are no longer treated as templates, and are not resolved (but are passed through as-is). This matches Android
- Updated initializers as necessary to match Android
=> ios: move configuration to Objective-C

BUILD
=> bazel: remove unused BUILD imports

examples/objective-c/hello_world/ViewController.m, examples/swift/hello_world/ViewController.swift, library/swift/src/BUILD, library/swift/src/EnvoyClient.swift, library/swift/src/EnvoyClientBuilder.swift, library/swift/src/HTTPClient.swift, library/swift/test/BUILD, library/swift/test/EnvoyClientBuilderTests.swift, library/swift/test/EnvoyClientTests.swift
`Client` -> `HTTPClient`
`Envoy` -> `EnvoyClient`
`EnvoyBuilder` -> `EnvoyClientBuilder`
Consistent with [this Android change](https://github.com/lyft/envoy-mobile/pull/424), and helps us to avoid naming collisions with the `Envoy` type and `Envoy` module namespace.
=> ios: rename Client/Envoy/EnvoyBuilder

library/common/http/dispatcher.cc, test/common/http/dispatcher_test.cc
Description: clean up streams in the http dispatcher when the underlying stream fires an onReset callback. Previously we were leaking this state.
Risk Level: med - stream memory management changes. However, we have a guarantee from the underlying async client implementation that terminal callbacks (onReset, onComplete) will only fire once.
Testing: unit tests.
=> core: clean up streams in http dispatcher on reset

examples/java/hello_world/MainActivity.java, examples/kotlin/hello_world/MainActivity.kt, library/kotlin/src/io/envoyproxy/envoymobile/AndroidEnvoyClientBuilder.kt, library/kotlin/src/io/envoyproxy/envoymobile/BUILD, library/kotlin/src/io/envoyproxy/envoymobile/EnvoyClient.kt, library/kotlin/src/io/envoyproxy/envoymobile/EnvoyClientBuilder.kt, library/kotlin/src/io/envoyproxy/envoymobile/HTTPClient.kt, library/kotlin/test/io/envoyproxy/envoymobile/BUILD, library/kotlin/test/io/envoyproxy/envoymobile/EnvoyClientBuilderTest.kt, library/kotlin/test/io/envoyproxy/envoymobile/EnvoyClientTest.kt
Description: Rename Envoy to EnvoyClient
Testing: n/a
=> Rename Envoy to EnvoyClient

.pre-commit-config.yaml, library/common/BUILD, library/common/certificates.inc, library/common/config_template.cc, tools/check_format.sh
Description: This PR inlines certificates for trusted certificate authorities into the config template and adds subject alt name verification to the base cluster. The certificate bundle is the same as that presented in MacOS 10.14.6
Risk Level: High
Testing: Simulator
Fixes #322
=> security: tls configuration for baseline security

.bazelrc
Resolves https://github.com/lyft/envoy-mobile/issues/208.
Testing: Built locally
=> bazel: enable bitcode on release for iOS

.github/workflows/android.yml, examples/java/hello_world/MainActivity.java, examples/kotlin/hello_world/MainActivity.kt, examples/kotlin/shared/ResponseViewHolder.kt
Description: the liveliness CI tests for android are flaky because the response view holder doesn't log with high fidelity without UI interaction. This PR changes the logs to be printed in the main activity.
Testing: CI
=> android: move liveliness log to main

.bazelrc
This runtime is available in Xcode 11 by default.
=> bazel: use iOS 13 by default

examples/objective-c/hello_world/ViewController.m, examples/swift/hello_world/ViewController.swift
As of https://github.com/lyft/envoy-mobile/pull/428, we now queue API calls while Envoy starts up, so the 1s delay is no longer required. Removing the outdated docstrings.
=> examples: remove outdated docstrings

.github/workflows/android.yml, library/java/test/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt, library/kotlin/test/io/envoyproxy/envoymobile/EnvoyClientBuilderTest.kt, library/kotlin/test/io/envoyproxy/envoymobile/EnvoyClientTest.kt, library/kotlin/test/io/envoyproxy/envoymobile/RequestMapperTest.kt, library/kotlin/test/io/envoyproxy/envoymobile/ResponseHandlerTest.kt, library/kotlin/test/io/envoyproxy/envoymobile/RetryPolicyMapperTest.kt
We weren't running CI for the java tests previously because they weren't being specified in the CI task
Description: kotlin: fix unit tests and add java tests to ci
Testing: unit
=> kotlin: fix unit tests and add java tests to ci

library/common/main_interface.cc, library/common/main_interface.h, library/common/types/c_types.h
Description: This is to allow OS/platform reachability signals to be consumed by the Envoy library engine.
Co-authored-by: Jose Nino <jnino@lyft.com>
=> core: introduce interface for setting preferred network

library/common/config_template.cc, library/common/http/dispatcher.cc, library/common/http/dispatcher.h, library/common/main_interface.cc, library/common/main_interface.h, library/common/types/c_types.h, test/common/http/dispatcher_test.cc
Description: Consumes OS network preference signals to classify connections based on when they're created. New streams will be opened on connections grouped under the current network indication. Note that sockets are still opened by syscalls and so it is simply assumed they are attached to the appropriate network interface.
Testing: CI and local testing
Co-authored-by: Jose Nino <jnino@lyft.com>
=> core: add network-specific clusters to support OS preference

library/common/http/BUILD, library/common/http/dispatcher.cc, library/common/http/dispatcher.h, library/common/types/c_types.h
Description: Addresses crashes from locally-generated responses in Envoy leading to inconsistent stream state. A better fix will require an upstream change. Additionally, this adds a mechanism to map local error responses into error callbacks. This path could also be greatly improved with upstream changes.
Testing: CI and local
Co-authored-by: Mike Schore <mike.schore@gmail.com>
=> core: deal with local replies

dist/BUILD, library/objective-c/BUILD, library/objective-c/EnvoyEngine.h, library/objective-c/EnvoyEngineImpl.m, library/objective-c/EnvoyNetworkMonitor.m
Adds an implementation of observing reachability on iOS which calls in to the function added in https://github.com/lyft/envoy-mobile/pull/443 to notify Envoy of a change in preferred network selection.
Note that since the core maintains a singleton ref to the preferred network, these observations are also static and are not discarded. This should be addressed as part of implementing shutdown functionality in https://github.com/lyft/envoy-mobile/issues/445.
=> ios: update preferred networks via reachability

library/objective-c/BUILD, library/swift/test/EnvoyClientBuilderTests.swift
These were missed because tests aren't running on CI (attempting to get that fixed in https://github.com/lyft/envoy-mobile/pull/463). Ran them locally to validate they work properly.
=> swift: fix tests

.bazelrc
When uploading an app with the previous `--config=release` configuration, bitcode wasn't actually present.
Bazel doesn't seem to be passing `-fembed-bitcode` for C targets when using `--apple_bitcode`, so we need to do so manually.
=> bazel: fix bitcode

library/swift/src/RequestMethod.swift
This can be useful to external consumers since the names of the enum cases are not convertible to strings due to the `@objc` attribute.
For example, when printing `print(RequestMethod.get)`, this will log `RequestMethod` instead of `get` right now since Objective-C int-backed enums don't store the names of Swift cases. Adding this read-only string representation allows consumers to utilize it.
=> swift: make RequestMethod.stringValue public

library/common/config_template.cc
Description: Factors out some of the more complex replicated content in the template. Without merge key support in yaml-cpp, this is probably the extent of what we can do.
=> config: factor out some of the replication in config

library/common/jni_interface.cc, library/java/src/io/envoyproxy/envoymobile/engine/AndroidEngineImpl.java, library/java/src/io/envoyproxy/envoymobile/engine/AndroidJniLibrary.java, library/java/src/io/envoyproxy/envoymobile/engine/AndroidNetworkMonitor.java, library/java/src/io/envoyproxy/envoymobile/engine/BUILD
Description: Adds a platform network monitor to Android to leverage the set_preferred_network interface. This implementation only works on Lollipop and above, and does rely on some methods deprecated in the most recent versions of Android - in order to be compatible with multiple versions and not unnecessarily complicated.
Testing: local, CI, and physical device
=> android: create network condition monitor

WORKSPACE, bazel/boringssl.patch
When linking envoy-mobile to an iOS app that ships with bitcode, you get
these warnings from the linker:
```
ld: warning: Linker asked to preserve internal global: 'sk_CRYPTO_BUFFER_call_free_func'
ld: warning: Linker asked to preserve internal global: 'sk_X509_call_free_func'
ld: warning: Linker asked to preserve internal global: 'sk_X509_call_free_func'
ld: warning: Linker asked to preserve internal global: 'sk_X509_call_free_func'
ld: warning: Linker asked to preserve internal global: 'sk_X509_call_free_func'
```
I have submitted an upstream patch to fix this
https://boringssl-review.googlesource.com/c/boringssl/+/37804 in the
meantime I've applied that patch here.
=> Work around BoringSSL bitcode linker warning

library/common/types/c_types.h, library/objective-c/EnvoyEngine.h, library/objective-c/EnvoyHTTPStreamImpl.m, library/swift/test/MockEnvoyHTTPStream.swift
Description: Better fit for storing opaque memory addresses and/or sentinel values.
=> core: change handles to a more suitable type

.bazelrc
This changes the release config to use bazel's compilation_mode=opt
which implies the necessary optimization options, and some other things.
This also removes the linkopt that appears to do nothing, and requires
you pass some configuration about architectures separately.
=> bazel: update release config

.bazelrc
This reverts commit 2c345529580daf2985dc99823ce6701898f3ca63. We noticed when building with these new release options that builds fail with the following errors:
```
Uncompressed input jar has size 18446744072925756006, which exceeds the maximum supported output size 4294967295.
Assuming that ijar will be smaller and hoping for the best.
Target //:ios_dist failed to build
```
=> Revert "bazel: update release config (#479)"

bazelw
Description: Just makes it easier to update validation when .bazelversion changes.
=> build: update bazelw to print sha on mismatch

library/objective-c/EnvoyHTTPStreamImpl.m
Description: Ensure we get a compiler warning if the type declared in the bridge header doesn't match the internal type.
=> objc: use internal type for handle in EnvoyHTTPStreamImpl

WORKSPACE
Description: This will hopefully allow for both faster and more reliable builds. http_archive contains built-in retry logic, and pulls down smaller artifacts (no history).
=> build: use http_archive instead of git_repository

library/kotlin/test/io/envoyproxy/envoymobile/ResponseHandlerTest.kt
Adding countdown latch for ensuring we have asserted the response callback data
Description: kotlin: fix no-oped tests in ResponseHandlerTest
Testing: unit
=> kotlin: fix no-oped tests in ResponseHandlerTest

library/kotlin/src/io/envoyproxy/envoymobile/EnvoyStreamEmitter.kt, library/kotlin/src/io/envoyproxy/envoymobile/StreamEmitter.kt, library/kotlin/test/io/envoyproxy/envoymobile/EnvoyClientTest.kt, library/swift/src/EnvoyStreamEmitter.swift, library/swift/src/GRPCStreamEmitter.swift, library/swift/src/StreamEmitter.swift, library/swift/test/GRPCStreamEmitterTests.swift
Description: the gRPC protocol requires closing the client stream in a DATA frame. This PR fixes the GRPCStreamEmitter for iOS.
Risk Level: med - protocol level changes.
Testing: local.
=> grpc: close stream with data frame

library/swift/test/GRPCStreamEmitterTests.swift
Adding a test to match Android (see [this comment](https://github.com/lyft/envoy-mobile/pull/472#discussion_r335070694)) to validate that gRPC streams are closed with `nil` trailers, so as to force the stream to close with a data frame per the gRPC protocol spec.
=> swift: add test for closing gRPC streams

library/swift/src/GRPCResponseHandler.swift
These were missing `- returns`.
=> swift: fix GRPCResponseHandler docstrings

library/common/BUILD, library/common/engine.cc, library/common/engine.h, library/common/jni_interface.cc, library/common/main_interface.cc, library/common/main_interface.h, library/java/src/io/envoyproxy/envoymobile/engine/EnvoyEngineImpl.java, library/java/src/io/envoyproxy/envoymobile/engine/JniLibrary.java, library/objective-c/EnvoyEngineImpl.m, test/performance/test_binary_size.cc
Description: create a class to manage Envoy lifecycle and allow for graceful teardown. Teardown is now graceful for both iOS and Android. Envoy's codebase expects to have shutdown happen from the main thread. However, in mobile the thread the engine runs in is not the main thread of the process, and thus shutdown/destructors were not getting run from the thread the engine was started on. This PR makes sure that the engine is destructed/shutdown from the thread that it ran in.
Risk Level: high. This PR changes state management for the engine, and initializes it on a std::thread instead of a platform thread. iOS thread management is afaict handled gracefully. On Android the native thread has to be attached and detached from the JVM. This PR attaches the native thread, but the work to detach …
=> core: envoy engine

library/swift/src/GRPCResponseHandler.swift, library/swift/test/GRPCResponseHandlerTests.swift
Updates the Swift gRPC response compression error handling logic to match Android's:
- Instead of silently failing, call `onError` in a terminal state and clear out other callbacks
- Retain the `GRPCResponseHandler` while the core Envoy engine retains the underlying `onData` callback to ensure that error and message propogation can be called by the handler
Context: https://github.com/lyft/envoy-mobile/pull/472#discussion_r335064658
=> swift: handle gRPC compression errors

library/common/jni_interface.cc, library/java/src/io/envoyproxy/envoymobile/engine/JvmCallbackContext.java
Description: this PR wires up on trailers callback for android, which was previously missing.
Risk Level: low - using already battled tested code paths for accumulating headers.
Testing: pending testing with gRPC on the Lyft android app
Fixes #506 
=> android: wire up on trailers

library/common/engine.cc, library/common/engine.h, library/common/jni_interface.cc, library/common/main_interface.cc, library/common/main_interface.h, library/common/types/c_types.h, library/objective-c/EnvoyEngineImpl.m, test/performance/test_binary_size.cc
Description: this is a follow up to #498. This PR introduces `envoy_engine_callbacks`. They are similar in nature to envoy_http_callbacks. The difference being that they are not exposed all the way to consumer level in the library as it is not needed right now. However, one can see how by adding a type erased context pointer, and following the platform patterns for http callbacks we could thread this all the way up if need be. The immediate need for these callbacks is to detach the engine's native thread from the JVM on Android.
Risk Level: med -- adds complexity to engine management.
Testing: local testing on devices (Lyft and example app on iOS and Android).
In conjunction with #498 this PR Fixes #492 #445 
=> core: engine callbacks -- add on_exit

library/kotlin/src/io/envoyproxy/envoymobile/GRPCResponseHandler.kt
In the case where the client receives an unsupported compressed message, the `errorClosure` should be cleared out with the other handlers after being called once. This will prevent it from being called again if multiple compressed messages are received, which is the intended behavior as `onError` should be considered a terminal state.
=> kotlin: clear error closure after compression error

.github/workflows/artifacts.yml
Description: ci: update artifact to only run for common/java/kotlin
Testing: on master
Release Notes:
=> ci: update artifact to only run for common/java/kotlin

library/swift/src/RetryPolicy.swift, library/swift/src/RetryPolicyMapper.swift, library/swift/test/RetryPolicyMapperTests.swift
When users set a timeout via `perRetryTimeoutMS`, they silently get limited to 15 seconds due to the fact that Envoy assigns a [default timeout of 15 seconds](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#envoy-api-field-route-routeaction-timeout). We should expose this through our `RetryPolicy` to allow consumers to override it using the already-supported `x-envoy-upstream-rq-timeout-ms` header.
Related Kotlin PR: https://github.com/lyft/envoy-mobile/pull/519
Details on retry semantics: [Envoy docs](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_routing.html?highlight=exponential#retry-semantics)
=> swift: add support for total upstream timeouts

library/kotlin/src/io/envoyproxy/envoymobile/RetryPolicy.kt, library/kotlin/src/io/envoyproxy/envoymobile/RetryPolicyMapper.kt, library/kotlin/test/io/envoyproxy/envoymobile/RetryPolicyMapperTest.kt
When users set a timeout via `perRetryTimeoutMS`, they silently get limited to 15 seconds due to the fact that Envoy assigns a [default timeout of 15 seconds](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#envoy-api-field-route-routeaction-timeout). We should expose this through our `RetryPolicy` to allow consumers to override it using the already-supported `x-envoy-upstream-rq-timeout-ms` header.
Related Swift PR: https://github.com/lyft/envoy-mobile/pull/518
Details on retry semantics: [Envoy docs](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_routing.html?highlight=exponential#retry-semantics)
=> kotlin: add support for total upstream timeouts

library/kotlin/src/io/envoyproxy/envoymobile/RetryPolicy.kt, library/kotlin/src/io/envoyproxy/envoymobile/RetryPolicyMapper.kt, library/kotlin/test/io/envoyproxy/envoymobile/RequestBuilderTest.kt, library/kotlin/test/io/envoyproxy/envoymobile/RequestMapperTest.kt, library/kotlin/test/io/envoyproxy/envoymobile/RetryPolicyMapperTest.kt
Updating to match iOS and `totalUpstreamTimeoutMS`.
=> kotlin: update capitalization of perRetryTimeoutMS

library/swift/src/RetryPolicy.swift
=> ios: update RetryPolicy Equatable conformance

library/objective-c/EnvoyEngine.h, library/objective-c/EnvoyEngineImpl.m, library/objective-c/EnvoyHTTPStreamImpl.m, library/swift/src/EnvoyClient.swift, library/swift/test/EnvoyClientBuilderTests.swift, library/swift/test/EnvoyClientTests.swift, library/swift/test/MockEnvoyHTTPStream.swift
Updates to utilize the options exposed in https://github.com/lyft/envoy-mobile/pull/520 to prevent unnecessarily buffering requests that will never be retried. This can be especially useful for preventing buffering of long-lived [gRPC] streams, for example.
We discussed having a full fledged platform level struct to parallel `envoy_stream_options`, but decided that while we only expose one option we can leave the API as a boolean argument.
Matching Android functionality is being tracked here: https://github.com/lyft/envoy-mobile/issues/524.
=> ios: only buffer when requests support retries

.github/workflows/artifacts.yml, library/kotlin/src/io/envoyproxy/envoymobile/RetryPolicy.kt
These builds are taking longer than the original 45minutes since we are building multiple architectures on a release configuration
We're going to make it 90minutes and see if it works
Description: ci: update to 90m for aar master generation
Testing: on master
=> ci: update to 90m for aar master generation

library/common/engine.cc
Description: when the server pointer was moved from being captured in the post init callback to outside of it https://github.com/lyft/envoy-mobile/pull/498/files#diff-b5c0c85b8d3df6960fe582b70fe1c122L112 to https://github.com/lyft/envoy-mobile/pull/498/files#diff-79839c4e6bee0a2fa78e0f8215db7433R64 we introduced the possibility that the captured pointer pointer to an invalid memory address. This PR returns the server capture to inside the callback.
Risk Level: med - moving pointer captures from synchronous to inside the event loop
=> core: fix server early capture

library/common/engine.cc
Description: #498 did not fully solve https://github.com/lyft/envoy-mobile/issues/492. The reset cleanly destructed all objects. However, because destruction was posted in to the event dispatcher, the event dispatcher was left with bad accesses. 
This PR fixes the issue by issuing shutdown on the dispatcher, and only destructing once the event loop has exited and control has returned to the Engine's run function.
Risk Level: med - fixing crash on shutdown
Testing: local
Fixes #492 
=> core: fix shutdown libevent crash

library/swift/src/EnvoyClient.swift
Recent changes (namely https://github.com/lyft/envoy-mobile/pull/498) made it unnecessary for the platform-level clients to start Envoy on newly spawned threads. In fact, these changes actually introduced potential races where consumers of the platform clients could end up calling `send` on engines that hadn't finished starting on these threads.
This PR removes the custom threading logic in Swift in favor of simply using the new threading being done within the core. Another PR will make the same change on Android: https://github.com/lyft/envoy-mobile/pull/531.
=> ios: use internal engine thread

library/kotlin/src/io/envoyproxy/envoymobile/EnvoyClient.kt
Description: "Recent changes (namely #498) made it unnecessary for the platform-level clients to start Envoy on newly spawned threads. In fact, these changes actually introduced potential races where consumers of the platform clients could end up calling send on engines that hadn't finished starting on these threads."
This PR removes the custom threading logic in Kotlin in favor of simply using the new threading being done within the core. Parallel to #530.
Risk Level: med - reduce threading complexity
Testing: local app.
=> android: use internal engine thread

library/kotlin/src/io/envoyproxy/envoymobile/GRPCStreamEmitter.kt, library/kotlin/test/io/envoyproxy/envoymobile/GRPCStreamEmitterTest.kt, library/swift/src/GRPCStreamEmitter.swift, library/swift/test/GRPCStreamEmitterTests.swift
We should support chaining with gRPC stream emitters the same way we do for HTTP stream emitters.
I.e.,
```
let emitter = ...
.sendMessage(...)
.sendMessage(...)
```
This PR also updates tests to use chaining syntax for gRPC.
=> grpc: support chaining emitters

library/common/engine.cc
Description: At the point where this destructor is being called, the OS is already trying to terminate the thread holding Envoy's static state. shutdown() may simply not be aggressive enough to tear things down in time. This will cause the event loop to exit.
=> core: shut down more aggressively in the engine destructor

.bazelrc
Description:
When building for debug with Bazel, both local and remote should have local paths excluded from the binary, or at minimum, normalized paths before being embedded in the binary.
This change enables bazel's `debug_prefix_map_pwd_is_dot` feature, which uses [clang's `-fdebug-prefix-map`](https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-fdebug-prefix-map). For details, see https://github.com/bazelbuild/bazel/commit/3f46dd0f6d5a042fc28d265411a6014f666a40c1 and https://github.com/bazelbuild/bazel/issues/5545.
This same feature is already enabled by default for swift.
Additionally for swift, enable the `cacheable_swiftmodules` feature. This ensures that local paths are not embedded in `.swiftmodule` files. For details, see …
=> bazel: enable cacheable binaries

library/common/main_interface.cc
Description: Access Engine via weak_ptr so that threads can extend its lifetime for the durations of their calls to it. Despite the fact that all incoming calls are ultimately dispatched to the underlying Envoy main thread, there exists a window where the thread must leverage Engine state (e.g. to access the dispatcher) that can otherwise race with the Engine lifecycle. While it's probably possible to cover these edge cases at the platform layer, this provides a common solution.
Testing: local and CI
=> core: expose engine via weak_ptr

.github/workflows/artifacts.yml
This archive is actually a zip containing the produced aar, so this
makes that a bit less confusing.
=> ci: Change aar archive name

.bazelrc, .github/workflows/artifacts.yml, docs/root/start/building/building.rst
Because we shared the `release` bazel config between both iOS and
Android, Android builds were incorrectly having llvm bitcode enabled for
them.
=> bazel: Fix bitcode for android binaries

.github/workflows/artifacts.yml
We previously only rebuilt when common or Android code changed. However, there are several other cases where we'd want to rebuild artifacts on push to master even if those source files haven't changed:
- Bazel version is updated
- Build configs are updated
- CI configs are updated
Rather than maintain a list of paths we care about, we can simply rebuild on any merge to master.
=> ci: build artifacts on all pushes to master

.bazelrc, docs/root/start/building/building.rst
Include the `ios` config by default when using `release-ios`. Also updates the docs for clarity on usage.
=> bazel: include iOS config with release

.bazelrc, docs/root/development/performance/cpu_battery_impact.rst, envoy-mobile.tulsiproj/project.tulsiconf
Removes some build configurations that we don't explicitly use anywhere. Documentation suggests explicitly using `--ios_multi_cpus` or `--fat_apk_cpu`.
Follow up to https://github.com/lyft/envoy-mobile/pull/563#discussion_r340821651
=> bazel: remove unused build configs

.github/workflows/artifacts.yml
Adds a job that runs on master and builds/uploads a zip artifact of the `Envoy.framework` for iOS using the release configurations. This should make it easier for consumers to utilize the most recent iOS versions of Envoy Mobile.
Resolves https://github.com/lyft/envoy-mobile/issues/547.
Tested against this PR, which resulted in the expected artifacts being uploaded successfully:
=> ci: add job to publish iOS release artifact on merge to master

.github/workflows/artifacts.yml
Previously, the artifacts would appear on GitHub Actions as:
- `envoy_android_aar.zip`
- `envoy_ios_framework.zip`
These would then unzip to:
- `envoy_android_aar.zip.zip`
- `envoy_android_aar.zip/envoy.aar`
And:
- `envoy_ios_framework.zip.zip`
- `envoy_ios_framework.zip/Envoy`
- `envoy_ios_framework.zip/Headers`
- `envoy_ios_framework.zip/Modules`
This was confusing and actually ended up mis-naming both the zip files and the framework.
With the changes in this PR, the new artifacts will be:
- `envoy_android_aar`
- `envoy_ios_framework`
And will unzip to:
- `envoy_android_aar.zip`
- `envoy_android_aar/envoy.aar`
And:
- `envoy_ios_framework.zip`
- `envoy_ios_framework/Envoy.framework/*`
=> ci: update format of master artifacts

library/common/jni_interface.cc
Description: We don't actually call this check anywhere anymore.
Testing: CI
=> cleanup: remove ares init check

library/common/config_template.cc, library/java/src/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java, library/java/test/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt, library/kotlin/src/io/envoyproxy/envoymobile/EnvoyClientBuilder.kt, library/kotlin/test/io/envoyproxy/envoymobile/EnvoyClientBuilderTest.kt, library/kotlin/test/io/envoyproxy/envoymobile/EnvoyClientTest.kt, library/objective-c/EnvoyConfiguration.m, library/objective-c/EnvoyEngine.h, library/swift/src/EnvoyClientBuilder.swift, library/swift/test/EnvoyClientBuilderTests.swift
Description: this PR adds configuration to flush metrics from Envoy Mobile to a backend metrics service via Envoy's metrics_service API.
Risk Level: low - with respect to the library, higher risk for orgs using the library and ingesting metrics from their mobile clients.
Testing: locally, and with e2e with Lyft's infrastructure. Added unit tests for the new config templating.
=> metrics: add configuration for flushing stats via a metrics service

library/objective-c/EnvoyEngine.h, library/objective-c/EnvoyHTTPStreamImpl.m, library/swift/test/MockEnvoyHTTPStream.swift
At the moment, we leak all `EnvoyHTTPStreamImpl` and `EnvoyHTTPCallbacks` instances with every stream due to the deliberate retain cycle used to keep the stream in memory and pass callbacks through to the platform layer while the stream is active. This ends up also leaking the callback closures specified by the end consumer, along with anything captured by those closures.
To resolve this problem, we will release the strong reference cycle that the stream holds to itself when the stream completes.
The state/callback for stream completion has to be stored somewhere in the `ios_context` type and retained since the `ios_context` is a struct and doesn't retain its members.
We considered having the `EnvoyHTTPCallbacks` hold a reference to the `EnvoyHTTPStreamImpl` rather than having …
=> ios: fix leaking of http streams

EnvoyMobile.podspec
Makes several updates to our podspec in order to fix CocoaPods integration with v0.2.0:
- Link `resolv.9` and `c++` which is being done with Bazel today
- Link `SystemConfiguration` which is being done with Bazel today
- Specify Swift version and platform version
- Specify `source_files` **with an empty `.swift` file** in order to ensure that Swift libraries are linked when building (i.e., `swiftFoundation`)
**Important notes:**
Releasing new versions of the pod requires the following manual changes:
- Unzipping `envoy_ios_framework.zip`
- Renaming the directory to `envoy_ios_cocoapods`
- Creating an empty file at `envoy_ios_cocoapods/Envoy.framework/Swift/Empty.swift`. This forces CocoaPods to link Swift libraries as necessary. We worked around this in Bazel similarly in the past …
=> ios: fix podspec for v0.2.0 support

library/objective-c/EnvoyEngine.h, library/objective-c/EnvoyHTTPStreamImpl.m
Description: Fixes a race in cleanup timing by ensuring cleanup is ALWAYS dispatched from Envoy's main thread to the callback thread for a given stream, AFTER reset or completion has been handled at the common layer.
Testing: CI
=> ios: make stream cleanup (more) thread-safe

.github/workflows/android.yml, .github/workflows/artifacts.yml, .gitignore, BUILD, WORKSPACE, library/BUILD
- Using https://github.com/Kotlin/dokka/releases/tag/0.9.18 to generate `javadocs.jar` based on the `library/` directory. 
- Copying our source files into a single jar for `envoy-sources.jar`
- Zipping up the sources jar, javadocs, pom xml, and aar on `artifact.yaml`
I am using a bit of a shortcut as we are indiscriminately generating javadocs for all kotlin/java files in our directory to generate these files
Description: android: add javadoc generation for aar
Testing: local
=> android: add javadoc and sources jar generation for aar

library/objective-c/EnvoyHTTPStreamImpl.m
Description: saw a warning on master compilation. Cleaning up.
Testing: compiles, code inspection.
=> ios stream: clean up warning

.github/workflows/artifacts.yml
use env variables from android
Description: use env variables from android
Testing: local
=> ci: use env variables from android

WORKSPACE
Description: bazel: update rules_jvm_external to 2.10
Testing: ci
=> bazel: update rules_jvm_external to 2.10

.github/workflows/android.yml, .github/workflows/core.yml, .github/workflows/format.yml, .github/workflows/ios.yml, .github/workflows/perf.yml
This should make CI run on externally contributed PRs, rather than just PRs made from branches within this repo.
=> ci: run on external PRs

library/objective-c/EnvoyHTTPStreamImpl.m
Description: Updates callback logic to ensure only one of any terminal callback is fired per stream/requests: one of final-onHeaders, final-onData, onTrailers, onError, and onCancel. Additionally ensures that it will be the last callback (iff provided callback dispatch is serial).
Risk: Low
=> ios: only fire a single 'terminal' callback per stream

library/java/src/io/envoyproxy/envoymobile/engine/EnvoyHTTPStream.java, library/java/src/io/envoyproxy/envoymobile/engine/JvmCallbackContext.java
Description: Updates callback logic to ensure only one of any terminal callback is fired per stream/requests: one of final-onHeaders, final-onData, onTrailers, onError, and onCancel. Additionally ensures that it will be the last callback (iff provided callback dispatch is serial).
Risk: Low
=> android: only fire a single 'terminal' callback per stream

WORKSPACE, bazel/aar_with_jni.bzl
We're packaging kotlin with our aar classes.jar and in the aar itself.
This change is to remove that by manually excluding specific directories from the `deploy.jar`. Additionally, we removed some unnecessary artifacts from the aar itself. Here's what it looks like now:
```
Archive:  envoy.aar
AndroidManifest.xml     
classes.jar             
jni/
jni/armeabi-v7a/
jni/armeabi-v7a/libenvoy_jni.so  
jni/x86/
jni/x86/libenvoy_jni.so  
jni/arm64-v8a/
jni/arm64-v8a/libenvoy_jni.so  
proguard.txt     
```
https://developer.android.com/studio/projects/android-library
Description: …
=> android: remove kotlin bundling from aar

library/common/config_template.cc
Description: Because we associate connections to a network interface heuristically and because we don't currently have a good request-independent signal for connection health (like h2 pings), TCP keepalives may be the next best thing. This change aims to address reports of hung requests by setting fairly aggressive keepalive settings to detect dead connections.
After a connection is idle for 5 seconds, we'll begin sending keepalives on a 10 second interval. If any go unacked in that interval, we'll terminate the connection.
Eventually we'll want to tune this and/or make it configurable and/or rely on something at L7 (like h2 pings).
Testing: In the wild
=> config: experiment with some moderately aggressive keepalive settings

library/objective-c/EnvoyEngine.h
Description:
After opening `EnvoyEngine.h` in Xcode, these two warnings were shown. Applying the fixit suggestion resulted in these changes.
For the block declaration, the diagnostic was:
> This block declaration is not a prototype
I don't think that's a clear explanation. In C and ObjC, these two declarations are **not** the same:
```c
f();
f(void);
```
In C and ObjC, the first function can take _any_ arguments, so you need to use `void` to indicate the function accepts no arguments.
In C++ and ObjC++, `f()` and `f(void)` are the same, so this issue only applies to C/ObjC.
Testing: None
=> Apply warnting fixits to EnvoyEngine.h

library/swift/src/EnvoyError.swift
We have a few cases in tests where we want to allow creation of these
error types, which might warrant this being public.
=> swift: Make EnvoyError initializer public

library/common/certificates.inc, library/common/config_template.cc, library/common/engine.cc, library/common/engine.h, test/common/http/dispatcher_test.cc
Description: this PR updates Envoy Mobile's Envoy ref past the point where Envoy internally uses v3 config. I took the chance to update Envoy Mobile's config and delete deprecated fields. Note that SAN verification changes, and thus it was removed here. I opened an issue tracking #630. Further note that this ref update significantly increased the binary size. It is a priority for the team to investigate and trim the binary ahead of the v0.3 release (noted in #447)
Risk Level: med boost to v3 config and deleted deprecated fields.
Testing: passing liveliness in CI and locally.
=> envoy: update envoy ref and update config to v3 supported schema

.github/workflows/artifacts.yml
Description: the android master artifact is running out of time to build. Extending the timeout to allow it to build. Ultimately we need to track this time down #634 
Testing: CI run
=> android: extend timeout for master artifact

library/common/config_template.cc, test/common/http/dispatcher_test.cc
Description: updating the envoy ref and moving the v3alpha config to v3.
Testing: CI and local
=> envoy: update envoy ref and move v3alpha to v3

.github/workflows/android.yml, .github/workflows/artifacts.yml, .github/workflows/core.yml, .github/workflows/format.yml, .github/workflows/ios.yml
Description:
Some CI jobs for #638 failed with the cause given as:
> The macOS virtual environment has been updated to Catalina (v10.15). Starting January 15th, jobs that include the line 'runs-on: macOS-10.14' will fail to run and return a failed check suite. Please update your workflow and change the line 'runs-on: macOS-10.14' to 'runs-on: macOS-latest'.
This makes the specified changes, moving from `runs-on: macOS-10.14` to `runs-on: macOS-latest`.
Risk Level:
Maybe Low? I'd have to hear from others. It also seems like an upstream requirement.
Testing:
This PR will test mac CI jobs.
=> ci: change runs-on: from macOS-10.14 to -latest

WORKSPACE
Description:
We had reports of debugging issues due to paths that don't exist on developer machines. Previously we enabled the `swift.cacheable_modules` feature to prevent this (see #549). Apparently `rules_foreign_cc_dependencies()` is loading `rules_swift`, and must use a sha that is prior to the introduction of the `cacheable_modules` feature.
This change moves the `rules_swift` repository rule earlier in the `WORKSPACE` – above `rules_foreign_cc_dependencies()` and just below the `rules_appe` repo rule.
Risk Level:
Low
The rules_swift declaration was previously inert, it wasn't being used, so this change is effectively a bump to the rules_swift version being used/dependend on.
Testing:
Used `bazel aquery //library/swift/src:ios_framework_archive` and verified that …
=> build: move rules_swift repo rule earlier

.github/workflows/ios.yml
Description: https://github.com/envoyproxy/envoy/pull/9618 broke the iOS build due to missing symbols. https://github.com/envoyproxy/envoy/pull/9875 fixes. However, in order to expedite a clean master branch this PR moves the Envoy ref back to a stable place. Note that [Android logging](https://github.com/envoyproxy/envoy/pull/9767) is reverted. Also note that CI for iOS was not testing for liveliness, which is how the breakage went through in the first place. This PR also fixes that.
Testing: CI
Fixes https://github.com/lyft/envoy-mobile/issues/646
=> envoy: move ref back to stable

docs/build.sh
Description: reserve tagged docs publishing for vX.Y.Z versions.
Risk Level: low. Can fix if broken without adverse consequences.
Testing: locally running the script with different conditions.
Fixes #644 
=> ci: fix docs publishing

examples/objective-c/hello_world/ViewController.m, examples/swift/hello_world/ViewController.swift, library/common/config_template.cc, library/objective-c/EnvoyConfiguration.m, library/objective-c/EnvoyEngine.h, library/swift/src/EnvoyClientBuilder.swift, library/swift/test/EnvoyClientBuilderTests.swift, library/swift/test/EnvoyClientTests.swift
Description: Removes domain from Envoy engine configuration on iOS. Dynamic forwarding is now default, and so a proper `:authority` header is all that's needed.
=> ios: remove domain from engine configuration

examples/java/hello_world/MainActivity.java, examples/kotlin/hello_world/MainActivity.kt, library/common/config_template.cc, library/java/src/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java, library/java/test/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt, library/kotlin/src/io/envoyproxy/envoymobile/AndroidEnvoyClientBuilder.kt, library/kotlin/src/io/envoyproxy/envoymobile/EnvoyClientBuilder.kt, library/kotlin/test/io/envoyproxy/envoymobile/EnvoyClientBuilderTest.kt, library/kotlin/test/io/envoyproxy/envoymobile/EnvoyClientTest.kt
Description: Removes domain from Envoy engine configuration on Android. Dynamic forwarding is now default, and so a proper `:authority` header is all that's needed.
=> android: remove domain from engine configuration

library/common/http/dispatcher.cc
Description: Envoy's HCM expects calling resetStream() to immediately raise rest callbacks. Thus it does not do a stream destroy in `doEndStream` if it fires a reset. Instead it waits for the reset to come back. This is how the H1/2 codecs work. e.g in h2: https://github.com/envoyproxy/envoy/blob/abb1f969fe131c7a47da5c1ad1577be142e1ea8a/source/common/http/http2/codec_impl.cc#L301 and similarly in h1 (although through some indirection): https://github.com/envoyproxy/envoy/blob/abb1f969fe131c7a47da5c1ad1577be142e1ea8a/source/common/http/http1/codec_impl.cc#L798.
Previously Envoy Mobile's DirectStreams were not propagating the reset back to the HCM. Thus the HCM's ActiveStream was not getting destroyed when the App was receiving upstream resets. This would result in for example idle timers …
=> stream reset: higher layers expect calling resetStream() to immediately raise reset callbacks

library/common/config_template.cc
Envoy's current retry mechanism works relatively aggressively for mobile networks. Today, it defaults to a [base retry interval of `25ms`](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route_components.proto#envoy-api-field-route-retrypolicy-retry-back-off) and a [max retry interval of 10x the base interval](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route_components.proto#route-retrypolicy-retrybackoff).
In order for the retry mechanism to better suit mobile networks, we are tuning these values to match some reasonable defaults in Envoy Mobile using what Lyft has historically used in production:
- Exponential back off + jittering ([implemented in Envoy](https://github.com/envoyproxy/envoy/blob/b495c36e0c583ab673915abf0b06a6e9babac9f9/source/common/ro …
=> config: set default retry back-off policies

docs/root/development/releasing/releasing.rst
`ddmmyy` is not monotonically increasing as months progress during the year (i.e., `January 25th, 2020` yields a version "lower" than `February 3, 2020`).
Starting with `v0.2.2`, we'll be changing the format to a monotonically increasing format of `mmddyy`.
=> docs: update weekly erlease versioning

WORKSPACE, bazel/abseil.patch
Description: update abseil to track upstream Envoy. This will also allow us to test @lizan's suggestion [here](https://github.com/envoyproxy/envoy/pull/9654#issuecomment-580870865)
Risk Level: low. keeps track with Envoy. 
Testing: CI
=> update abseil to track envoy upstream

EnvoyMobile.podspec
The podspec currently expects a nested directory inside of the zip artifact generated by CI for CocoaPods. For example:
`envoy_ios_cocoapods.zip` unzips to:
`envoy_ios_cocoapods > envoy_ios_cocoapods > Envoy.framework...`
The artifact generated from CI (correctly) does not have this extra `envoy_ios_cocoapods` path.
Thus, we need to fix the podspec to reflect this file structure. The spec in this PR is what has been published as `v0.2.2`.
=> cocoapods: fix podspec file paths

library/kotlin/src/io/envoyproxy/envoymobile/RetryPolicy.kt, library/kotlin/src/io/envoyproxy/envoymobile/RetryPolicyMapper.kt, library/kotlin/test/io/envoyproxy/envoymobile/RetryPolicyMapperTest.kt, library/swift/src/RetryPolicy.swift, library/swift/src/RetryPolicyMapper.swift, library/swift/test/RetryPolicyMapperTests.swift
We should allow zero to be specified for `totalUpstreamTimeoutMS`, which effectively [disables the upstream timeout per Envoy's docs](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route_components.proto#envoy-api-field-route-routeaction-timeout).
This can be useful for consumers who only want to timeout on a per-request basis (rather than timing out all retries in aggregate).
=> ios/android: allow zero for total upstream timeouts

library/common/http/dispatcher.cc, library/common/http/dispatcher.h, test/common/http/dispatcher_test.cc
Bumping to include the following fixes:
- `dns: destroy/reinitialize c-ares channel on ARES_ECONNREFUSED`: https://github.com/envoyproxy/envoy/pull/9899. This should resolve the issues we've been seeing with Envoy Mobile hanging on startup and never properly issuing requests if started in the offline state on iOS. Fixes https://github.com/lyft/envoy-mobile/issues/672, though more improvements to DNS resolution will be investigated in lyft/envoy-mobile#673
- `gzip: add force load factory declaration`: https://github.com/envoyproxy/envoy/pull/9942. This will allow us to use the gzip filter with Envoy Mobile
- `api listener: add shutdown method and call during server termination`: https://github.com/envoyproxy/envoy/pull/9959. Fixes https://github.com/lyft/envoy-mobile/issues/667. Fixes …
=> upstream: update Envoy to include new fixes

library/common/http/dispatcher.cc, library/common/http/dispatcher.h, test/integration/dispatcher_integration_test.cc
Description: previously Envoy Mobile was not guarded against a race that resulted in a double deletion of an Http::ConnectionManagerImpl::ActiveStream. This PR creates state that protects against that race.
Risk Level: low, integration test reproe'd the stack trace, and then updated prod code fixed as expected.
Testing: new integration test.
Fixes #668 
=> core: prevent race that causes double delete of HCM ActiveStreams

.gitattributes
Description: remove certificates.inc from language composition.
Testing: locally ran github-linguist
=> git: ignore certificates file for repo language composition

.github/workflows/release.yml
Description: this job keeps timing out #634 for long term solution
=> ci: increase timeout for android master release

.github/workflows/artifacts.yml
Description: only version bumps are used on clients. Therefore, this PR makes it so that the jobs on the artifacts.yml workflow only run when the VERSION file changes. This should save some CI time.
=> ci: only build artifacts on commits that affect the VERSION file

library/common/http/dispatcher.cc, library/common/http/header_utility.cc, library/common/http/header_utility.h, test/common/http/dispatcher_test.cc, test/common/http/header_utility_test.cc, test/integration/dispatcher_integration_test.cc
Description: Update to use new internal types in Envoy.
Risk: Low
Testing: Unit and CI
=> dispatcher: update to use new internal header map types

.github/workflows/perf.yml, tools/check_format.sh
Description: Bump the Envoy ref. This PR brings in the relevant updates to Envoy Mobile:
-  https://github.com/envoyproxy/envoy/pull/10060 which Fixes #687 
Testing: unit test in Envoy, Envoy Mobile local build and CI
Fixes #687 
=> envoy: update ref 021820

library/common/http/dispatcher.cc, library/common/http/dispatcher.h, library/common/jni_interface.cc, library/common/main_interface.cc, library/common/main_interface.h, library/common/types/c_types.h, library/java/src/io/envoyproxy/envoymobile/engine/EnvoyEngine.java, library/java/src/io/envoyproxy/envoymobile/engine/EnvoyEngineImpl.java, library/java/src/io/envoyproxy/envoymobile/engine/EnvoyHTTPStream.java, library/java/src/io/envoyproxy/envoymobile/engine/JniLibrary.java, library/kotlin/src/io/envoyproxy/envoymobile/EnvoyClient.kt, library/kotlin/test/io/envoyproxy/envoymobile/EnvoyClientTest.kt, library/objective-c/EnvoyEngine.h, library/objective-c/EnvoyEngineImpl.m, library/objective-c/EnvoyHTTPStreamImpl.m, library/swift/src/EnvoyClient.swift, library/swift/test/EnvoyClientBuilderTests.swift, library/swift/test/EnvoyClientTests.swift, library/swift/test/MockEnvoyHTTPStream.swift, test/common/http/dispatcher_test.cc, test/integration/dispatcher_integration_test.cc
As of https://github.com/lyft/envoy-mobile/pull/616, this is no longer used or necessary since it's handled by the router.
Resolves https://github.com/lyft/envoy-mobile/issues/643.
=> core: remove envoy_stream_options

.bazelrc
Description: With this change https://github.com/envoyproxy/envoy/pull/10015 Envoy now supports conditionally disabling assertions that cover known issues via build options. This allows us to resolve the crash on shutdown on iOS while the upstream issue is investigated.
Testing: Local, upstream
=> build: disable known issue assertions

docs/root/api/http.rst, examples/java/hello_world/MainActivity.java, examples/kotlin/hello_world/MainActivity.kt, examples/objective-c/hello_world/ViewController.m, examples/swift/hello_world/ViewController.swift, library/common/config_template.cc, library/common/http/dispatcher.cc, library/common/http/dispatcher.h, library/kotlin/src/io/envoyproxy/envoymobile/BUILD, library/kotlin/src/io/envoyproxy/envoymobile/GRPCRequestBuilder.kt, library/kotlin/src/io/envoyproxy/envoymobile/Request.kt, library/kotlin/src/io/envoyproxy/envoymobile/RequestBuilder.kt, library/kotlin/src/io/envoyproxy/envoymobile/RequestMapper.kt, library/kotlin/src/io/envoyproxy/envoymobile/UpstreamHttpProtocol.kt, library/kotlin/test/io/envoyproxy/envoymobile/EnvoyClientTest.kt, library/kotlin/test/io/envoyproxy/envoymobile/GRPCRequestBuilderTest.kt, library/kotlin/test/io/envoyproxy/envoymobile/RequestBuilderTest.kt, library/kotlin/test/io/envoyproxy/envoymobile/RequestMapperTest.kt, library/kotlin/test/io/envoyproxy/envoymobile/RequestTest.kt, library/swift/src/BUILD, library/swift/src/GRPCRequestBuilder.swift, library/swift/src/Request.swift, library/swift/src/RequestBuilder.swift, library/swift/src/RequestMapper.swift, library/swift/src/UpstreamHttpProtocol.swift, library/swift/test/EnvoyClientTests.swift, library/swift/test/GRPCRequestBuilderTests.swift, library/swift/test/RequestBuilderTests.swift, library/swift/test/RequestMapperTests.swift, test/common/http/dispatcher_test.cc
Description: this PR adds the ability to decide what protocol to use for upstream requests. Note that this will be unnecessary once ALPN works for upstream requests (https://github.com/lyft/envoy-mobile/issues/502)
Testing: updated unit tests
Docs Changes: updated docs
Fixes #679 
=> upsteam protocol: add the ability to decide what protocol to use for upstream requests

library/common/config_template.cc
Description: this PR deletes previously duplicated fields in the base cluster.
Testing: CI
=> config: delete redundant fields

library/objective-c/EnvoyHTTPStreamImpl.m
The instantiation of the native `envoy_http_callbacks` has a mis-ordered set of C parameters which resulted in `ios_on_metadata` being called instead of `ios_on_trailers`.
This "works" (doesn't crash) because these are the same type, so it compiles fine.
I identified this problem by looking at trace logs after noticing that iOS trailers were not being passed through to the platform layer. I saw logs for `dispatching to platform response trailers for stream`, but noticed that the callbacks never propagated through to the platform.
At the moment we don't have a test suite that covers this bridging between the C/Obj-C or C/Java layers, but we should cover this in https://github.com/lyft/envoy-mobile/issues/414 / https://github.com/lyft/envoy-mobile/issues/197.
Signed-off-by: Michael Rebello …
=> ios: fix trailers never being called

ci/test_size_regression.sh
We have slightly exceeded the `5MB` size limit here: https://github.com/lyft/envoy-mobile/pull/704/checks?check_run_id=473012084
Rather than disable this job, we're bumping by 500KB and will continue to monitor the size.
=> ci: bump max binary size limit to 5.5MB

library/common/engine.h
This is only called by the implementation of the `Engine`, and can be `private`.
=> core: make `run()` private

library/common/config_template.cc, library/java/src/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java, library/java/test/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt, library/kotlin/src/io/envoyproxy/envoymobile/EnvoyClientBuilder.kt, library/kotlin/test/io/envoyproxy/envoymobile/EnvoyClientBuilderTest.kt, library/kotlin/test/io/envoyproxy/envoymobile/EnvoyClientTest.kt, library/objective-c/EnvoyConfiguration.m, library/objective-c/EnvoyEngine.h, library/swift/src/EnvoyClientBuilder.swift, library/swift/test/EnvoyClientBuilderTests.swift
Description: updates envoy ref to include https://github.com/envoyproxy/envoy/pull/10137. Exposes client builder function to add dns failure refresh rate.
Risk Level: low, new configuration option
Testing: local apps, CI
Docs Changes: created #715 to create a section in the docs for all the builder options.
Fixes #673
=> dns: add ability to set dns failure refresh rate

library/common/config_template.cc
Adding the following stats to the allow-list based on [these Envoy docs](https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats):
- `upstream_rq_retry`
- `upstream_rq_retry_overflow`
- `upstream_rq_retry_success`
Also re-alphabetized the stats list.
=> stats: emit stats for retries

library/common/engine.cc, library/common/engine.h, library/common/main_interface.cc, library/common/main_interface.h
Adds functionality built on top of the upstream Envoy changes in https://github.com/envoyproxy/envoy/pull/10097 which will allow the bridging layers to manually flush stats based on lifecycle changes in the mobile application.
Note: Stats must be flushed from the main Envoy thread, as validated by the following assertion failure that occurs when attempting to flush from another thread:
```
[2020-02-27 14:38:43.181][4716580][critical][assert] [external/envoy/source/common/thread_local/thread_local_impl.cc:190] assert failure: std::this_thread::get_id() == main_thread_id_.
```
Follow-up PRs will call these functions from Java/Objective-C.
Part of https://github.com/lyft/envoy-mobile/issues/573.
=> core: expose functionality for flushing stats manually

library/common/engine.h
=> core: add missing header docstrings

library/common/jni_interface.cc
Updates the `ANDROID_LOG_ERROR` calls to instead use `VERBOSE` or `INFO` in order to more appropriately show up in the console.
Also updates the tag to use `[Envoy]` for parity with iOS.
In the future, we may investigate options for more native logging: https://github.com/lyft/envoy-mobile/issues/719
=> android: update log levels + tags

library/java/src/io/envoyproxy/envoymobile/engine/AndroidEngineImpl.java
We should be registering the application for lifecycle callbacks in both the typed config and YAML config cases.
Related to https://github.com/lyft/envoy-mobile/pull/717/files.
=> android: fix app lifecycle monitoring with typed config

library/common/engine.h
Fixes an [issue](https://github.com/lyft/envoy-mobile/issues/729) where the library could potentially race and crash when calling `flushStats` when `server_` has not yet been assigned. @junr03 astutely pointed out that this could be caused by the fact that `server_` is not assigned to anything, so the `if (server_)` check does not perform as expected. To fix this, we should assign it to `nullptr` immediately.
I was able to simulate the race by calling `flushStats()` at the top of `Engine::run()` (before `server_` is assigned). With this patch, the crash disappears.
Resolves https://github.com/lyft/envoy-mobile/issues/729.
=> core: fix crash with potential race

library/common/http/dispatcher.cc
Description: I noticed that we were logging before all the header mutations. Moved the log statement _after_ mutations happen.
=> core: move log line after header mutation

library/common/http/dispatcher.cc, test/common/http/dispatcher_test.cc
Description: in order to prevent the Http::ConnectionManager from sanitizing retry headers attached by the platform, streams are now marked by `is_internally_created` true.
Risk Level: medium, but output shown below shows that the requests still have expected headers.
Testing: log and behavior confirmation. Integration tests are needed and will be focus of imminent work.
Fixes #733
=> core: make streams with`is_internally_created`

docs/root/development/performance/cpu_battery_impact.rst
Re-ran the analysis on CPU/battery with the current version of Envoy Mobile, and am updating the documentation accordingly. The code used to run the analysis is linked in the documentation and available at https://github.com/rebello95/EnvoyMobileAnalysis/tree/v0.2.3.03062020.
Resolves https://github.com/lyft/envoy-mobile/issues/536, and created https://github.com/lyft/envoy-mobile/issues/741 to track re-running the Android analysis.
=> docs: update with new cpu/memory analysis

.github/workflows/artifacts.yml
Description: After #750 I moved the deps install to use the script in Envoy. This means that the CI checkout needs to be recursive. The only path not updated was the cocoapods artifact. This PR fixes it.
=> cocoapods: checkout submodules

docs/root/api/starting_envoy.rst, library/common/config_template.cc, library/java/src/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java, library/java/test/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt, library/kotlin/src/io/envoyproxy/envoymobile/EnvoyClientBuilder.kt, library/kotlin/test/io/envoyproxy/envoymobile/EnvoyClientBuilderTest.kt, library/kotlin/test/io/envoyproxy/envoymobile/EnvoyClientTest.kt, library/objective-c/EnvoyConfiguration.m, library/objective-c/EnvoyEngine.h, library/swift/src/EnvoyClientBuilder.swift, library/swift/test/EnvoyClientBuilderTests.swift
Description: this PR adds `app_version` and `app_id` to the available fields in the node metadata for Envoy Mobile's config. It also adds Client Builder functions to allow the user to override these values. These values can be used to identify the clients making use of Envoy Mobile.
Note that we have discussed making the information in the node metadata fully dynamic. However, that type of change bears some more thinking implementation wise. I am tracking this in #755.
Risk Level: low, adds new information to the node metadata.
Testing: added unit tests.
Docs Changes: updated the client builder docs.
=> config: add app metadata to node config

.pre-commit-config.yaml, ci/linux_ci_setup.sh
Description: messed up gpg keys for heroku on github actions hosted machines. I opened https://github.com/heroku/cli/issues/1464 with heroku to start a discussion. For now I found in https://cli-assets.heroku.com/install-ubuntu.sh where they host their key.
=> ci: add missing key

library/common/config_template.cc
Description: this enables emitting stats for calculating SR.
Testing: local emission
=> stats: emit cluster upstream rq status code counters

docs/root/api/starting_envoy.rst, library/common/config_template.cc, library/java/src/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java, library/java/test/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt, library/kotlin/src/io/envoyproxy/envoymobile/EnvoyClientBuilder.kt, library/kotlin/test/io/envoyproxy/envoymobile/EnvoyClientBuilderTest.kt, library/kotlin/test/io/envoyproxy/envoymobile/EnvoyClientTest.kt, library/objective-c/EnvoyConfiguration.m, library/objective-c/EnvoyEngine.h, library/swift/src/EnvoyClientBuilder.swift, library/swift/test/EnvoyClientBuilderTests.swift
Description: Virtual Clusters allow Envoy Mobile to emit stats based on matching criteria. This allows users to single out important traffic for their application. This PR adds an API to the client builder to add virtual cluster configuration and emission of virtual cluster stats.
Note: the client builder API exposed here is not ideal #770 tracks enhancing this.
Testing: unit tests, and local stats test. #769 tracks adding CI tests for stats
Docs Changes: added docs for the new API.
=> stats: add segmentation of stats via virtual clusters

.github/workflows/ios.yml
Description: iOS CI greps for indicators of liveliness. Sometimes they fail in CI when local runs are ok. This additional step should show us if CI failures are flakes or real.
Testing: CI
=> ci: cat iOS log to check when CI flakes

library/common/config_template.cc
Description: since traffic was moved to be able to select h2, upstream_rq_active is useful to determine concurrency.
Testing: CI
=> stats: add emission rule for upstream_rq_active

library/common/config_template.cc
Description: previously the cluster configuration for circuit breakers was not specified. This meant that Envoy Mobile was using the default of 3 concurrent retries. This is not appropriate, specially because all* active traffic goes through the same cluster. This PR changes the configuration and explicitly sets the `retry_budget` configuration.
Risk Level: low (more retries will actually be allowed)
Testing: local
=> retries: enable retry budget for concurrent retries

library/common/config_template.cc
Description: this PR adds emission of some downstream_rq metrics to compliment the upstream_rq metrics already emitted. This will allow users to have a view of both network success (upstream_rq) and client perceived success (downstream_rq)
Testing: local
=> stats: emit downstream_rq http metrics

dist/sonatype_nexus_upload.py
The logic in the original script was incorrect, and we could end up infinitely retrying until the job times out.
=> ci: prevent infinite retries of sonatype upload

library/kotlin/src/io/envoyproxy/envoymobile/EnvoyStreamEmitter.kt, library/kotlin/src/io/envoyproxy/envoymobile/GRPCStreamEmitter.kt, library/kotlin/src/io/envoyproxy/envoymobile/StreamEmitter.kt, library/kotlin/test/io/envoyproxy/envoymobile/EnvoyClientTest.kt, library/kotlin/test/io/envoyproxy/envoymobile/GRPCStreamEmitterTest.kt, library/swift/src/EnvoyStreamEmitter.swift, library/swift/src/GRPCStreamEmitter.swift, library/swift/src/StreamEmitter.swift, library/swift/test/GRPCStreamEmitterTests.swift
Replaces the `close(trailers: Map<String, List<String>>?)` function with two new functions (one for closing with data, and one for closing with trailers).
This removes the ambiguity of how a stream will be closed by making the consumer specify explicitly whether they'd like to close a stream using trailers or data.
The change is being done as a precursor for integrating L7 Swift/Kotlin filters, which will have interfaces in which trailers are not nullable.
=> platform: close streams explicitly with data or trailers

library/kotlin/src/io/envoyproxy/envoymobile/BUILD, library/kotlin/src/io/envoyproxy/envoymobile/EnvoyClient.kt, library/kotlin/src/io/envoyproxy/envoymobile/LogLevel.kt
Cleaner/easier to find, as well as maintaining parity with iOS.
=> kotlin: split LogLevel into its own file

library/java/src/io/envoyproxy/envoymobile/engine/EnvoyHTTPStream.java, library/java/src/io/envoyproxy/envoymobile/engine/JniLibrary.java, library/java/src/io/envoyproxy/envoymobile/engine/JvmCallbackContext.java, library/java/src/io/envoyproxy/envoymobile/engine/types/EnvoyHTTPCallbacks.java, library/kotlin/src/io/envoyproxy/envoymobile/EnvoyStreamEmitter.kt, library/kotlin/src/io/envoyproxy/envoymobile/ResponseHandler.kt, library/kotlin/src/io/envoyproxy/envoymobile/StreamEmitter.kt, library/kotlin/test/io/envoyproxy/envoymobile/EnvoyClientTest.kt, library/kotlin/test/io/envoyproxy/envoymobile/GRPCStreamEmitterTest.kt, library/objective-c/EnvoyEngine.h, library/objective-c/EnvoyHTTPStreamImpl.m, library/swift/src/EnvoyStreamEmitter.swift, library/swift/src/StreamEmitter.swift, library/swift/test/GRPCStreamEmitterTests.swift, library/swift/test/MockEnvoyHTTPStream.swift
These are never called in practice today. Since we don't want to support them in the initial version of filters, we're removing them from the public interfaces now.
=> platform: remove sendMetadata/onMetadata

library/swift/test/BUILD, library/swift/test/EnvoyClientBuilderTests.swift, library/swift/test/EnvoyClientTests.swift, library/swift/test/MockEnvoyEngine.swift
We don't need to replicate this type in multiple places.
=> ios: centralize MockEnvoyEngine

examples/java/hello_world/MainActivity.java, examples/kotlin/hello_world/MainActivity.kt, examples/objective-c/hello_world/ViewController.m, examples/swift/hello_world/ViewController.swift, library/kotlin/src/io/envoyproxy/envoymobile/EnvoyClient.kt, library/kotlin/src/io/envoyproxy/envoymobile/GRPCClient.kt, library/kotlin/src/io/envoyproxy/envoymobile/HTTPClient.kt, library/kotlin/test/io/envoyproxy/envoymobile/EnvoyClientTest.kt, library/swift/src/EnvoyClient.swift, library/swift/src/GRPCClient.swift, library/swift/src/HTTPClient.swift, library/swift/test/EnvoyClientTests.swift
Currently, our platform-level unary interfaces have the following limitations:
- It's not very clear when sending a request if it's going to be unary or streamed
- It's not possible to send headers-only requests
- Trailers are non-optional
This PR introduces the following changes to improve these interfaces:
- `send(...)` is used for unary requests, and `start(...)` is used for streaming
- `send(...)` provides the ability to send headers-only requests
- Callers can specify whether they'd like to close with body data or trailers by explicitly passing one as `nil` (see inline documentation)
Additionally, this PR introduces a new set of `EnvoyClient` tests which are 1:1 on iOS and Android.
This change is being made as a precursor to L7 Swift/Kotlin filters.
Signed-off-by: Michael Rebello …
=> platform: update interfaces for unary/streamed requests

ci/kotlin_lint.sh
- Update the script to download to a temp directory instead of the project root
- This makes it easier to run locally since users won't end up with a git diff
- Add some logs to the script to make it easier to identify issues in CI logs
New output:
```
mrebello-mbp151:envoy-mobile-2 mrebello$ ./ci/kotlin_lint.sh
Downloading detekt...
detekt-cli-1.8.0-all.jar                            100%[===================================================================================================================>]  46.86M  5.23MB/s    in 12s
Running linter...
Done
```
=> kotlin: improve linter script

dist/sonatype_nexus_upload.py
Using 500 since sonatype fails more than 20 times in a given attempt.
Description: update sonatype retries to be 500
Testing: n/a
=> [sonatype] update max retries to be 500

library/common/config_template.cc
Description: while investigating retry scenarios I noticed that some retries were not getting performed due to overflow. This PR actually increases the concurrency limit. More information can be found in the PR comments.
Risk Level: med - this change actually allows higher retry concurrency.
Testing: local testing
=> config: fix max concurrent retries circuit breaker

library/swift/src/RetryPolicy.swift, library/swift/src/RetryPolicyMapper.swift, library/swift/test/RetryPolicyMapperTests.swift
Adding support for setting the `x-envoy-retriable-status-codes` header to allow consumers to specify the retriable status codes that are not supported by `RetryRule` out of the box.
From the [docs](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#config-http-filters-router-x-envoy-retriable-status-codes):
> Setting this header informs Envoy about what status codes should be considered retriable when used in conjunction with the retriable-status-code retry policy. When the corresponding retry policy is set, the list of retriable status codes will be considered retriable in addition to the status codes enabled for retry through other retry policies.
Mirrors Android: https://github.com/lyft/envoy-mobile/pull/820
Signed-off-by: Michael Rebello …
=> swift: add x-envoy-retriable-status-codes support

library/kotlin/src/io/envoyproxy/envoymobile/RetryPolicy.kt, library/kotlin/src/io/envoyproxy/envoymobile/RetryPolicyMapper.kt, library/kotlin/test/io/envoyproxy/envoymobile/RequestBuilderTest.kt, library/kotlin/test/io/envoyproxy/envoymobile/RequestTest.kt, library/kotlin/test/io/envoyproxy/envoymobile/RetryPolicyMapperTest.kt
Adding `x-envoy-retriable-status-codes` header to allow consumers to specify the retriable status codes
Description: [kotlin] add x-envoy-retriable-status-codes header
Testing: unit
=> [kotlin] add x-envoy-retriable-status-codes header

examples/kotlin/shared/ResponseViewHolder.kt, examples/kotlin/shared/res/values/colors.xml
Making sure we set the colors on success and failures since the views are recycled (and might present the wrong color)
Description: ensure we set successful colors to white
Testing: n/a
=> [jvm demos] ensure we set successful colors to white

examples/java/hello_world/MainActivity.java, examples/kotlin/hello_world/MainActivity.kt, examples/objective-c/hello_world/ViewController.m, examples/swift/hello_world/ViewController.swift, library/common/http/dispatcher.cc, library/common/http/dispatcher.h, library/common/jni_interface.cc, library/common/types/c_types.h, library/java/src/io/envoyproxy/envoymobile/engine/JvmCallbackContext.java, library/java/src/io/envoyproxy/envoymobile/engine/types/EnvoyHTTPCallbacks.java, library/kotlin/src/io/envoyproxy/envoymobile/EnvoyError.kt, library/kotlin/src/io/envoyproxy/envoymobile/GRPCResponseHandler.kt, library/kotlin/src/io/envoyproxy/envoymobile/ResponseHandler.kt, library/objective-c/EnvoyEngine.h, library/objective-c/EnvoyHTTPStreamImpl.m, library/swift/src/EnvoyError.swift, library/swift/src/GRPCResponseHandler.swift, library/swift/src/ResponseHandler.swift, library/swift/test/GRPCResponseHandlerTests.swift, test/common/http/dispatcher_test.cc
Description: this PR updates the error objects in the library to contain an attempt count. Additionally it wires up the attempt count as reported via envoy headers to the error object used by the Http::Dispatcher.
Risk Level: low - no breaking API changes.
Testing: unit tests, plus local end-to-end tests.
Docs Changes: updated the types docstrings
=> error handling: add attempt counts to the library's error types

library/common/http/dispatcher.h
We've started seeing `SIGABRT` crashes in this file coming from `readDisable()`.
The `NOT_IMPLEMENTED_GCOVR_EXCL_LINE` tag was added a nice-to-have in https://github.com/lyft/envoy-mobile/commit/7ea53ab2f0a6263694cad21a0da6b872e1d6cae0, but is now causing problems because `readDisable` is being called.
I'm removing this for now, and filed https://github.com/lyft/envoy-mobile/issues/825 to properly implement this function.
Crash:
```
SIGABRT
[critical][assert] [./library/common/http/dispatcher.h:150] panic: not implemented
```
=> dispatcher: fix crashes from NOT_IMPLEMENTED_GCOVR_EXCL_LINE

.bazelrc
This reverts commit 6d91bf555b02942c5c740bc9a7594604ff3b11fc.
This broke local debugging
=> Revert "build: Enable opt for Swift compiles (#816)"

library/common/config_template.cc
Description: updates the envoy ref. Brings in the ability to report counters as deltas in the metrics service stats sink https://github.com/envoyproxy/envoy/pull/10889.
=> envoy upstream: update ref and report counters as deltas

library/kotlin/src/io/envoyproxy/envoymobile/EnvoyError.kt
Description: [kotlin] make constructor public visibility for EnvoyError
Testing: n/a
=> [kotlin] make constructor public visibility for EnvoyError

library/common/BUILD, library/common/engine.cc, library/common/engine.h, library/common/envoy_mobile_main_common.cc, library/common/envoy_mobile_main_common.h, test/common/BUILD, test/common/envoy_mobile_main_common_test.cc
Description:  Disabling signal handling in the Server::Options makes it so that the server's event dispatcher [_does not_ listen for termination signals](https://github.com/envoyproxy/envoy/blob/048f4231310fbbead0cbe03d43ffb4307fff0517/source/server/server.cc#L519) such as SIGTERM, SIGINT, etc. Previous crashes in iOS were experienced due to out-of-band event loop exit as described in #831. Ignoring termination signals makes it more likely that the event loop will only exit due to [Engine destruction](https://github.com/lyft/envoy-mobile/blob/a72a51e64543882ea05fba3c76178b5784d39cdc/library/common/engine.cc#L105).
This PR introduces `Envoy::MobileMainCommon`, as this is the canonical way to customize how main runs, and options setup per https://github.com/envoyproxy/envoy/pull/3424. The …
=> main: use custom main common to disable listening for termination signals

.bazelrc
Previously we could not do this because the archive ended up being too
large with debug info. I've added an option to disable this here https://github.com/envoyproxy/envoy/pull/10987
=> bazel: build releases with opt

WORKSPACE, ci/mac_start_emulator.sh
Description: brings in an envoy update. Relevant commits:
- https://github.com/envoyproxy/envoy/pull/11127 which uses the construct on first use idiom for certain static variables in the histogram code which were causing #688.
Testing: fixed local repro of the crash.
Fixes #688 
=> update envoy 05102020

ci/mac_start_emulator.sh, docs/root/start/building/building.rst
Description: actions infra is failing to start android 28. However, android 29 works fine. This PR updates CI to start the android emulator with android 29.
Testing: local and CI
Docs Changes: updated the docs to SDK version 29 for requirements
Fixes #841 
=> android: update version to 29

.github/workflows/release.yml
Description: the current time limit was exceeded in the last release I cut: https://github.com/lyft/envoy-mobile/runs/668659114
=> release: increase android release ci time limit

library/swift/src/FilterDataStatus.swift
This is currently being used for `Data` but is currently being polluted
by the Objective-C bridging header.
=> Add missing Foundation import

WORKSPACE, ci/linux_ci_setup.sh, library/common/config_template.cc, library/common/extensions/BUILD, library/common/extensions/registry.cc, library/common/extensions/registry.h
Description: this PR pulls in the new decompressor filter in Envoy and configures response decompression in Envoy Mobile for gzip encoding.
Risk Level: med - new filter in envoy, not tested in production environments.
Testing: local build of the Lyft app. 
=> compression: add response decompression

library/common/BUILD
In this commit https://github.com/lyft/envoy-mobile/pull/830 I removed
the `-s` linkopt because 1) I didn't realize it did anything since for
ld64 on macOS it does not and 2) I expected `-g0` in envoy to be enough
to remove all debug info.
It turns out that when linking this dynamic framework having `-g0` on
all the compiles is not enough, this restores `-s` just for the
`cc_binary`'s `linkopts`:
```
-s, --strip-all
Strip all symbols
```
Theoretically we might eventually want just `-S`:
```
-S, --strip-debug
Strip debugging information
```
To improve crash log quality, but for now this restores the previous
behavior.
Reference: https://manpages.ubuntu.com/manpages/trusty/man1/ld.gold.1.html
=> android: Add missing `-s` linkopt

.github/workflows/coverage.yml
I'm temporarily disabling coverage for now since it's blocking PRs. It'll be fixed/re-enabled in https://github.com/lyft/envoy-mobile/issues/863.
I spent a few minutes looking into fixing the breakage from https://github.com/envoyproxy/envoy/pull/10909, but it looks like the fix won't be trivial since we [rely on](https://github.com/lyft/envoy-mobile/blob/f50aaa57033decf68d2e961f7716ecb9a5f42402/test/coverage/run_coverage.sh#L6-L8) `EXTRA_QUERY_PATHS` and `ONLY_EXTRA_QUERY_PATHS` (the latter of which was [added upstream](https://github.com/envoyproxy/envoy/commit/9931239df99abda9ec69d450177730826d985c25) by @junr03 recently), and the file that used those was deleted in the above PR.
=> ci: temporarily disable coverage

bazel/swift_static_framework.bzl, bazel/swift_test.bzl, library/objective-c/BUILD, library/swift/src/BUILD, library/swift/src/EnvoyClient.swift, library/swift/src/EnvoyClientBuilder.swift, library/swift/src/EnvoyStreamEmitter.swift, library/swift/src/ResponseHandler.swift, library/swift/test/BUILD, library/swift/test/EnvoyClientBuilderTests.swift, library/swift/test/GRPCResponseHandlerTests.swift, library/swift/test/MockEnvoyEngine.swift, library/swift/test/MockEnvoyHTTPStream.swift
This is an in between to https://github.com/lyft/envoy-mobile/pull/797
which starts building the archive with swiftinterface files, but does
it with our existing swift_static_framework rule because of issues
linked on that PR.
=> bazel: Update swift_static_framework to use swiftinterfaces

library/swift/src/Headers.swift, library/swift/src/HeadersBuilder.swift, library/swift/src/RequestTrailersBuilder.swift, library/swift/src/ResponseHeadersBuilder.swift, library/swift/src/ResponseTrailersBuilder.swift, library/swift/src/grpc/GRPCStream.swift, library/swift/test/ResponseHeadersTests.swift
- Add public initializers for remaining headers/trailers builders. These are being done on each subclass rather than once in the superclass in order to allow subclasses (like `GRPCRequestHeaders`) to require certain values on initialization
- Add missing `super.init()` calls for `NSObject` subclasses
- Add a function for setting the HTTP status code on response headers, as setting `:status` publicly is restricted
=> swift: add builder initializers

library/kotlin/src/io/envoyproxy/envoymobile/Headers.kt, library/swift/src/Headers.swift
After some discussions, we decided to expose the underlying map of headers as a convenience accessor for public consumption in order to enable iterating over the key-value pairs from other consumers.
=> swift/kotlin: add `Headers.allHeaders()`

library/swift/src/RequestHeaders.swift, library/swift/src/ResponseHeaders.swift
Android's implementation lazily computes these properties, then stores them so that they are not recalculated each time they're accessed. Conversely, iOS recomputes them each time.
This PR updates iOS to mirror Android's behavior since we actually don't need to recompute these each time since `Headers` types are immutable (modifications are done via builders).
=> swift: lazily compute {Request/Response}Headers properties

library/kotlin/src/io/envoyproxy/envoymobile/ResponseHeadersBuilder.kt, library/kotlin/test/io/envoyproxy/envoymobile/BUILD, library/kotlin/test/io/envoyproxy/envoymobile/ResponseHeadersTest.kt, library/swift/src/ResponseHeadersBuilder.swift, library/swift/test/ResponseHeadersTests.swift
This was added for swift in https://github.com/lyft/envoy-mobile/pull/893 but I failed to add it on Android as well.
Also adds some tests to mirror iOS' tests for response headers.
=> kotlin: add `ResponseHeadersBuilder.addHttpStatus()`

BUILD, bazel/envoy_mobile_repositories.bzl
Patches need to be referenced using the workspace alias
Description: bazel: fixup patches 
Testing: ci
=> bazel: fixup patches

library/common/config_template.cc
Description: add individual stats for some 4xx codes of interest at Lyft. In the future, like other stats we can have this be configurable.
Testing: local
=> stats: add stats for specific 4xx codes

library/common/jni_interface.cc
Description: wire up missing on cancel call from JNI up to platform layer
Testing: build
=> android: wire up on cancel from JNI layer

bazel/aar_with_jni.bzl
The release task is relying on the output artifact to be of this format
Description: bazel: Fix sonatype uploads
Risk Level: none
Testing: local
=> bazel: Fix sonatype uploads

library/swift/src/HeadersBuilder.swift, library/swift/src/RequestTrailersBuilder.swift, library/swift/src/ResponseHeadersBuilder.swift, library/swift/src/ResponseTrailersBuilder.swift
With Swift < 5.2 there's an issue where if you implicitly inheret
initializer from `NSObject` the generated swiftinterface doesn't include
the `override` keyword for subclasses and fails when trying to import
the framework. This makes that explicit which adds the keyword. Once we
upgrade to build with Swift 5.2 we can revert this.
=> Swift: Workaround Swift 5.1 swiftinterface bug

WORKSPACE
Fixing android's api to 29 since it seems like api 30 has some bazel proguard issues which are similar to: bazelbuild/bazel#3777
Description: android: fixate api_level to be 29
Testing: ci
=> android: fixate api_level to be 29

.github/workflows/android.yml
=> ci: increase android linux build timeout to 90m

library/swift/src/mocks/MockStreamClient.swift
Without this we see this crash:
```
Fatal error: Use of unimplemented initializer 'init()' for class 'Envoy.MockStreamClient'
```
=> swift: Add another explicit init for Swift 5.2

.github/workflows/core.yml
Jobs have been timing out for the `asan` job at 60m.
=> ci: bump core timeouts

library/swift/src/grpc/GRPCStream.swift
Fixes the following warnings when compiling with Xcode 11.5:
```
INFO: From Compiling Swift module Envoy:
library/swift/src/grpc/GRPCStream.swift:56:23: warning: initialization of 'UnsafeBufferPointer<UInt32>' results in a dangling buffer pointer
prefixData.append(UnsafeBufferPointer(start: &length, count: 1))
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
library/swift/src/grpc/GRPCStream.swift:56:50: note: implicit argument conversion from 'UInt32' to 'UnsafePointer<UInt32>?' produces a pointer valid only for the duration of the call to 'init(start:count:)'
prefixData.append(UnsafeBufferPointer(start: &length, count: 1))
^~~~~~~
library/swift/src/grpc/GRPCStream.swift:56:50: note: use 'withUnsafePointer' in order to explicitly convert argument to pointer valid for a defined scope …
```
=> swift: fix Xcode 11.5 warnings

docs/root/api/grpc.rst, docs/root/api/http.rst, docs/root/api/starting_envoy.rst
This PR updates the docs to reflect all the recent Swift/Kotlin interface changes. It also adds "quick start" sections to the HTTP and gRPC pages.
Resolves https://github.com/lyft/envoy-mobile/issues/906.
=> docs: update docs for swift/kotlin interfaces

examples/java/hello_world/MainActivity.java, examples/kotlin/hello_world/MainActivity.kt
Create a new thread for response handlers. The previous implementation uses whatever thread that envoy used for executing responses.
Description: android: use new thread for responses handlers
Testing: ci
=> android: use new thread for responses handlers

bazel/aar_with_jni.bzl
=> build: fix for generating javadocs courtesy of @buildbreaker

.github/workflows/android.yml, .github/workflows/ios.yml, examples/java/hello_world/MainActivity.java, examples/kotlin/hello_world/MainActivity.kt, examples/objective-c/hello_world/Result.h, examples/objective-c/hello_world/ViewController.m, examples/swift/hello_world/ResponseModels.swift, examples/swift/hello_world/ViewController.swift
We've seen some flakiness on the iOS liveliness CI jobs which appear to be caused by the fact that the first response log from the hello world projects is not showing up when the script greps for `Response status (1): 200`. This PR aims to:
- Fix these flakes by grepping for any 200 response in the logs (rather than specifically the first one)
- Unify the logging and CI behavior for all 4 languages
- Fix error messages not being displayed in the Objective-C hello world app
=> ci: fix liveliness flakiness

library/common/config_template.cc
Description: allow the decompressor to be flexible in decompressing all possible compressed gzip streams. The decompressor setting should be at least as big as the compressed stream. Optimally Envoy would allow us to set the value to 0, which would then derive the actual window bits value from the zlib header in the compressed stream.
Testing: local + CI
=> compression: change decompressor window bits

WORKSPACE, bazel/envoy_mobile_repositories.bzl, examples/java/hello_world/MainActivity.java
We're reverting the libevent version bump from upstream envoy to avoid the commit which introduced a usage of `pthread_mutexattr_setprotocol`. The libevent change is [here](https://github.com/libevent/libevent/commit/f76456b0dc14fb7c5fa55f815512b2ed07df4706). The upstream envoy change was primarily targeted for windows.
Upstream change for updating libevent: https://github.com/envoyproxy/envoy/pull/11137
Addressing missing symbol: https://github.com/lyft/envoy-mobile/issues/934
Will need to lower to 21: https://github.com/lyft/envoy-mobile/issues/936
Description: android: fixate …
=> android: fixate to API 24 and use old libevent version for upstream envoy

library/swift/src/HeadersBuilder.swift, library/swift/src/RequestTrailersBuilder.swift, library/swift/src/ResponseHeadersBuilder.swift, library/swift/src/ResponseTrailersBuilder.swift, library/swift/src/mocks/MockStreamClient.swift
This reverts 139f037e2599438ae3bf3faa62ed03d7f8594c7f and 1b36d5a2c31c5b55c4d64bc3a933969cbab6ec06
These are no longer required since we now build with Swift 5.2
=> Revert "Swift: Workaround Swift 5.1 swiftinterface bug (#914)"

CONTRIBUTING.md
This is snapshotted from upstream Envoy.
=> docs: update CONTRIBUTING.md with inclusive language policy

.github/workflows/android.yml, .github/workflows/artifacts.yml, .github/workflows/release.yml, BUILD, bazel/android_artifacts.bzl, library/kotlin/src/io/envoyproxy/envoymobile/BUILD
Description: android: only build aar for android_dist target
Testing: ci
=> android: only build aar for android_dist target

ci/test_size_regression.sh
Description: Increases the soft limit for binary size to 5.6MB due to upstream Envoy update. Size prior to update was 5298092 (5.3MB).
=> ci: increase soft binary size limit

envoy_build_config/BUILD, envoy_build_config/extension_registry.cc, envoy_build_config/extension_registry.h, envoy_build_config/extensions_build_config.bzl, library/common/BUILD, library/common/envoy_mobile_main_common.cc, library/common/http/dispatcher.h, library/common/http/header_utility.cc, test/common/http/dispatcher_test.cc, test/common/http/header_utility_test.cc, test/integration/dispatcher_integration_test.cc
Description: Pulls in multiple fixes committed to upstream Envoy.
- Update for resolution to TLSContext crash: https://github.com/envoyproxy/envoy/issues/10030
- Fixes for 32 bit archs: https://github.com/envoyproxy/envoy/pull/11726
- Fix for missing posix call on Android: https://github.com/envoyproxy/envoy/pull/12081
- Additional zlib stats: https://github.com/envoyproxy/envoy/pull/11782
=> envoy: update upstream for multiple fixes

WORKSPACE
We can do this now that https://github.com/envoyproxy/envoy/pull/11863 has landed and upstream has been bumped.
Resolves https://github.com/lyft/envoy-mobile/issues/936.
=> android: switch API level to 21

docs/publish.sh
Reverts some of the changes from https://github.com/lyft/envoy-mobile/commit/1d39e036650d384426527a51d3fd3e074e9afd40 in order to fix our docs publishing job. After some investigating, it appears that setting the default branch for a GitHub pages site to a non-`master` branch (like `main`) does not properly load, and results in 404s.
=> ci: fix docs publishing job

docs/root/start/building/building.rst
Description: android: docs update NDK to be 21 rather than 19
Testing: n/a
Docs Changes: buidling docs for android
=> android: docs update NDK to be 21 rather than 19

.github/workflows/android.yml, .github/workflows/artifacts.yml, .github/workflows/core.yml, .github/workflows/format.yml, .github/workflows/ios.yml, .github/workflows/perf.yml, .github/workflows/release.yml
We should be using bazelisk on CI since that's what we advise doing locally.
=> ci: use bazelisk

library/common/extensions/filters/http/platform_bridge/c_types.cc, library/common/extensions/filters/http/platform_bridge/c_types.h, library/common/extensions/filters/http/platform_bridge/filter.cc, library/common/extensions/filters/http/platform_bridge/filter.h
Description: Add initial support for HTTP body data chunks to be bridged to platform filter invocations.
Testing: Local
=> filters: add bridge support for data invocations

STYLE.md, library/common/types/c_types.cc, library/common/types/c_types.h, library/java/src/io/envoyproxy/envoymobile/engine/EnvoyEngineImpl.java, library/objective-c/EnvoyEngine.h, library/objective-c/EnvoyEngineImpl.m, library/swift/src/mocks/MockEnvoyEngine.swift
Description: Introduces extern consts to enforce agreement between return codes produced by the engine. Note the JNI is currently an exception, but could be runtime enforced with an additional one-time validation step.
Risk: Low
Testing: Local
=> tech debt: enforce agreement of engine return codes

BUILD
We previously outputted `dist/envoy_local.aar` for `bazelisk build android_dist`. This change it is to appropriately name the output to `dist/envoy.aar`
Description: bazel: android aar bazel rule fix to output envoy.aar
Testing: local
=> bazel: android aar bazel rule fix to output envoy.aar

examples/swift/hello_world/DemoFilter.swift, examples/swift/hello_world/ViewController.swift, library/common/extensions/filters/http/platform_bridge/BUILD, library/common/extensions/filters/http/platform_bridge/c_types.h, library/common/extensions/filters/http/platform_bridge/filter.cc, library/common/extensions/filters/http/platform_bridge/filter.h, library/objective-c/BUILD, library/objective-c/EnvoyConfiguration.m, library/objective-c/EnvoyEngine.h, library/objective-c/EnvoyEngineImpl.m, library/objective-c/EnvoyHTTPFilterFactory.m, library/swift/src/StreamClientBuilder.swift, library/swift/src/filters/Filter.swift
Description: Changes filter instantiation to be a per-stream basis, across the core, bridge, and iOS platform layers. Also improves usage of CFBridge* functions to be better in line with their intent.
Testing: Local end-to-end
=> filters: instantiate filters on a per-stream basis

library/common/extensions/filters/http/platform_bridge/c_types.cc, library/common/extensions/filters/http/platform_bridge/c_types.h, library/common/extensions/filters/http/platform_bridge/filter.cc, library/common/extensions/filters/http/platform_bridge/filter.h
Description: Adds remaining wiring in the PlatformBridgeFilter necessary for trailers invocations.
Risk: Moderate
Testing: Local
=> filters: wire trailers at core layer

library/swift/src/HeadersBuilder.swift, library/swift/src/RequestTrailersBuilder.swift, library/swift/src/ResponseHeadersBuilder.swift, library/swift/src/ResponseTrailersBuilder.swift, library/swift/src/mocks/MockStreamClient.swift
With envoy-mobile built from Xcode 11.5, we are unable to consume it
with Xcode 12.0 beta 3. I'm hoping this fixes it, the errors appear
related:
```
deps/cache/dependencies/Envoy/current/Envoy.framework/Modules/Envoy.swiftmodule/x86_64.swiftinterface:137:28: error: overriding declaration requires an 'override' keyword
@objc convenience public init()
^
override
deps/cache/dependencies/Envoy/current/Envoy.framework/Modules/Envoy.swiftmodule/x86_64.swiftinterface:38:33: note: overridden declaration is here
@objc override dynamic public init()
^
Modules/EnvoyFilters/Sources/EnvoyFilterManager.swift:1:8: error: failed to build module 'Envoy' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', may have used features …
```
=> Swift: Workaround Swift 5.2 + 5.3 swiftinterface bug

library/common/BUILD, library/common/jni/BUILD, library/common/jni/jni_interface.cc, library/kotlin/src/io/envoyproxy/envoymobile/BUILD
Description: Move JNI to dedicated directory ahead of Android filter PRs.
=> jni: move to dedicated path

.bazelrc
This has a few small changes
1. Always apply `--incompatible_objc_compile_info_migration` so that
when you switch between configurations this doesn't force bazel to
reanalyze all targets
2. Use consistent `--define` `=` syntax
=> build: Update .bazelrc

BUILD, bazel/android_artifacts.bzl, dist/sonatype_nexus_upload.py, docs/root/start/building/building.rst
Cleaning up the sonatype upload script to enable easier local deployment. The change here is just to remove some required fields in the local publish case.
Description: android: clean up sonatype upload to support local deploy 
Testing: local
=> android: clean up sonatype upload to support local deploy

examples/swift/hello_world/ViewController.swift, library/swift/src/StreamClientBuilder.swift, library/swift/src/filters/Filter.swift
Updates the stream client builder to accept a closure returning a `Filter` rather than requiring `Filter` to have an `init()` in its protocol conformance. This allows consumers to provide more flexible implementations of "factories" (closures) that can be used with custom initializers or alongside additional logic.
Note: Generics are required here since `Filter.name` is needed.
As part of this change, I also fixed some outdated documentation of this function.
Testing: Local/CI
Docs Changes: No
=> swift: update stream client to use factory closures for filters

library/kotlin/src/io/envoyproxy/envoymobile/filters/RequestFilterCallbacks.kt, library/kotlin/src/io/envoyproxy/envoymobile/filters/ResponseFilterCallbacks.kt, library/swift/src/filters/RequestFilterCallbacks.swift, library/swift/src/filters/ResponseFilterCallbacks.swift
At the moment, `continueRequest()` and `continueResponse()` are not yet wired up. While we plan to implement that in the very near future (next week or so), we do not have plans to add these other "async" operations at the moment. Removing them from the public interface until we're ready to implement them.
=> platform: remove some interfaces

library/swift/src/filters/FilterDataStatus.swift, library/swift/src/filters/FilterHeaderStatus.swift, library/swift/src/filters/FilterTrailerStatus.swift
This suppresses the following warning when `switch`ing over filter return values:
> Switch covers known cases, but 'FilterHeaderStatus<RequestHeaders>' may have additional unknown values
Note that while we are not guaranteeing ABI stability, we will use semantic versioning going forward.
=> swift: add `@frozen` annotation to filter statuses

library/swift/src/filters/FilterDataStatus.swift, library/swift/src/filters/FilterHeaderStatus.swift, library/swift/src/filters/FilterTrailerStatus.swift
This will allow for easier testing/validation of filters for consumers.
=> swift: make filter statuses equatable

library/common/config_template.cc
Description: The previous list of stats would result in redundant checks and larger state machines. This change slims things down.
=> stats: clean up default inclusion list

.github/workflows/ios.yml
Description: This job seems to get cancelled frequently at the 45-minute mark, which just means another 45-minute cycle to run it again. Increase to 60 to hopefully get it to complete consistently.
=> ci: increase ios/mac_dist timeout

examples/swift/hello_world/DemoFilter.swift, examples/swift/hello_world/ViewController.swift, library/swift/src/StreamClientBuilder.swift, library/swift/src/filters/Filter.swift
Description: This avoids generics and some additional complexity on the Kotlin side. Ultimately, we may move to a solution that removes the need to specify a name entirely.
=> filters: update iOS interface to take explicit filter name

examples/swift/hello_world/DemoFilter.swift, library/swift/src/filters/ResponseFilter.swift
These are specified in the Kotlin interface, but not in Swift. They'll be wired up separately.
=> swift: add some missing ResponseFilter functions

library/common/jni/jni_interface.cc, library/common/types/c_types.h, library/java/src/io/envoyproxy/envoymobile/engine/BUILD, library/java/src/io/envoyproxy/envoymobile/engine/JvmBridgeUtility.java, library/java/src/io/envoyproxy/envoymobile/engine/JvmCallbackContext.java, library/objective-c/EnvoyHTTPStreamImpl.m, test/common/http/dispatcher_test.cc, test/integration/dispatcher_integration_test.cc
Description: Rework callback signatures by allowing a type-erased return context similar to the context parameter that gets included in the call argument. This opens the door to filter callbacks and stream callbacks sharing streamlined bridge code, especially in the case of the JNI. Also improves upon the current header passing mechanism for the JNI.
=> filters: rework callbacks for shared signatures

examples/swift/hello_world/ViewController.swift, library/kotlin/src/io/envoyproxy/envoymobile/StreamClientBuilder.kt, library/swift/src/StreamClientBuilder.swift, library/swift/test/StreamClientBuilderTests.swift
Since we essentially just want to enforce that each filter has a unique name in the registry, we can move this burden into the library and avoid making consumers specify filter names directly.
=> platform: automatically assign filter names

library/common/engine.h, library/common/http/dispatcher.cc
Description: Due to inverse destruction order, it was previously theoretically possible that the main thread could still be running and executing the event loop when the Http::Dispatcher had already been destroyed. This ensures that the normal destruction order of the Engine should ensure the main thread has been destructed (and terminated) before the dispatcher. Our presumption that the crash is called by `this` being null in the callback is covered by a new `RELEASE_ASSERT`, so that we can detect if further protection (e.g. capturing the dispatcher via a shared pointer in the callback) is needed.
Testing: CI
Co-authored-by: Jose Nino <jnino@lyft.com>
=> crash fix: ensure main thread is destructed before Http::Dispatcher

library/objective-c/EnvoyEngine.h
Description: We ended up not using this, and don't have a use for it at present.
=> cleanup: delete unused type

library/common/config_template.cc
Envoy Mobile currently does not handle IPV6 connections, and they fail with local 503s. This PR forces IPV4 for now until we add support in https://github.com/lyft/envoy-mobile/issues/1022.
=> dynamic forward proxy: restrict to ipv4

examples/kotlin/hello_world/BUILD, examples/kotlin/hello_world/DemoFilter.kt, examples/kotlin/hello_world/MainActivity.kt, library/common/jni/jni_interface.cc, library/java/src/io/envoyproxy/envoymobile/engine/BUILD, library/java/src/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java, library/java/src/io/envoyproxy/envoymobile/engine/EnvoyEngineImpl.java, library/java/src/io/envoyproxy/envoymobile/engine/JniLibrary.java, library/java/src/io/envoyproxy/envoymobile/engine/JvmCallbackContext.java, library/java/src/io/envoyproxy/envoymobile/engine/JvmFilterContext.java, library/java/src/io/envoyproxy/envoymobile/engine/JvmFilterFactoryContext.java, library/java/test/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt, library/kotlin/src/io/envoyproxy/envoymobile/EngineBuilder.kt, library/proguard.txt
Description: Adds invocation path for Android platform-bridged filters, covering request/response headers, data, and trailers. This change does not provide for state modification via the return path.
=> filters: wire Android invocation path

library/java/src/io/envoyproxy/envoymobile/engine/JvmCallbackContext.java, library/java/src/io/envoyproxy/envoymobile/engine/JvmFilterContext.java
Description: Fixes incorrect signatures for the JNI calls on the trailers callback path in Android.
Testing: Needs to be covered by AssertionFilter integration tests
=> filters: fix trailers callback signatures

library/common/http/dispatcher.cc, library/common/http/dispatcher.h
Description: introduces temporary state to figure out where the garbage pointer in #1016 is.
Risk Level: low, removing imminently.
=> crashes: get more granularity on potential crash

library/common/engine.cc, library/common/engine.h
Description: Use a dedicated Stats::Scope for external stats.
Testing: Local
=> stats: add scope for external stats

library/common/http/BUILD, library/common/http/dispatcher.cc, library/common/http/dispatcher.h, test/common/http/dispatcher_test.cc
Description: this PR creates a `DirectStreamWrapper` class. This class is used to `deferredDelete` the ref count of the `DirectStream` owned by `streams_` while still maintaining a container of `DirectStreamSharedPtr`. Using `deferredDelete` is important due to the necessary ordering of `ActiveStream` deletion w.r.t `DirectStream` deletion; the former needs to be destroyed first. Using post to defer delete the `DirectStream` provides no ordering guarantee per envoy/source/common/event/libevent.h. Maintaining a container of `DirectStreamSharedPtr` is important because `Dispatcher::resetStream` is initiated by a platform thread.
Risk Level: high - changes deletion scheme of DirectStreams
Testing: updated unit tests, passing integration tests which exercise races around stream deletion …
=> direct stream: use wrapper to schedule defer deletion

library/common/jni/BUILD, library/common/jni/android_jni_interface.cc, library/common/jni/jni_interface.cc
Description: Split interfaces to allow for creation of a non-Android build target.
=> jni: separate Android and base JNI interfaces

library/common/http/dispatcher.cc, library/common/http/dispatcher.h
Description: given we have gotten no additional information from the code deleted in this PR, I am deleting to make readability better. This code was previously added to help investigate #1016 and #1017.
Testing: no-op in terms of functionality.
=> dispatcher: clean up investigation code

library/common/jni/jni_utility.cc
Description: Previously, get_env would make unnecessary JNI calls every time it was called, making it relatively expensive, and encouraging passing the pointer around everywhere. This makes it faster in the normal case by skipping JNI calls except for the first time a thread uses it.
=> jni: make get_env skip JNI calls for the normal case

library/swift/src/StatsClientImpl.swift, library/swift/src/stats/Counter.swift, library/swift/src/stats/CounterImpl.swift, library/swift/test/BUILD, library/swift/test/CounterTests.swift
Description: Make `StatsClient` protocol's interface return `Counter` protocol (as opposed to `Counter` class) to make mocking of the `StatsClient` easier.
Use case: in our Lyft application we need a way to mock `StatsClient` (protocol). An instance of the object conforming to this protocol can be created with the use of Envoy engine. In unit tests, we do not want to use Envoy engine and hence we need a way to create a custom object conforming to `StatsClient` protocol.
To implement a `StatsClient` protocol one needs to implements `func counter(_ elements: [Element]) -> Counter` method. In order to implement this method a developer needs to be able to initialize a new instance of `Counter`, it's currently not possible to do from outside of the module in which `Counter` is defined because: …
=> Introduce Counter protocol

docs/root/api/api.rst, docs/root/api/starting_envoy.rst, docs/root/api/stats.rst
Updates the [Start Envoy](https://github.com/lyft/envoy-mobile/blob/main/docs/root/api/starting_envoy.rst) section and adds doc for `Stats` to reflect the api changes introduced by https://github.com/lyft/envoy-mobile/commit/b9a4334916159eebe68a544690a1eb9e4023dbc4
Signed-off-by: Jingwei Hao <jingweih@lyft.com>
=> docs: update doc to reflect recent api changes

library/common/jni/jni_interface.cc
In the case when the JVM calls a native method, the native method will automatically handle local references within the method upon a the method's return.
However, in the case where the native method calls a JVM method, local references created will not be deleted after the method returns. In some of these cases, we have forgotten to clean up some of these local references prior to returning.
While we previously did not do this clean up for `on_error` and `on_cancel` and since these were rarer events, we did not observe any issues. However, with the introduction of platform based filters, we also did not clean this up for the filter initialization which does occur more often and we ran into issues.
For an explanation of how to fill out the fields, …
=> jni: fix unreleased local refs

library/common/engine.cc
Description: scope destruction should happen ahead of destroying main_common_. Additionally while cross thread destruction is acceptable, this PR also moves destruction to happen in the context of the main thread.
Risk Level: med - resolve crash
Testing: repro in alpha builds of the lyft app.
=> stats: ensure client_scope_ destruction occurs ahead of main_common_ destruction

docs/root/api/starting_envoy.rst, docs/root/api/stats.rst, examples/swift/hello_world/ViewController.swift, library/swift/src/Engine.swift, library/swift/src/EngineImpl.swift
- Convert `statsClient`/`streamClient` accessors to functions in Swift as they are in Kotlin
- Update docs with the above changes
- Fix some typos in docs
=> platform: fix inconsistencies between swift/kotlin

library/common/http/dispatcher.cc, library/common/http/dispatcher.h, test/common/http/dispatcher_test.cc
=> dispatcher: rename onReset to onError for consistency with callbacks

library/common/config_template.cc, library/common/main_interface.cc
Description: The was only needed prior to dynamic registration of platform filters. It's benign, but thoroughly unnecessary now.
Testing: CI
=> cleanup: remove PlatformStub filter

library/swift/src/filters/Filter.swift
These are unused and triggering warnings when building.
=> swift: fix build warnings in platform filter

.github/workflows/ios.yml
Description: Increase timeout since mac_dist is still timing out mid-compile.
=> ci: increase mac_dist timeout to 75 minutes

test/common/extensions/filters/http/platform_bridge/BUILD, test/common/extensions/filters/http/platform_bridge/platform_bridge_filter_test.cc
Description: Adds basic framework for unit coverage of the PlatformBridgeFilter.
=> filters: setup unit test coverage for PlatformBridgeFilter

ci/test_size_regression.sh
The most recent Envoy bump requires this: https://github.com/lyft/envoy-mobile/pull/1076
```
The new binary is 2.00 % different in size compared to main.
The new binary is 5790759 bytes.
The current size (5790759) is larger than the maximum size (5700000).
```
=> ci: increase max size of binary

library/common/extensions/filters/http/assertion/BUILD, library/common/extensions/filters/http/assertion/filter.cc, test/common/extensions/filters/http/assertion/assertion_filter_test.cc
Description: Updates theAssertionFilter to always return ::Continue when validation checks pass. Fixes some bugs when requests should have failed, but wouldn't, or should have passed, but wouldn't:
- Processing would be aborted for truncated requests, but potentially still appear to pass: e.g., a filter set up to validate conditions on headers and body could return 200 for headers-only requests, skipping body validation.
- If data was streamed, but the first chunk didn't pass all data assertions on its own, processing would fail, even if later chunks would have passed validation.
- Testing of conditions before and after another filter wasn't possible.
For integration tests, there's not much downside to the pass-through behavior, since the Router can always be configured to return a 200 …
=> assertion filter: update to be pass-through

library/common/extensions/filters/http/assertion/filter.cc, library/common/extensions/filters/http/assertion/filter.h, test/common/extensions/filters/http/assertion/assertion_filter_test.cc
Description: Adds response assertions to the AssertionFilter, using a 500 status code to distinguish response from request assertion failures.
=> assertion filter: add response assertion support

.github/workflows/ios.yml
Description: Increases the sleep before attempting to cat iOS logs in CI to 5 minutes. We're still occasionally trying too early, resulting in flakiness.
Testing: CI
=> ci: increase delay before checking iOS simulator

.github/workflows/ios.yml
Description: This should reduce the flakiness of the iOS example app CI jobs, and allow them to terminate quicker on success. Notes:
- `touch` log file so that `tail` doesn't terminate early if it starts before output.
- `tail -F` so it notices when the log file is replaced.
- `sed` to also stream all log output to `stdout`.
Testing: CI
=> ci: continuously check iOS example app log output

library/common/jni/jni_interface.cc
Continuation from https://github.com/lyft/envoy-mobile/pull/1057.
Doing an audit of all the JNI methods which call into a java context.
Description: jni: ensure we delete local refs
Risk Level: moderate
Testing: manually
=> jni: ensure we delete local refs

.github/workflows/artifacts.yml
This was renamed a bit back but I suppose we never paid too much attention to this failure 😬 
Description: android: fix binary uploading for artifacts ci job
Testing: n/a
=> android: fix binary uploading for artifacts ci job

envoy_build_config/extensions_build_config.bzl, library/common/http/dispatcher.h
Bumping primarily to include the changes from https://github.com/envoyproxy/envoy/pull/12477 for decompressor trailers reporting.
Contains changes to fix compilation after:
- https://github.com/envoyproxy/envoy/commit/d245c0296690103780c8d4cc7a54b47aeca2972d
- https://github.com/envoyproxy/envoy/commit/52ec66f45fdc814a5e3f96912ebde22f78c7c03a
Also contains new fixes required by Envoy Mobile:
- https://github.com/envoyproxy/envoy/pull/13039
- https://github.com/envoyproxy/envoy/pull/13040
=> upstream: bump envoy submodule ref

library/common/extensions/filters/http/platform_bridge/filter.cc, library/common/extensions/filters/http/platform_bridge/filter.h
Description: these functions are no-ops in the current implementation. They can be not overridden in order to delete uncovered code here.
Testing: no-op
=> platform bridge filter: offload no-ops to pass through filter

library/common/engine.cc, library/common/engine.h, library/common/jni/android_jni_interface.cc, library/common/main_interface.cc, library/common/main_interface.h, library/java/src/io/envoyproxy/envoymobile/engine/AndroidAppLifecycleMonitor.java, library/java/src/io/envoyproxy/envoymobile/engine/AndroidJniLibrary.java
Description: this functionality is not currently being used. Instead of having non-used code in the library (which is also not covered by tests), we should delete and bring back when it is actively being worked on
Risk Level: low - unused functionality
Related to: https://github.com/lyft/envoy-mobile/issues/754
=> stats: remove ability to force flush until required

.bazelrc, ci/mac_ci_setup.sh, docs/root/start/building/building.rst
This change is dependent on https://github.com/envoyproxy/envoy/pull/13140 to fix upstream build failures with Xcode 12.
=> build: update to Xcode 12

library/common/extensions/filters/http/assertion/filter.cc, test/common/extensions/filters/http/assertion/assertion_filter_test.cc
Description: Removes two branches that aren't possible to hit with Envoy's matcher implementation today. Adds two tests that cover an alternate path through body assertion failure.
=> coverage: improve AssertionFilter coverage

library/common/config_template.cc
This filter is configured exclusively with gzip decompression. If we were to add more in the future (i.e., brotli), this would be a good way to differentiate.
This change is especially useful since it'll transform `x-envoy-decompressor-basic-uncompressed-bytes` to use "gzip" instead of "basic" in the trailers it adds to responses.
=> config: rename decompressor name from "basic" to "gzip"

library/common/buffer/utility.cc, library/common/buffer/utility.h, library/common/extensions/filters/http/platform_bridge/filter.cc, library/common/extensions/filters/http/platform_bridge/filter.h, test/common/extensions/filters/http/platform_bridge/platform_bridge_filter_test.cc
Description: Adds internal buffering support for platform filters. Filters may now utilize Envoy's internal buffering by returning the status StopIterationAndBuffer. The complete buffer will be passed on subsequent on*Data invocations until iteration is resumed. This change does not support modifying the buffer (support coming in #1100 ).
Testing: Unit coverage, local and CI
=> filters: support internal buffering

.bazelrc
Description: Bazel config `clang-asan` currently is unable to be run on MacOS due to a macro redefinition and missing dependencies. This alternative config works around these issues.
Testing: Local
=> build: add asan config runnable on MacOS

library/common/extensions/filters/http/platform_bridge/BUILD, library/common/extensions/filters/http/platform_bridge/c_type_definitions.h, library/common/extensions/filters/http/platform_bridge/c_types.cc, library/common/extensions/filters/http/platform_bridge/c_types.h, library/common/extensions/filters/http/platform_bridge/filter.cc, library/common/extensions/filters/http/platform_bridge/filter.h, library/common/types/c_types.cc, library/common/types/c_types.h, library/kotlin/src/io/envoyproxy/envoymobile/filters/Filter.kt, library/kotlin/src/io/envoyproxy/envoymobile/filters/FilterTrailersStatus.kt, library/objective-c/EnvoyBridgeUtility.h, library/objective-c/EnvoyEngine.h, library/objective-c/EnvoyEngineImpl.m, library/swift/src/filters/Filter.swift, test/common/extensions/filters/http/platform_bridge/platform_bridge_filter_test.cc
Description: Adds support for resuming iteration to platform filters via a new *ResumeIteration filter status. The API for platform filters requires all HTTP entities that should be forwarded to be attached to a result status of a filter invocation. When iteration is stopped, previous entities that were not forwarded may now be attached to the special ResumeIteration status, e.g., pending headers might be attached to ResumeIteration returned during an on-data invocation. See code documentation for additional detail. Full API documentation will be included in an upcoming PR.
Testing: Unit tests
=> filters: support new platform ResumeIteration status

ci/mac_ci_setup.sh
Description: This is a temporary measure due to frequent CI failures occurring on `brew update`. If this continues to be an issue, we can explore retries, a backup source for dependencies, or other options.
=> ci: temporarily skip brew update due to CI flakiness

.bazelrc
Description: Previously, setting `--config=asan-dev` would blow away the local build cache, forcing one to rebuild from scratch both to run asan, and then again for normal builds after. This change caches asan builds separately so that both normal builds and asan builds may benefit from caching without clobbering each other.
Testing: Local
=> build: cache local asan builds independently

library/kotlin/src/io/envoyproxy/envoymobile/filters/FilterDataStatus.kt
Description: Hardcoding these isn't ideal, but it works for now. Down the road, we should map dynamically at runtime.
Testing: Local with app filters
=> filters: map Kotlin enum to correct Envoy status

bazel/envoy_mobile_repositories.bzl, library/common/extensions/filters/http/platform_bridge/filter.proto
Updating to pull in https://github.com/envoyproxy/envoy/pull/13074 which will use Apple's DNS resolver for iOS in order to allow Envoy Mobile to ship on iOS 14 without triggering the "local area network" modal.
=> upstream: update with apple dns resolver

library/common/jni/jni_interface.cc, library/java/src/io/envoyproxy/envoymobile/engine/AndroidEngineImpl.java, library/java/src/io/envoyproxy/envoymobile/engine/EnvoyEngine.java, library/java/src/io/envoyproxy/envoymobile/engine/EnvoyEngineImpl.java, library/java/src/io/envoyproxy/envoymobile/engine/JniLibrary.java, library/kotlin/src/io/envoyproxy/envoymobile/StatsClient.kt, library/kotlin/src/io/envoyproxy/envoymobile/StatsClientImpl.kt, library/kotlin/src/io/envoyproxy/envoymobile/mocks/MockEnvoyEngine.kt, library/kotlin/src/io/envoyproxy/envoymobile/stats/Gauge.kt, library/kotlin/src/io/envoyproxy/envoymobile/stats/GaugeImpl.kt, library/kotlin/test/io/envoyproxy/envoymobile/StatsClientImplTest.kt, library/objective-c/EnvoyEngine.h, library/objective-c/EnvoyEngineImpl.m, library/swift/src/StatsClient.swift, library/swift/src/StatsClientImpl.swift, library/swift/src/mocks/MockEnvoyEngine.swift, library/swift/src/stats/Gauge.swift, library/swift/src/stats/GaugeImpl.swift, library/swift/test/StatsClientImplTests.swift
Description: Add Gauge Apis in the platform layers, after this change, gauge will be available for both iOS and Android platforms.
Testing: Unit tests and end to end in the Lyft Android app
=> stats: add gauge apis in jni and platform layers

library/objective-c/EnvoyEngineImpl.m
Description: The high-level representation of filter statuses with attached HTTP entities to be forwarded can't be directly represented across the bridge layer and must be mapped. Uniquely, resume iteration statuses may contain pending entities that have not yet been forwarded. This quick fix checks bounds explicitly for these cases in Objective-C.
=> filters: fix out of bound access to result status

.github/workflows/coverage.yml
Description: let the coverage report be uploaded even on failure. This allows contributors to see the report when the failure happens due to coverage below threshold errors.
Testing: testing by setting the coverage bar too high in an earlier commit.
=> coverage: continue to upload on error

library/common/jni/jni_interface.cc, library/common/jni/jni_utility.cc, library/common/jni/jni_utility.h, library/java/src/io/envoyproxy/envoymobile/engine/BUILD, library/java/src/io/envoyproxy/envoymobile/engine/EnvoyHTTPFilterCallbacksImpl.java, library/java/src/io/envoyproxy/envoymobile/engine/EnvoyNativeResourceRegistry.java, library/java/src/io/envoyproxy/envoymobile/engine/JvmFilterContext.java, library/java/src/io/envoyproxy/envoymobile/engine/types/BUILD, library/java/src/io/envoyproxy/envoymobile/engine/types/EnvoyHTTPFilter.java, library/java/src/io/envoyproxy/envoymobile/engine/types/EnvoyHTTPFilterCallbacks.java, library/kotlin/src/io/envoyproxy/envoymobile/filters/Filter.kt, library/kotlin/src/io/envoyproxy/envoymobile/filters/FilterResumeStatus.kt, library/kotlin/src/io/envoyproxy/envoymobile/filters/RequestFilterCallbacksImpl.kt, library/kotlin/src/io/envoyproxy/envoymobile/filters/ResponseFilterCallbacksImpl.kt
Description: Adds support for asynchronous filter callbacks to be set and called on Android and Java filters.
=> java: add Android and Java async filter callback support

library/common/extensions/filters/http/platform_bridge/filter.cc, library/common/extensions/filters/http/platform_bridge/filter.h
Description: This change moves platform filter callback setup from the PlatformBridgeFilter constructor into its own callback setup path. It's not possible to use shared/weak_from_this in the constructor because the shared pointer state doesn't exist yet.
Testing: Local
=> filters: fix weak pointer capture for filter callbacks

library/objective-c/EnvoyBridgeUtility.h
Description: Objective-C collections that don't allow nil use NSNull as a sentinel for missing values. Because these mappers may be used on values that come from collections, this fixes their null checks to be sensitive to NSNull as well as nil.
Testing: Local
=> filters: fix objc null checks to account for collections

library/common/engine.cc, library/common/engine.h, library/common/main_interface.cc, library/java/src/io/envoyproxy/envoymobile/engine/AndroidEngineImpl.java, library/java/src/io/envoyproxy/envoymobile/engine/EnvoyEngine.java, library/java/src/io/envoyproxy/envoymobile/engine/EnvoyEngineImpl.java, library/java/src/io/envoyproxy/envoymobile/engine/JniLibrary.java, library/kotlin/src/io/envoyproxy/envoymobile/mocks/MockEnvoyEngine.kt, library/kotlin/src/io/envoyproxy/envoymobile/stats/CounterImpl.kt, library/kotlin/test/io/envoyproxy/envoymobile/StatsClientImplTest.kt, library/objective-c/EnvoyEngine.h, library/objective-c/EnvoyEngineImpl.m, library/swift/src/mocks/MockEnvoyEngine.swift, library/swift/src/stats/CounterImpl.swift
Reverts lyft/envoy-mobile#1134
lyft/envoy-mobile#1134 introduced a bug where the jni method for `recordCounterInc` is mis-declared.
=> Revert "stats: update method names of counter"

library/swift/src/filters/Filter.swift
Description: The public and private representations of platform filters' compound statuses differ in ordering. In the public case, the ordering aligns with our chosen API, whereas in the private case, it's dictated by constraints in the type representation. This change fixes a bug which arose out of that misalignment. Note that fully-bridged types would avoid the potential for this sort of mapping bug.
Testing: Pending integration
=> filters: fix ordering of optional entities in swift statuses

library/common/extensions/filters/http/platform_bridge/filter.cc
Description: In certain cases - for example, when a previous filter in the chain stopped and buffered the request, and a subsequent filter stops iteration as well - the on-data filter invocation receives Envoy's internal buffer directly. This makes sense, since that's where Envoy has buffered all data, but it means that an attempt to preemptively aggregate new data into the buffer should be skipped: it's already there.
Testing: Local and CI (#1157)
=> filters: fix edge case where on-data receives Envoy's internal buffer

library/common/jni/jni_interface.cc
Description: A miss at the JNI layer was causing optional pending entities attached to resume iteration return statuses to be dropped. Upcoming additional coverage for this will include new example app filters and integration tests.
Testing: Local
=> filters: fix some missing JNI wiring

library/kotlin/src/io/envoyproxy/envoymobile/EngineBuilder.kt, library/swift/src/EngineBuilder.swift
Being able to specify a custom name can be helpful for reading `trace` logs which include named filters.
=> platform: add option for specifying custom filter names

library/java/src/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java, library/java/test/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt
Description: Added to assist while debugging filters.
=> java: show which key is unresolved in config errors

library/common/jni/jni_interface.cc
Description: Fixes error in JNI function signature, and adds missing parameter.
Testing: Local and CI (#1167)
=> filters: fix on-resume JNI call signature and parameters

library/common/config_template.cc
Description: adding stats now available from https://github.com/envoyproxy/envoy/pull/13942
Testing: local emission
=> stats: add dns counters

library/common/extensions/filters/http/platform_bridge/filter.cc, test/common/extensions/filters/http/platform_bridge/platform_bridge_filter_test.cc
Description: This ensures we don't trip an Envoy assertion when accessing the buffer under certain conditions.
=> filters: check iteration state before accessing internal buffer

docs/root/start/building/building.rst
Adds mention of Maven to the docs, and cross-links CocoaPods from the building section.
Resolves https://github.com/envoyproxy/envoy-mobile/issues/1189.
=> docs: update docs to mention Maven

library/objective-c/EnvoyEngine.h, library/objective-c/EnvoyEngineImpl.m, library/swift/src/EngineBuilder.swift, library/swift/src/EngineImpl.swift, library/swift/src/mocks/MockEnvoyEngine.swift, library/swift/test/EngineBuilderTests.swift
Description: Custom yaml will be treated as a configuration template, rather than a fixed set of configuration. It's still possible to pass fixed configuration, simply by not including any tokens for interpolation. This usage was already present and appeared supported by the API (e.g. see HttpBridgeTests), but simply wouldn't work, without any indication that it wouldn't.
=> ios: allow engine to be run with custom yaml template

library/common/jni/jni_interface.cc, library/java/src/io/envoyproxy/envoymobile/engine/JvmFilterContext.java, library/java/src/io/envoyproxy/envoymobile/engine/types/EnvoyHTTPFilter.java, library/kotlin/src/io/envoyproxy/envoymobile/filters/Filter.kt
Description: Adds JVM/Android wiring for on-cancel and on-error filter invocations.
=> filters: wire JVM/Android on-cancel and on-error pathways

tools/check_format.sh
Description: Allows the target path parameter to be passed through to `check_format.py`
Testing:
- Manual testing, a la `./tools/check_format.sh check` and `./tools/check_format.sh check library/common` to check that it works with and w/o a path
- Will be run as part of normal format check during PR, so any incompatibilities w/ CI setup will be bubbled up
=> tooling: allow for target path to be passed to check_format.py

envoy_build_config/BUILD, envoy_build_config/extension_registry.cc, envoy_build_config/extension_registry.h, envoy_build_config/extensions_build_config.bzl, library/common/buffer/utility.cc, library/common/buffer/utility.h, library/common/extensions/filters/http/local_error/BUILD, library/common/extensions/filters/http/local_error/config.cc, library/common/extensions/filters/http/local_error/config.h, library/common/extensions/filters/http/local_error/filter.cc, library/common/extensions/filters/http/local_error/filter.h, library/common/extensions/filters/http/local_error/filter.proto, library/common/http/BUILD, library/common/http/dispatcher.cc, library/common/http/dispatcher.h, library/common/http/headers.h, library/common/types/c_types.h, library/java/src/io/envoyproxy/envoymobile/engine/types/EnvoyHTTPFilterCallbacks.java, library/java/src/io/envoyproxy/envoymobile/engine/types/EnvoyOnEngineRunning.java, library/swift/test/HttpBridgeTests/ReceiveDataTest.swift, library/swift/test/HttpBridgeTests/ReceiveErrorTest.swift, library/swift/test/HttpBridgeTests/SendDataTest.swift, library/swift/test/HttpBridgeTests/SendHeadersTest.swift, library/swift/test/HttpBridgeTests/SendTrailersTest.swift, test/common/buffer/utility_test.cc, test/common/http/dispatcher_test.cc, test/integration/BUILD, test/integration/dispatcher_integration_test.cc
Description: Creates a filter to handle mapping local responses to errors, instead of baking the logic into the dispatcher. This additionally allows platform filters to receive onError callbacks.
Testing: Dispatcher integration, Swift integration, unit and manual
=> core: create LocalErrorFilter to map responses to errors

library/common/extensions/filters/http/platform_bridge/BUILD, library/common/extensions/filters/http/platform_bridge/filter.cc, library/common/extensions/filters/http/platform_bridge/filter.h, library/swift/test/HttpBridgeTests/ReceiveErrorTest.swift
Description: Leverages the LocalErrorFilter to provide on-error invocations for platform filters.
Testing: Integration test & manual
=> filters: dispatch on-error invocations from PlatformBridgeFilter

library/objective-c/EnvoyBridgeUtility.h
Description: Splits list-formatted header value on creation of header maps.  Per RFC 7230, does not perform this parsing on "set-cookie" headers, and additionally skips it on "www-authenticate" and "proxy-authenticate", due to their potential to contain commas in contravention of the spec.
=> ios: split comma-delimited header values when creating platform representation

library/java/src/io/envoyproxy/envoymobile/engine/JvmBridgeUtility.java, library/java/test/io/envoyproxy/envoymobile/engine/JvmBridgeUtilityTest.kt
Description: Splits list-formatted header value on creation of header maps.  Per RFC 7230, does not perform this parsing on "set-cookie" headers, and additionally skips it on "www-authenticate" and "proxy-authenticate", due to their potential to contain commas in contravention of the spec.
=> android: split comma-delimited header values when creating platform representation

library/cc/BUILD, library/cc/log_level.cc, library/cc/request_method.cc, library/cc/retry_policy.cc, library/cc/upstream_http_protocol.cc
**Description:**
All header changes in this PR come from https://github.com/envoyproxy/envoy-mobile/pull/1217, that should be reviewed and merged first.
This PR implements all of the enum-related code, like translating between string- and enum-representations. It also implements `RetryPolicy`, since it's related to `RetryRule` (and defined in the same file).
**Risk Level:** Low
**Testing:** N/A, will follow up when everything is finished with e2e testing + unit testing in Python and/orC++
**Docs Changes:** N/A
**Release Notes:** N/A
=> python: implement enum-related code

library/cc/BUILD, library/cc/stream.cc, library/cc/stream_callbacks.cc, library/cc/stream_client.cc, library/cc/stream_prototype.cc, library/python/BUILD, library/python/module_definition.cc, library/python/stream_prototype_shim.cc, library/python/stream_prototype_shim.h, library/python/stream_shim.cc
**Description:**
All header changes in this PR come from https://github.com/envoyproxy/envoy-mobile/pull/1217, that should be reviewed and merged first.
This PR implements all of the stream-related classes: `Stream`, `StreamCallbacks `EnvoyHttpCallbacksAdapter`, and `StreamPrototype`.
**Risk Level:** Low
**Testing:** N/A, will follow up when everything is finished with e2e testing + unit testing in Python and/orC++
**Docs Changes:** N/A
**Release Notes:** N/A
=> python: implement stream-related classes

library/cc/BUILD, library/cc/bridge_utility.cc, library/python/BUILD, library/python/bytes_view.cc
**Description:**
All header changes in this PR come from https://github.com/envoyproxy/envoy-mobile/pull/1217, that should be reviewed and merged first.
This implements all of the util functions used to convert between envoy-mobile types and cc-lib types. Note that right now it copies _all_ data at the border between envoy-mobile and the cc-lib, which is inefficient. As noted in the TODO, this is going to be a good place for optimization.
**Risk Level:** Low
**Testing:** N/A, will follow up with testing in only C++, since this won't be exposed into the Python layer.
**Docs Changes:** N/A
**Release Notes:** N/A
=> python: implement bridge utilities

library/common/extensions/filters/http/platform_bridge/filter.cc, library/common/extensions/filters/http/platform_bridge/filter.h, test/common/extensions/filters/http/platform_bridge/platform_bridge_filter_test.cc
Description: Adds support for injecting data and/or trailers specifically during onResume() callbacks when resuming filter iteration asynchronously. This is accomplished by passing back data and/or trailers where none were originally present at the point of resumption.
=> filters: add support for data and trailers injection

docs/root/development/performance/binary_size.rst, docs/root/development/performance/cpu_battery_impact.rst, docs/root/development/performance/device_connectivity.rst, docs/root/development/testing/testing.rst, docs/root/start/building/building.rst, docs/root/start/examples/hello_world.rst
Description: bazelisk is the default and preferred way to build to ensure consistency as much as possible. This change updates the project's docs to refer to bazelisk when providing example build commands.
=> docs: update commands to reference bazelisk

library/kotlin/src/io/envoyproxy/envoymobile/stats/CounterImpl.kt, library/kotlin/src/io/envoyproxy/envoymobile/stats/GaugeImpl.kt
Description: construct the stats name in constructor, avoid string join during stats reporting (inc, set, etc.)
Testing: unit, ci
Signed-off-by: Jingwei Hao <jingweih@lyft.com>
=> stats: avoid string join during stats reporting

library/common/config_template.cc
Description: This change will result in faster dead connection cycling at the expense of much busier connections once keepalive triggers. It's probably not an appropriate setting in all cases, but supports an experiment we're running with connection behavior on preferred interface switchovers. Applications can still override this to meet their specific requirements until we land a reasonable default. Augmenting this with h2 pings will give us quite a bit more flexibility.
Testing: CI
=> config: experiment with tighter keepalive configuration

library/common/extensions/filters/http/assertion/BUILD, library/common/extensions/filters/http/local_error/BUILD, library/common/extensions/filters/http/platform_bridge/BUILD, library/common/extensions/stat_sinks/metrics_service/BUILD
Updating upstream to include: https://github.com/envoyproxy/envoy/pull/14945
Update includes adding extension categories for `envoy_cc_extension`
Description: Updating upstream to include: https://github.com/envoyproxy/envoy/pull/14945
Testing: CI
=> Update envoy to b1caeb3

envoy_build_config/extension_registry.cc, envoy_build_config/extension_registry.h, envoy_build_config/extensions_build_config.bzl, library/common/config_template.cc
Description: unregister custom stats sink until the backend service is ready
Testing: ci/unit
Signed-off-by: Jingwei Hao <jingweih@lyft.com>
=> stats: unregister custom stats sink

library/common/extensions/filters/http/platform_bridge/filter.cc, test/common/extensions/filters/http/platform_bridge/BUILD, test/common/extensions/filters/http/platform_bridge/platform_bridge_filter_integration_test.cc, test/common/extensions/filters/http/platform_bridge/platform_bridge_filter_test.cc
Description: A previous change caused the pointer to the mutable buffer to be retrieved regardless of iteration state which trips an internal assertion in Envoy.
Testing: New integration test
=>  filters: only access mutable buffer when iteration is stopped on current 

library/common/extensions/filters/http/local_error/filter.cc
Description: A member pointer was erroneously being accessed that should have been a local. Fixed and refactored to simplify call path.
Testing: New coverage will be added in upcoming PR
=> grpc errors: fix pointer access

library/swift/test/HttpBridgeTests/BUILD, library/swift/test/HttpBridgeTests/GRPCReceiveErrorTest.swift
Description: This test covers the case where the LocalErrorFilter transforms a locally generated response for a gRPC request to an error.
Note: Kotlin tests can be added once we have #1263.
Testing: This commit adds coverage.
=> coverage: integration test for LocalErrorFilter when using gRPC

examples/swift/hello_world/ViewController.swift, library/kotlin/src/io/envoyproxy/envoymobile/ResponseHeaders.kt, library/kotlin/src/io/envoyproxy/envoymobile/ResponseHeadersBuilder.kt, library/kotlin/test/io/envoyproxy/envoymobile/ResponseHeadersTest.kt, library/swift/src/ResponseHeaders.swift, library/swift/src/ResponseHeadersBuilder.swift, library/swift/test/ResponseHeadersTests.swift
We can prevent an [assert from being hit within Envoy](https://github.com/envoyproxy/envoy/blob/17e815122ff53d0ac6cb2d64cdbf1bfc547bb7e8/source/common/http/utility.cc#L441-L448) if the end consumer attempts to set a negative status code via these platform interfaces.
=> swift/kotlin: enforce unsigned :status code values

library/common/jni/jni_interface.cc, library/common/jni/jni_utility.cc
Description: These caused an almost immediate crash on a Galaxy S8 for some reason, but are a problem regardless.
Testing: Device
Co-authored-by: Alan Chiu <achiu@lyft.com>
=> jni: fix local ref leaks

library/swift/src/stats/Counter.swift, library/swift/src/stats/CounterImpl.swift, library/swift/src/stats/DistributionImpl.swift, library/swift/src/stats/GaugeImpl.swift, library/swift/src/stats/TimerImpl.swift
- Make some classes final since they are not intended to be subclassed
- Use optional chaining to simplify guard statements
- Move todos into functions to avoid them showing up in documentation
=> swift: clean up some stats types

docs/root/development/performance/binary_size.rst, test/performance/BUILD
Description: fixing bazel target with explicit stamp. Also updating docs with information about debug symbols.
Testing: local binary size analysis
Docs Changes: updated relevant docs.
=> size: update docs and bazel target

ci/mac_ci_setup.sh
Description: Fixes CI. MacOS images seem to have a "good enough" version of go pre-installed now.
Testing: CI
=> ci: skip go install
