envoyproxy/envoy-mobile

README.md

Final text from legal and LF/CNCF.

readme: update license text

---

docs/root/start/building/building.rst

Description: update bazel requirements in the building instructions.
Risk Level: low. Doc changes.
Testing: CI
Docs Changes: update bazel requirements in the building instructions.

docs: bazel requirements

---

docs/build.sh

We don't have immediate plans to implement this, so removing the TODO for the time being.

cleanup: remove outdated todo

---

ci/linux_ci_setup.sh

Description: clean up commented out ndk install
Risk Level: low. deleted commented out code.
Testing: CI

ci: clean up commented out ndk install

---

README.md

This should help make the roadmap a bit more visible.

readme: link living roadmap

---

docs/root/start/building/building.rst
docs/root/start/examples/hello_world.rst

Description: docs on using prebuilt artifacts

docs: using prebuilt artifacts

---

WORKSPACE

Fixes: https://github.com/lyft/envoy-mobile/issues/72

bazel: downgrade abseil

---

WORKSPACE

WORKSPACE: reference abseil workaround issue

---

docs/root/intro/version_history.rst

docs: update release date of 0.1.0

---

azure-pipelines.yml

Description: ci: android ci on mac
Fixes #106

ci: android ci on mac

---

azure-pipelines.yml
tools/check_format.sh

Co-authored-by: Jose Ulises Nino Rivera <junr03@users.noreply.github.com>

lint: fix format checker script

---

BUILD

java: fix src name dependency rename

---

BUILD

Description: fix small typo
Risk Level: low -- fix inline comment typo

comment: small typo fix

---

examples/objective-c/hello_world/ViewController.mm

Per Apple best practices.
Testing: CI
Docs Changes: No

demo: change objc true to YES

---

.bazelrc

build: add arch options configuration

---

library/BUILD
library/java/io/envoyproxy/envoymobile/engine/BUILD

build: clean up java dep structure

---

library/objective-c/Envoy.h
library/objective-c/Envoy.mm

logging: add EnvoyLogLevel enum to iOS interface

---

BUILD
library/kotlin/io/envoyproxy/envoymobile/BUILD

build: clean up kotlin deps

---

.swiftlint.yml
examples/objective-c/hello_world/ViewController.mm
examples/swift/hello_world/Response.swift
examples/swift/hello_world/ResponseModels.swift
examples/swift/hello_world/ViewController.swift

Update the Swift and Objective-C demos to follow the UI logic implemented by https://github.com/lyft/envoy-mobile/pull/166.
Resolves https://github.com/lyft/envoy-mobile/issues/168.

ios: update demos to display errors

---

library/kotlin/io/envoyproxy/envoymobile/Envoy.kt

logging: add LogLevel enum to kotlin interface

---

azure-pipelines.yml
ci/templates/start_android_emulator.yaml
examples/java/hello_world/MainActivity.java
examples/kotlin/shared/ResponseViewHolder.kt

Signed-off-by: Jose Nino jnino@lyft.com
Description: previously the CI runs would only build the demos. However we did not run them, or check for liveliness. This PR adds running all the Android demos in the emulator for Mac CI.
Risk Level: low - improved CI
Testing: tested locally and on CI
Fixes #117

ci: run android apps in the emulator

---

docs/root/development/performance/device_conditions.rst
docs/root/development/performance/performance.rst

Adding some details on the application lifecycle/network conditions investigation with Envoy on Android. I added sections for iOS so @rebello95 can integrate his findings here too.
Description: device conditions analysis for Android
Testing: locally
Docs Changes: /performance/device_conditions.rst

docs: device conditions analysis

---

docs/conf.py
docs/root/development/performance/cpu_battery_impact.rst

Adding sphinx extensions for sha references and issues
Description: add sphinx extensions for tree and issues
Testing: local
Docs Changes: /docs
Release Notes:

Add sphinx extensions for tree and issues

---

docs/root/development/performance/cpu_battery_impact.rst

Fixes a link, as well as the formatting of the top section.

docs: fix link CPU/battery analysis

---

docs/root/development/performance/device_conditions.rst

Resolves https://github.com/lyft/envoy-mobile/issues/128.

perf: add iOS docs on device conditions

---

library/swift/Envoy.swift

Restricting subclassing and visibility of these types.
Testing: CI

swift: make classes final/private

---

library/swift/Envoy.swift

swift: make Envoy visible to Objective-C

---

library/common/jni_interface.cc
library/common/main_interface.cc
library/common/main_interface.h
library/objective-c/Envoy.mm
library/objective-c/EnvoyEngine.mm
test/performance/test_binary_size.cc

Co-authored-by: Jose Ulises Nino Rivera <junr03@users.noreply.github.com>
Description: Introduces the interfaces for the core API.
Testing: CI

core api: add header definitions for native interface

---

library/swift/src/Envoy.swift

swift: add docstrings to main Envoy class

---

docs/root/start/building/building.rst
docs/root/start/examples/hello_world.rst

docs: update to mention bazelw wrapper

---

WORKSPACE
azure-pipelines.yml

Description: pulling in tip of envoy master.
Testing: CI

upstream: update envoy ref

---

library/objective-c/BUILD

bazel: remove unused envoy_engine_hdrs

---

library/objective-c/EnvoyEngine.h
library/objective-c/EnvoyEngine.mm

We missed this one in https://github.com/lyft/envoy-mobile/pull/290.

objc: add shim function for starting stream

---

WORKSPACE

build: Switch to better kotlin rules

---

.bazelrc
docs/root/start/building/building.rst

bazel: update to Xcode 10.3

---

.bazelrc
WORKSPACE
library/common/http/dispatcher.cc
library/common/http/dispatcher.h

don't merge before https://github.com/lyft/envoy-mobile/pull/316

envoy: update upstream for onComplete callback

---

examples/common/config.yaml

example apps: fix config

---

library/common/http/dispatcher.cc
library/common/http/dispatcher.h
library/common/main_interface.cc
library/common/main_interface.h
library/objective-c/EnvoyEngine.m
test/common/http/dispatcher_test.cc

core: init functions

---

library/swift/src/Envoy.swift

Description: delete commented out line

swift: delete commented out line

---

library/common/include/c_types.h

bridge: remove unneeded struct

---

library/objective-c/EnvoyEngine.m

cruft: delete dead commented line

---

.github/workflows/android.yml
.github/workflows/core.yml
.github/workflows/format.yml
.github/workflows/ios.yml
.github/workflows/perf.yml

This will prevent machines from switching beneath us.

ci: pin macOS and linux versions

---

library/java/src/io/envoyproxy/envoymobile/engine/EnvoyHTTPStream.java

java: fix master linter

---

bazel/swift_static_framework.bzl

Addressing https://github.com/lyft/envoy-mobile/pull/372#discussion_r316845384

bazel: assert if '-Swift.h' files are not exactly 1

---

BUILD
examples/java/hello_world/BUILD
examples/java/hello_world/EmptyFile.kt
examples/java/hello_world/MainActivity.java
examples/kotlin/hello_world/MainActivity.kt
library/kotlin/src/io/envoyproxy/envoymobile/Envoy.kt
library/kotlin/src/io/envoyproxy/envoymobile/ResponseHandler.kt

Description: android: java envoy pass through implementation
Testing: local

android: java envoy pass through implementation

---

test/common/http/BUILD
test/common/http/dispatcher_test.cc

Description: sendData/onData dispatcher unit tests now that #284 is closed.
Testing: added unit tests

core: sendData/onData dispatcher unit tests

---

library/common/jni_interface.cc
library/java/src/io/envoyproxy/envoymobile/engine/JvmObserverContext.java

Description: this PR adds functionality to send data to HTTP streams and receive data from callbacks for Android.
Risk Level: med - adds core functionality.
Testing: tested locally with the kotlin app and an echo endpoint. Data was seen on both the send and the received direction.
Co-authored-by: Jose Nino <jnino@lyft.com>

java: data passthrough

---

library/common/http/dispatcher.cc
library/common/http/dispatcher.h

Description: docstrings for dispatcher header

cleanup: docstrings for dispatcher header

---

library/java/src/io/envoyproxy/envoymobile/engine/types/EnvoyObserver.java

Description: delete extraneous comment

cleanup: delete extraneous comment

---

examples/objective-c/hello_world/ViewController.m
examples/swift/hello_world/ViewController.swift
library/kotlin/src/io/envoyproxy/envoymobile/Client.kt
library/kotlin/src/io/envoyproxy/envoymobile/Envoy.kt
library/swift/src/Client.swift
library/swift/src/Envoy.swift

interface: use 'body' as parameter name for send

---

library/common/jni_interface.cc
library/java/src/io/envoyproxy/envoymobile/engine/EnvoyHTTPStream.java
library/java/src/io/envoyproxy/envoymobile/engine/JniLibrary.java

jni: add support for on-heap buffers

---

library/objective-c/EnvoyHTTPStreamImpl.m

Right now, if a consumer fails to set any closure in the `EnvoyHTTPCallbacks`, a crash will occur when the `EnvoyHTTPStreamImpl` attempts to call the closure.
It's reasonable to assume that a consumer might not care about each available callback (i.e., never setting `onCanceled`). We can guard against this by validating each closure is actually set before trying to call it.
Tested locally and this solves the problem.

objective-c: guard against nil callbacks

---

EnvoyMobile.podspec
docs/root/start/building/building.rst

Description: fixing some formatting issues from #431 

fmt: fix precommit errors

---

WORKSPACE

This is required for us to update to Xcode 11

bazel: update iOS rules

---

library/common/config_template.cc
library/java/src/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java
library/java/test/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt
library/kotlin/test/io/envoyproxy/envoymobile/EnvoyClientBuilderTest.kt
library/objective-c/EnvoyConfiguration.m
library/swift/test/EnvoyClientBuilderTests.swift

Description: there were inconsistencies in the config that led to envoy not being able to start. This PR fixes them.
Testing: CI and locally

config: clean up and fix config

---

.bazelrc
docs/root/start/building/building.rst

ci: Update to Xcode 11

---

.github/workflows/ios.yml

Description: turn liveliness tests in CI back on.
Testing: CI

ios: liveliness test in CI

---

library/common/http/dispatcher.h

dispatcher: explicitly null-initialize pointers

---

library/common/jni_interface.cc

Description: Just minor cleanup.

jni: move function to correct section

---

library/objective-c/BUILD

cleanup: remove dated inapplicable todo

---

library/common/jni_interface.cc

jni: init ares from Android-specific call

---

library/common/http/dispatcher.cc

Description: set stream options to buffer stream body for retries.
Risk Level: med - the client now buffers stream body for retries.
Testing: local - lyft and example apps.

core: buffer body for retries

---

library/kotlin/test/io/envoyproxy/envoymobile/GRPCResponseHandlerTest.kt
library/kotlin/test/io/envoyproxy/envoymobile/ResponseHandlerTest.kt

Description: kotlin: make tests timeout in 1s
Testing: this is it

kotlin: make tests timeout in 1s

---

docs/root/about_docs.rst
docs/root/index.rst
docs/root/intro/intro.rst
docs/root/intro/what_is_envoy_mobile.rst

- Remove `about_docs.rst`
- Fix file name
- Fix table of contents title of `What is Envoy Mobile?`
- Fix capitalization

docs: minor cleanup

---

docs/root/start/examples/hello_world.rst

docs: update outdated example documentation

---

library/common/jni_interface.cc
library/java/src/io/envoyproxy/envoymobile/engine/EnvoyEngine.java
library/java/src/io/envoyproxy/envoymobile/engine/EnvoyEngineImpl.java
library/java/src/io/envoyproxy/envoymobile/engine/EnvoyHTTPStream.java
library/java/src/io/envoyproxy/envoymobile/engine/JniLibrary.java
library/kotlin/src/io/envoyproxy/envoymobile/EnvoyClient.kt
library/kotlin/test/io/envoyproxy/envoymobile/EnvoyClientTest.kt

Description: android parallel to https://github.com/lyft/envoy-mobile/pull/521. 
Risk Level: low - matching ios functionality
Testing: unit tests
Fixes #524

android: only buffer when requests support retries

---

docs/root/development/performance/binary_size.rst
docs/root/development/performance/performance.rst

docs: resolve TODO for binary size CI integration

---

docs/root/development/performance/cpu_battery_impact.rst

docs: link issue for update in CPU/battery analyses

---

docs/root/development/development.rst
docs/root/development/testing/testing.rst

docs: add docs for running tests locally

---

envoy_build_config/extensions_build_config.bzl

Description: add metrics service extension

build: add metrics service extension

---

library/common/engine.cc

Description:  previously there were still races if the exit call was dispatched. This avoids the dispatch and runs the exit callback on the main thread, while ensuring that nothing else can fire after.

shutdown: more deterministic exit behavior

---

.github/workflows/format.yml

Description: updating envoy submodule
Risk Level: med - lots of commits
Testing: CI

submodule: update envoy to 92c085

---

library/common/main_interface.cc

Description: Makes the return path of start stream consistent with other stream calls.
Risk Level: Very low
Testing: CI

core: return result state on start stream

---

library/common/jni_interface.cc

Description: I believe this was probably a bad copy paste.
Testing: builds.

nit: remove unneeded variable

---

EnvoyMobile.podspec

ios: update podspec for v0.2.0

---

docs/root/api/grpc.rst
docs/root/api/http.rst
docs/root/api/starting_envoy.rst

Description: fixing some bad refs in the docs.
Risk Level: low.
Testing: locally built docs
Docs Changes: fixing broken links
Fixes #590. Thanks for reporting @derekargueta, nice to see you here :)

docs: fix broken links

---

.github/workflows/release.yml
.gitignore
BUILD
bazel/pom_template.xml
ci/linux_ci_setup.sh
ci/mac_ci_setup.sh
dist/sonatype_nexus_upload.py
dist/upload_maven.py

Maven public releases through sonatype requires the following artifacts:
1. `aar` or `jar` artifact
2. `pom.xml` which describes the artifact
3. `-sources.jar` which contains the code sources
4. `-javadoc.jar` which contains the java docs for the APIs
5. `*.asc` for each of the above signed (`gpg -ab "FILE"`)by a GPG key which sonatype knows about in order to verify the artifacts are uploaded by a trusted source
This means we have the following 8 files to upload:
Artifacts:
```
dist/envoy.aar
dist/envoy-pom.xml
dist/envoy-sources.jar
dist/envoy-javadoc.jar
```
GPG signed:
```
dist/envoy.aar.asc
dist/envoy-pom.xml.asc
dist/envoy-sources.jar.asc
dist/envoy-javadoc.jar.asc
```
The sonatype release process can be found [here](https://help.sonatype.com/repomanager2/staging-releases/staging-over …

android: sonatype maven release script

---

.bazelrc
ci/mac_ci_setup.sh
docs/root/start/building/building.rst

Resolves https://github.com/lyft/envoy-mobile/issues/581

ios: update to Xcode 11.2.1

---

.bazelrc

Description: Makes things consistent with the main project (and makes it slightly easier to add or comment out lines).

build: update .bazelrc with Envoy-style formatting and comments

---

.bazelrc
ci/mac_ci_setup.sh
docs/root/start/building/building.rst

update to Xcode 11.3

---

docs/root/development/development.rst
docs/root/development/releasing/releasing.rst

docs: add documentation for tagging releases

---

ci/test_size_regression.sh

Description: updating the envoy ref again and the absolute binary size per #447.
Testing: CI

envoy: update envoy ref

---

README.md
docs/root/intro/additional_resources.rst
docs/root/intro/intro.rst

docs: add additional resources

---

library/common/http/dispatcher.cc
library/common/http/dispatcher.h

Description: noticed an opportunity for cleanup
Risk Level: low, cleanup unused instance variable
Testing: CI

cleanup: delete metadata_ member

---

docs/root/intro/additional_resources.rst

Description: add @rebello95's talk to additional resources.

docs: add Rebello's talk to additional resources

---

docs/root/intro/additional_resources.rst

docs: add stats blog to additional resources

---

library/common/http/dispatcher.cc
library/common/http/dispatcher.h
test/common/http/dispatcher_test.cc

upstream: update header maps on response path

---

library/objective-c/EnvoyConfiguration.m
library/objective-c/EnvoyEngineImpl.m

This will make them easier to grep.

ios: prefix NSLog statements with `[Envoy]`

---

library/objective-c/EnvoyNetworkMonitor.m

ios: add log for switching preferred networks

---

docs/build.sh
docs/root/development/performance/performance.rst
docs/root/development/performance/vpn_analysis.rst

Adds documentation on the VPN analysis I did with Envoy Mobile.
Resolves https://github.com/lyft/envoy-mobile/issues/499 for now. Future work will be tracked in https://github.com/lyft/envoy-mobile/issues/727.

docs: add docs on VPN investigation

---

docs/root/development/performance/binary_size.rst

docs: update iOS binary size analysis

---

docs/root/api/starting_envoy.rst

Resolves https://github.com/lyft/envoy-mobile/issues/715.

docs: add docs on `EnvoyClientBuilder`

---

library/common/config_template.cc

Description: update envoy and include x-envoy-attempt-count in responses
Risk Level: low, the new config option attaches a new header to responses.
Testing: unit and integration tests in Envoy for the new feature.

routing: update envoy and include x-envoy-attempt-count in responses

---

.github/workflows/core.yml
test/integration/dispatcher_integration_test.cc

Description: noticed that core.yml was running `bazel test //test/common/...` this PR pushes the command one level up.
Testing: CI coverage for the entire test suite.

test: update integration test

---

library/common/engine.cc
library/common/http/dispatcher.cc
library/common/http/dispatcher.h
library/common/jni_interface.cc
library/java/src/io/envoyproxy/envoymobile/engine/EnvoyEngineImpl.java
library/kotlin/src/io/envoyproxy/envoymobile/GRPCResponseHandler.kt
library/kotlin/test/io/envoyproxy/envoymobile/GRPCStreamEmitterTest.kt
library/objective-c/EnvoyHTTPStreamImpl.m

Description: in preparation of cutting v0.3 I went ahead and audited inline TODOs.

cleanup: pass over todos

---

test/common/http/dispatcher_test.cc

Description: test for missing coverage in https://github.com/lyft/envoy-mobile/issues/653
Testing: add new expectation
Fixes https://github.com/lyft/envoy-mobile/issues/654

test: add test for reset callback to the http conn manager

---

test/common/http/dispatcher_test.cc

Description: added missing test for dispatcher queueing
Risk Level: low, in fact things are better because there are tests :)
Testing: added missing unit test
Fixes #449 

test: unit test for http dispatcher queueing 

---

library/common/http/dispatcher.h

Description: updates envoy to f4931758d29b2aa6be89900650aeee54addb1827. This brings a few relevant changes for envoy mobile:
-  Additional observability for virtual clusters: https://github.com/envoyproxy/envoy/pull/10474 https://github.com/envoyproxy/envoy/pull/10499 https://github.com/envoyproxy/envoy/pull/10501
-  32-bit compatibility fix https://github.com/envoyproxy/envoy/pull/10510
- Android re-definition of `mmsghdr` fix https://github.com/envoyproxy/envoy/pull/10521

update envoy f4931758d29

---

WORKSPACE

[bazel] Update rules

---

library/kotlin/src/io/envoyproxy/envoymobile/HTTPClient.kt

kotlin: clean up HTTPClient.kt formatting

---

ci/kotlin_lint.sh

Description: update kotlin linter
Testing: ci

[kotlin] update detekt to 1.8.0

---

docs/root/api/grpc.rst
docs/root/api/http.rst

Updating docs to reflect changes from https://github.com/lyft/envoy-mobile/pull/802.

docs: update docs for new platform interfaces

---

docs/root/intro/additional_resources.rst

Description: these translations were graciously written by @XAntonioLuna @sgenius and @gonzalolarralde and published in [Lyft Engineering en Español](https://medium.com/lyft-engineering-en-español)

docs: spanish translation of blog posts

---

docs/root/intro/additional_resources.rst

docs: add qcon london talk

---

.bazelrc

build: Enable opt for Swift compiles

---

examples/kotlin/shared/ResponseViewHolder.kt

Testing: tested locally, saw expected colors and transitions.

android: fix color in example app

---

docs/root/development/performance/cpu_battery_impact.rst

Did a quick experiment to see how Envoy Mobile performs now as a library
Description: android: update docs with cpu/battery analysis
Testing: n/a

android: update docs with cpu/battery analysis

---

library/swift/src/BUILD

swift: remove outdated TODO

---

envoy-mobile.tulsiproj/Configs/all.tulsigen

tulsi: Add all targets

---

envoy-mobile.tulsiproj/Configs/all.tulsigen
envoy-mobile.tulsiproj/project.tulsiconf

tulsi: include examples in xcodeproj

---

library/common/http/BUILD
library/common/http/dispatcher.h

build: dep cleanup

---

tools/check_format.sh

Description: Always needed for this project, so it might as well be baked in.

build: add ENVOY_BAZEL_PREFIX to check_format script

---

envoy-mobile.tulsiproj/Configs/all.tulsigen

tulsi: update project generation config

---

library/common/config_template.cc

This reverts commit 6cd5ffe1cb38c7a2e9834bb6dbbd45f158063ef0.

Revert "stats: add stats for specific 4xx codes (#902)"

---

.bazelrc
bazel/envoy_mobile_repositories.bzl
ci/mac_ci_setup.sh

ios: upgrade to Xcode 11.5

---

.github/workflows/android.yml
.github/workflows/artifacts.yml
.github/workflows/core.yml
.github/workflows/coverage.yml
.github/workflows/format.yml
.github/workflows/ios.yml
.github/workflows/perf.yml

Description: Switches CI workflows to be based off our new default main branch.
Testing: CI

build: update workflows to be based on main branch

---

PULL_REQUEST_TEMPLATE.md
ci/test_size_regression.sh
docs/README.md
docs/publish.sh
docs/root/development/releasing/releasing.rst
docs/root/development/testing/testing.rst

project: update tools and usage to refer to main branch

---

docs/root/api/starting_envoy.rst
library/kotlin/src/io/envoyproxy/envoymobile/RetryPolicy.kt
library/swift/src/RetryPolicy.swift

documentation: update some language

---

bazel/android_artifacts.bzl

build: update bazel rule for java_binary

---

library/common/config_template.cc
library/common/extensions/filters/http/platform_bridge/filter.cc
library/common/extensions/filters/http/platform_bridge/filter.proto

Description: Missed this request from @junr03 on #940.

filters: rename config property

---

library/common/extensions/filters/http/platform_bridge/filter.cc

Description: The assumption underpinning the optimization is unsound and results in non-determinism. Added TODO for safe approach.
Testing: Local end-to-end

filters: remove unsafe optimization

---

.bazelrc
library/common/BUILD

Signed-off-by: Yifan Yang <needyyang@google.com>
Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:

Subject: changing the C++17 build flag

---

STYLE.md

docs: pin link to sha

---

examples/swift/hello_world/DemoFilter.swift
library/kotlin/src/io/envoyproxy/envoymobile/filters/FilterDataStatus.kt
library/objective-c/BUILD
library/objective-c/EnvoyBridgeUtility.h
library/objective-c/EnvoyEngine.h
library/objective-c/EnvoyEngineImpl.m
library/objective-c/EnvoyHTTPStreamImpl.m
library/swift/src/filters/Filter.swift
library/swift/src/filters/FilterDataStatus.swift

Description: Completes end-to-end functionality for bridged platform filters on iOS. Factors out duplication in objective-c bridging functions.
Testing: Local end-to-end

filters: wire data and trailers for iOS

---

library/common/BUILD
library/common/api/external.cc
library/common/config_template.cc
library/common/http/dispatcher.h
test/common/envoy_mobile_main_common_test.cc
test/integration/dispatcher_integration_test.cc
test/performance/BUILD

update envoy to f958d39fcd

---

ci/test_size_regression.sh

perf: increase size limit

---

library/java/src/io/envoyproxy/envoymobile/engine/types/BUILD
library/java/src/io/envoyproxy/envoymobile/engine/types/EnvoyHTTPFilter.java
library/java/src/io/envoyproxy/envoymobile/engine/types/EnvoyHTTPFilterFactory.java
library/kotlin/src/io/envoyproxy/envoymobile/Headers.kt
library/kotlin/src/io/envoyproxy/envoymobile/StreamClientBuilder.kt
library/kotlin/src/io/envoyproxy/envoymobile/filters/Filter.kt
library/kotlin/src/io/envoyproxy/envoymobile/filters/FilterHeadersStatus.kt
library/kotlin/src/io/envoyproxy/envoymobile/filters/RequestFilter.kt
library/kotlin/src/io/envoyproxy/envoymobile/filters/ResponseFilter.kt

Description: Changes filter instantiation to be a per-stream basis at the Android platform layers.

filters: instantiate on Android on a per-stream basis

---

envoy_build_config/extensions_build_config.bzl
library/common/network/synthetic_address_impl.h
test/integration/dispatcher_integration_test.cc

Updating primarily to include decompressor fixes: https://github.com/envoyproxy/envoy/pull/12483.
Updates to fix breaking changes from https://github.com/envoyproxy/envoy/commit/da403fa7b67b9331ca1d129a4035950d2e23c752 as well.

upstream: bump Envoy ref

---

examples/swift/hello_world/ViewController.swift
library/common/config_template.cc
library/common/main_interface.h
library/java/src/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java
library/objective-c/EnvoyConfiguration.m
library/swift/test/StreamClientBuilderTests.swift

Description: Adds dynamically-generated configuration for platform filter chains, allowing for registration of custom filters.

filters: add dynamically-generated configuration

---

library/common/extensions/filters/http/assertion/BUILD
library/common/extensions/filters/http/assertion/filter.cc
library/common/extensions/filters/http/assertion/filter.h
library/common/extensions/filters/http/assertion/filter.proto

update envoy: cf850688a93b8dea5705170a211ea98b77beda61

---

library/common/network/BUILD
library/common/network/synthetic_address_impl.h

update envoy: 7f3e8a85ff1dbc3f3aec54dad7b5450aa53a98cd

---

bazel/envoy_mobile_dependencies.bzl
library/java/src/io/envoyproxy/envoymobile/engine/BUILD
library/java/src/io/envoyproxy/envoymobile/engine/JvmBridgeUtility.java
library/java/test/io/envoyproxy/envoymobile/engine/BUILD
library/java/test/io/envoyproxy/envoymobile/engine/JvmBridgeUtilityTest.kt

Description: Adds unit-level coverage to the JvmBridgeUtility.

coverage: add unit tests for JvmBridgeUtility

---

test/common/http/dispatcher_test.cc

Description: adding more tests in the Http::Dispatcher to exercise different interleavings of double Dispatcher::streamReset(stream) calls. Everything behaves as expected.
Risk Level: low test only PR
Testing: additional tests 

dispatcher: add more unit tests

---

examples/kotlin/hello_world/DemoFilter.kt
examples/kotlin/hello_world/MainActivity.kt
library/common/jni/jni_interface.cc
library/java/src/io/envoyproxy/envoymobile/engine/BUILD
library/java/src/io/envoyproxy/envoymobile/engine/EnvoyHTTPStream.java
library/java/src/io/envoyproxy/envoymobile/engine/JniBridgeUtility.java
library/java/src/io/envoyproxy/envoymobile/engine/JvmFilterContext.java
library/kotlin/src/io/envoyproxy/envoymobile/filters/Filter.kt
library/kotlin/src/io/envoyproxy/envoymobile/filters/FilterDataStatus.kt
library/kotlin/src/io/envoyproxy/envoymobile/filters/FilterHeadersStatus.kt
library/kotlin/src/io/envoyproxy/envoymobile/filters/FilterTrailersStatus.kt

Description: Wires the return path for Android filter invocations, allowing modification of the current HTTP entity.

filters: wire Android return path

---

examples/objective-c/hello_world/Result.h
examples/objective-c/hello_world/ViewController.m
examples/swift/hello_world/ResponseModels.swift
examples/swift/hello_world/ViewController.swift

Description: Allows rendering of additional headers. Leftover from testing platform filters; seemed worth cleaning up and merging.

iOS example apps: improve header rendering

---

examples/java/hello_world/MainActivity.java
examples/kotlin/hello_world/MainActivity.kt
examples/kotlin/shared/res/layout/item.xml
examples/kotlin/shared/res/values/strings.xml

Description: Allows rendering of additional headers. Leftover from testing platform filters; seemed worth cleaning up and merging.

Android example apps: improve header rendering

---

library/common/engine.h

documentation: add missing params in engine.h

---

library/common/jni/BUILD
library/common/jni/jni_interface.cc
library/common/jni/jni_utility.cc
library/common/jni/jni_utility.h
library/common/jni/jni_version.cc
library/common/jni/jni_version.h

Description: Phase one of JNI cleanup. Moves utility functions to a dedicated library.
Risk: Low
Testing: CI and Local

jni: extract utility library

---

.github/workflows/ios.yml

ci: increase timeout for swift_tests

---

library/common/jni/jni_utility.cc

jni: fix usage of malloc

---

library/kotlin/src/io/envoyproxy/envoymobile/StatsClientImpl.kt
library/kotlin/src/io/envoyproxy/envoymobile/stats/Counter.kt
library/kotlin/src/io/envoyproxy/envoymobile/stats/CounterImpl.kt

Description: Parallels Swift to improve testability and reduce coupling to implementation.
Testing: CI

stats: add kotlin Counter interface

---

library/common/certificates.inc

Description: Removes many expired certs; syncs with OpenBSD/LibreSSL.
Risk Level: High
Testing: Local

security: update root certificate chain

---

library/java/src/io/envoyproxy/envoymobile/engine/JvmFilterContext.java

docstrings: fix return values in JvmFilterContext

---

library/java/test/io/envoyproxy/envoymobile/engine/JvmBridgeUtilityTest.kt

coverage: fix warning in JvmBridgeUtilityTest

---

docs/root/development/testing/local_stats.rst

docs: added clarification

---

library/kotlin/src/io/envoyproxy/envoymobile/BUILD
library/kotlin/src/io/envoyproxy/envoymobile/RequestTrailers.kt
library/kotlin/src/io/envoyproxy/envoymobile/ResponseTrailers.kt
library/kotlin/src/io/envoyproxy/envoymobile/Trailers.kt
library/kotlin/src/io/envoyproxy/envoymobile/filters/FilterResumeStatus.kt
library/kotlin/src/io/envoyproxy/envoymobile/filters/FilterTrailersStatus.kt
library/swift/src/BUILD
library/swift/src/RequestTrailers.swift
library/swift/src/ResponseTrailers.swift
library/swift/src/Trailers.swift
library/swift/src/filters/FilterResumeStatus.swift
library/swift/src/filters/FilterTrailersStatus.swift

Description: Allows for better scoping of header types; in this case, specifically for advanced filters.
Testing: CI

platform: add Trailers type for better classification

---

library/common/types/c_types.h

Description: And some general cleaup of callback documentation.
Testing: CI

documentation: clarify role of terminal callbacks

---

library/objective-c/EnvoyEngine.h

objc: block properties should be copy, not strong

---

test/common/extensions/filters/http/platform_bridge/platform_bridge_filter_test.cc

Description: Adds initial coverage.

filters: add basic unit tests for PlatformBridgeFilter

---

test/common/extensions/filters/http/platform_bridge/platform_bridge_filter_test.cc

filters: add to_string helper in tests

---

test/common/extensions/filters/http/platform_bridge/platform_bridge_filter_test.cc

filters: test null and noop filters

---

test/common/extensions/filters/http/platform_bridge/platform_bridge_filter_test.cc

filters: add coverage for onDestroy and release_filter

---

library/common/jni/jni_interface.cc

Per request in https://github.com/lyft/envoy-mobile/pull/1087#discussion_r489746938.

core: add clarifying comment

---

test/common/extensions/filters/http/assertion/BUILD
test/common/extensions/filters/http/assertion/assertion_filter_test.cc

Description: assertion filter - add config coverage
Testing: added unit tests

assertion filter: add config coverage

---

ci/test_size_regression.sh
envoy_build_config/BUILD
envoy_build_config/extension_registry.cc
envoy_build_config/extension_registry.h
envoy_build_config/extensions_build_config.bzl
library/common/http/dispatcher.cc
library/common/http/dispatcher.h
library/common/main_interface.h
library/common/network/synthetic_address_impl.h
test/common/BUILD
test/common/main_interface_test.cc

Description: adds explicit tests for main interface functions.
Testing: add new integration style tests for the main interface static functions.

test: add tests around main interface

---

test/common/http/dispatcher_test.cc
test/common/main_interface_test.cc
test/common/network/synthetic_address_impl_test.cc

Description: add areas of missing coverage across the core codebase.
Testing: adds more testing!

core: add missing coverage

---

library/common/engine.cc

Description: Ensure stat names passed into the public interface pass internal validity checks.
Testing: CI

stats: sanitize incoming stat names

---

library/common/engine.cc

bugfix: fix stack-use-after-scope with stat name

---

test/common/extensions/filters/http/platform_bridge/platform_bridge_filter_test.cc

cleanup: use modern initialization for structs in unit test

---

library/common/extensions/filters/http/assertion/filter.cc

assertion filter: formatting; fix case for local var

---

.swiftlint.yml

swiftlint: bump target version

---

library/common/engine.cc
library/common/engine.h
library/common/main_interface.cc
library/java/src/io/envoyproxy/envoymobile/engine/AndroidEngineImpl.java
library/java/src/io/envoyproxy/envoymobile/engine/EnvoyEngine.java
library/java/src/io/envoyproxy/envoymobile/engine/EnvoyEngineImpl.java
library/java/src/io/envoyproxy/envoymobile/engine/JniLibrary.java
library/kotlin/src/io/envoyproxy/envoymobile/mocks/MockEnvoyEngine.kt
library/kotlin/src/io/envoyproxy/envoymobile/stats/CounterImpl.kt
library/kotlin/test/io/envoyproxy/envoymobile/StatsClientImplTest.kt
library/objective-c/EnvoyEngine.h
library/objective-c/EnvoyEngineImpl.m
library/swift/src/mocks/MockEnvoyEngine.swift
library/swift/src/stats/CounterImpl.swift

Description: Update the method names of counters to follow the same convention as `Gauge`.
Risk Level: Medium, the change itself is minimal, but it is a breaking change for callers of the methods.
Testing: Unit tests

stats: update method names of counter

---

library/common/http/dispatcher.h

dispatcher: fix incorrect comment

---

EnvoyMobile.podspec

distribution: update podspec to match release

---

examples/swift/hello_world/AsyncDemoFilter.swift
examples/swift/hello_world/DemoFilter.swift
examples/swift/hello_world/ViewController.swift

Description: Adds a filter to the swift example app that pauses the response and then asynchronously resumes it via callbacks.
Testing: Local

examples: add AsyncDemoFilter to swift example app

---

docs/root/api/stats.rst

Add doc for `Gauge` APIs introduced in https://github.com/lyft/envoy-mobile/pull/1117.

doc: add gauge apis

---

library/common/extensions/filters/http/platform_bridge/filter.cc

filters: add trace logging to PlatformBridgeFilter

---

examples/swift/hello_world/BufferDemoFilter.swift
examples/swift/hello_world/ViewController.swift

filters: add buffer demo filter to swift

---

examples/swift/hello_world/BufferDemoFilter.swift

examples: minor fix to swift example filter

---

library/common/extensions/filters/http/platform_bridge/filter.cc

filters: fix minor typo in comment

---

library/java/src/io/envoyproxy/envoymobile/engine/JniBridgeUtility.java
library/java/src/io/envoyproxy/envoymobile/engine/JvmFilterContext.java
library/kotlin/src/io/envoyproxy/envoymobile/filters/Filter.kt

Description: Adds additional java context layer mapping needed to transform headers.
Testing: Local and CI (#1163)

filters: fix kotlin status mapping

---

examples/kotlin/hello_world/BUILD
examples/kotlin/hello_world/BufferDemoFilter.kt
examples/kotlin/hello_world/MainActivity.kt

examples: add BufferFilterDemo to kotlin app

---

examples/kotlin/hello_world/AsyncDemoFilter.kt
examples/kotlin/hello_world/BUILD
examples/kotlin/hello_world/MainActivity.kt

examples: add AsyncDemoFilter to kotlin app

---

library/common/jni/jni_interface.cc

jni: fix stats method name

---

.github/workflows/core.yml

ci: increase asan job timeout

---

.bazelrc
ci/mac_ci_setup.sh
docs/root/start/building/building.rst

build: update Xcode to 12.2

---

library/common/config_template.cc

config: increase default connection buffer limit to 10MB

---

library/common/jni/jni_interface.cc

cleanup: remove some erroneously-added dead code

---

bazel/envoy_mobile_repositories.bzl

update to envoy to 588d9344b

---

library/java/src/io/envoyproxy/envoymobile/engine/JvmFilterContext.java

documentation: add missing docstrings in JvmFilterContext

---

library/common/extensions/filters/http/assertion/config.h
library/common/extensions/filters/http/platform_bridge/c_type_definitions.h
library/common/extensions/filters/http/platform_bridge/config.h
library/common/jni/jni_utility.h
library/common/jni/jni_version.h
library/common/main_interface.h

build: add missing pragma once to several headers

---

envoy_build_config/BUILD
envoy_build_config/extension_registry.cc
envoy_build_config/extension_registry.h
envoy_build_config/extensions_build_config.bzl
library/common/extensions/filters/http/platform_bridge/c_types.h
library/common/extensions/filters/http/platform_bridge/filter.cc
library/objective-c/EnvoyEngine.h
library/objective-c/EnvoyEngineImpl.m
library/swift/src/filters/Filter.swift
library/swift/test/HttpBridgeTests/CancelStreamTest.swift

Description: Also includes iOS wiring for on-error invocation path.
Testing: Integration and unit tests, CI and local

filters: add core and iOS support for on-cancel invocations

---

library/common/extensions/filters/http/platform_bridge/filter.cc

filters: add extra context in trace logging

---

library/common/jni/jni_interface.cc

jni: fix cleanup on terminal callbacks

---

library/cc/BUILD
library/cc/engine.cc
library/cc/engine.h
library/cc/engine_builder.cc
library/python/BUILD
library/python/engine_builder_shim.cc
library/python/engine_builder_shim.h
library/python/module_definition.cc

**Description:**
All header changes in this PR come from https://github.com/envoyproxy/envoy-mobile/pull/1217, that should be reviewed and merged first.
This PR implements all of the engine-related classes, like `Engine` and `EngineBuilder`.
**Risk Level:** Low
**Testing:** N/A, will follow up when everything is finished with e2e testing + unit testing in Python and/or C++
**Docs Changes:** N/A
**Release Notes:** N/A

python: engine implementation

---

ci/test_size_regression.sh

Description: pull envoy 8e2286b for https://github.com/envoyproxy/envoy/pull/14887 to fix ci
Testing: ci
Signed-off-by: Jingwei Hao <jingweih@lyft.com>

pull envoy 8e2286b

---

.github/workflows/core.yml
.github/workflows/ios.yml
.github/workflows/perf.yml

Description: I have noticed timing out on main and in PRs

ci: increase timeouts

---

bazel/swift_static_framework.bzl

This tool was meant to be a bazel implementation detail so its public
accessor was removed in https://github.com/bazelbuild/bazel/commit/f8b51ffc2a8a953f64657ae4a21c9e1f1793dae2
Using the cc API from bazel we can dynamically get this. This is still a
bit of a hack because we're writing our own args for this. We might be
able to fetch the args, based on bazel's crosstool, dynamically as well,
but ideally we remove this rule instead.
Fixes https://github.com/envoyproxy/envoy-mobile/issues/1233

build: fix libtool label for bazel 3.7+

---

test/common/extensions/filters/http/platform_bridge/BUILD
test/common/extensions/filters/http/platform_bridge/platform_bridge_filter_integration_test.cc

Description: introduces integration test harness for the platform bridge filter that enables testing scenarios with multiple filters, and their interactions with the filter manager. Additionally, it introduces a test case for a current crashing behavior. Subsequent PR will fix and uncomment the test.
Risk Level: low - introduce new testing infrastructure.
Testing: new test framework, but with commented out test case.

platform bridge: integration tests

---

.bazelrc
ci/mac_ci_setup.sh
docs/root/start/building/building.rst

Update Xcode to 12.4

---

library/common/certificates.inc

Description: Syncs with OpenBSD/LibreSSL.
Risk Level: High
Testing: Local

tls: update bundled root certificates

---

.bazelrc
.github/workflows/coverage.yml
docs/root/development/testing/testing.rst

docs: additional documentation on coverage runs

---

.pre-commit-config.yaml

format: exclude .clang_format from check-yaml precommit hook

---

library/common/jni/jni_utility.cc

Description: noticed this duplication while working on a different PR.
Risk Level: low - identical code, just dispatched as function.
Testing: builds - runs example app with successful headers.

jni utility: clean up duplicated code array_to_native_data

---

.pre-commit-config.yaml
README.md

format: fix precommit

---

library/common/jni/jni_interface.cc

Description: fixes memory leak per comment in https://github.com/envoyproxy/envoy-mobile/pull/1305/files#r595575188
Risk Level: med
Testing: local repro

memory leak: fix jni memory leak on resume filter

---

docs/root/api/stats.rst

Description: Small addition to the stats intro where I added mentions for Timer and Distribution
Signed-off-by: Miguel Juarez mjuarezlopez@lyft.com

docs: update the intro to include histogram

---

docs/requirements.txt

Description: Resolves a security issue flagged by GitHub.
Testing: CI

docs: update jinja2 dependency

---

docs/requirements.txt

docs: update Pygments dependency

---

.github/workflows/ios.yml

ci: log app run if job failed or cancelled

---

.github/workflows/android_apps.yml
.github/workflows/android_build.yml
.github/workflows/android_tests.yml

Description: Testing staged CI workflow to allow retrying stages. Must be merged to main to trigger workflow events.
Testing: In progress

ci: test staged ci workflow

---

examples/java/hello_world/MainActivity.java
examples/kotlin/hello_world/MainActivity.kt
examples/objective-c/hello_world/ViewController.m
examples/swift/hello_world/ViewController.swift

examples: add baseline debug logging to example apps

---

library/common/BUILD
library/common/engine.cc
library/common/engine.h
library/common/jni/jni_interface.cc
library/common/main_interface.cc
library/common/main_interface.h
library/common/types/c_types.h
library/objective-c/EnvoyEngineImpl.m
test/common/engine_test.cc
test/common/main_interface_test.cc

Description: exposes new functionality in the bridge layer that will leverage #1354.
Testing: updated tests

logging: expose envoy_logging_callbacks

---

test/performance/test_binary_size.cc

test: fix perf test with broken API usage

---

test/common/main_interface_test.cc

Description: fixes failure introduced in #1354.
Testing: original PR did not show failure. But main test run did.

tsan: fix failure in main_interface_test

---

docs/root/api/starting_envoy.rst
library/common/common/lambda_logger_delegate.cc
library/common/engine.cc
library/common/jni/jni_interface.cc
library/common/types/c_types.h
library/objective-c/BUILD
library/objective-c/EnvoyBridgeUtility.h
library/objective-c/EnvoyEngine.h
library/objective-c/EnvoyEngineImpl.m
library/objective-c/EnvoyLogger.m
library/swift/EngineBuilder.swift
library/swift/EngineImpl.swift
library/swift/mocks/MockEnvoyEngine.swift
test/common/common/lambda_logger_delegate_test.cc
test/common/main_interface_test.cc
test/swift/integration/BUILD
test/swift/integration/SetLoggerTest.swift

Description: iOS API for supporting #1355 
Testing: example apps. Pending e2e tests when all PRs land.

logging: ios API for callback logging

---

library/java/io/envoyproxy/envoymobile/engine/AndroidEngineImpl.java
library/kotlin/io/envoyproxy/envoymobile/AndroidEngineBuilder.kt

Description: android: update engine to take context
Testing: ci

android: update engine to take context

---

docs/root/development/testing/testing.rst

docs: update swift tests instructions

---

library/java/org/chromium/net/LICENSE

cronet binding: add upstream Chromium license

---

.bazelrc

build: add tsan-dev config

---

.bazelrc

dev: update tsan-dev

---

library/common/extensions/filters/http/platform_bridge/filter.cc

platform bridge: add additional debug logging on async resume

---

examples/swift/hello_world/ViewController.swift

examples: fix swift app

---

docs/root/intro/version_history.rst

docs: fix spacing

---

library/common/event/BUILD
library/common/event/provisional_dispatcher.h

dispatcher: clean up unused dependencies

---

.github/workflows/android_tests.yml

Description: ci: fix kotlin/java tests 
Testing: ci

ci: fix kotlin/java tests

---

.github/workflows/asan.yml
.github/workflows/tsan.yml

ci: add additional checks for asan/tsan workflows

---

library/cc/engine_builder.cc
library/common/jni/jni_interface.cc
library/common/types/c_types.cc
library/common/types/c_types.h
library/objective-c/EnvoyEngineImpl.m
test/common/common/lambda_logger_delegate_test.cc
test/common/main_interface_test.cc

build: fix compilation warnings from envoy_logger

---

.pre-commit-config.yaml
bazel/swift_test.bzl
experimental/swift/BUILD
experimental/swift/QUICStreamTest.swift
tools/check_format.sh

Description: Introduces an end-to-end test that successfully sends a request and receives a response over the local network with QUIC/H3, originating in the public iOS library API and exercising all layers of the stack.
Testing: Local

quic: introduce working e2e test

---

library/common/config_template.cc

Description: An alternate keepalive approach.
Testing: In progress.

config: update keepalive settings

---

library/cc/response_headers_builder.cc
library/cc/response_trailers_builder.cc
library/common/engine.h
library/common/extensions/filters/http/assertion/filter.h
library/common/extensions/filters/http/platform_bridge/filter.h
library/common/extensions/filters/http/test_accessor/filter.h
library/common/main_interface.cc
test/common/integration/client_integration_test.cc

Description: inspired by https://github.com/envoyproxy/envoy-mobile/pull/1433 audited the rest of missing definitions.

smart pointers: define using statements for all smart pointer usage

---

library/kotlin/io/envoyproxy/envoymobile/StreamPrototype.kt
test/kotlin/integration/BUILD
test/kotlin/integration/ReceiveDataTest.kt
test/swift/integration/ReceiveDataTest.swift

Description: kotlin: add receive data test
Testing: unit

kotlin: add receive data test

---

test/kotlin/integration/BUILD
test/kotlin/integration/SendDataTest.kt

Description: kotlin: add send data test
Testing: unit

kotlin: add send data test

---

test/kotlin/integration/BUILD
test/kotlin/integration/SendTrailersTest.kt
test/swift/integration/SendTrailersTest.swift

Description: kotlin: add send trailers test
Testing: integration

kotlin: add send trailers test

---

docs/root/api/stats.rst

docs: add docs for pulse custom tags

---

.github/workflows/python_tests.yml

Description: Conditionally run python tests based on whether changes exist to the python, cc, or core layers of the library. Build and Envoy changes will also trigger runs.
Testing: CI

ci: conditionally run python tests

---

docs/root/api/starting_envoy.rst

docs: update documentation for addSteamIdleTimeoutSeconds

---

library/swift/stats/TagsBuilder.swift

Description: make TagsBuilder initializer public 
Risk Level: low 
Testing: unit/ci

stats: make TagsBuilder initializer public

---

docs/root/start/building/building.rst

Adds some detail around what environment variables to set for a local development environment

docs: add more detail to build requirements/setup

---

docs/root/api/stats.rst
examples/java/hello_world/MainActivity.java
examples/kotlin/hello_world/MainActivity.kt
examples/objective-c/hello_world/ViewController.m
examples/swift/hello_world/ViewController.swift
library/kotlin/io/envoyproxy/envoymobile/stats/Timer.kt
library/kotlin/io/envoyproxy/envoymobile/stats/TimerImpl.kt
library/swift/stats/Timer.swift
library/swift/stats/TimerImpl.swift
test/kotlin/io/envoyproxy/envoymobile/PulseClientImplTest.kt
test/swift/PulseClientImplTests.swift

Description: update method (function) names of `Timer`
Testing: unit/ci
Docs Changes: updated 

stats: update method names for Timer

---

library/common/http/client.h

envoy: b4a3854 for config templating

---

library/java/io/envoyproxy/envoymobile/engine/EnvoyEngineImpl.java

java: simple factoring of duplicate config code

---

test/swift/integration/CancelStreamTest.swift
test/swift/integration/GRPCReceiveErrorTest.swift
test/swift/integration/ReceiveDataTest.swift
test/swift/integration/ReceiveErrorTest.swift
test/swift/integration/SendDataTest.swift
test/swift/integration/SendHeadersTest.swift
test/swift/integration/SendTrailersTest.swift
test/swift/integration/SetLoggerTest.swift

Description: This makes it easier to track discrepancies and avoid inadvertent errors.
Testing: CI

config: zero-align all config string literals for consistency

---

library/objective-c/EnvoyConfiguration.m

cast fix: incorrect cast in EnvoyConfiguration.m

---

envoy_build_config/BUILD
library/common/config/config.cc

Brings in https://github.com/envoyproxy/envoy/pull/17179

update envoy: f2906f5ce37281 & skip waiting on stats cluster warmup

---

library/java/org/chromium/net/impl/CronetUrlRequest.java
test/java/org/chromium/net/CronetUrlRequestTest.java

Description: Conclusion for two tests requiring more investigation
Testing: yes

Resolve @Ignored("Debug me") tests in CronetUrlRequestTest

---

docs/root/api/starting_envoy.rst

Docs Changes: adding missing docs

docs: add docs for addDNSPreresolveHostnames

---

library/common/config/config.cc

Includes three relevant commits:
https://github.com/envoyproxy/envoy/pull/17226
https://github.com/envoyproxy/envoy/pull/17274
https://github.com/envoyproxy/envoy/pull/17207

envoy: 3876d7c0f

---

test/common/extensions/filters/http/assertion/BUILD
test/common/extensions/filters/http/platform_bridge/BUILD
test/common/extensions/stat_sinks/metrics_service/BUILD

envoy: bump upstream for connection pool fix

---

envoy_build_config/extension_registry.h
library/common/config/config.cc

Propercasing both request and response path for the ALPN pool
Risk Level: low (alpn-pool only)
Testing: n/a
Fixes #1558

propercasing take two

---

docs/root/start/building/building.rst

docs: add attention to force registration of extensions

---

library/common/types/c_types.cc
library/common/types/c_types.h

bridge: cleanup of c_types functions

---

OWNERS.md

Description: we have had some more participants since this was first written. Updating to include people.

OWNERS: spruce up list

---

.github/workflows/ios_tests.yml

ci: fix workflow name

---

test/common/common/lambda_logger_delegate_test.cc
test/common/data/utility_test.cc
test/common/extensions/filters/http/platform_bridge/platform_bridge_filter_integration_test.cc
test/common/extensions/filters/http/platform_bridge/platform_bridge_filter_test.cc
test/common/http/client_test.cc
test/common/integration/client_integration_test.cc
test/common/main_interface_test.cc

Description: Noticed these needed to be updated.
Testing: CI

core: use new release calls in test

---

.github/workflows/artifacts.yml

For fixing: https://github.com/envoyproxy/envoy-mobile/issues/1651
Description: ci: fix release pom versions
Testing: n/a

ci: fix release pom versions

---

OWNERS.md

Description: owners: add snowp to maintainers list
Risk Level: n/a
Testing: n/a

owners: add snowp to maintainers list

---

.github/workflows/android_build.yml

ci: shorten Android example timeouts

---

.bazelrc

Description:
Add more clear description to bazelrc options for CI and remote execution.
Testing: No-op (comments only)

CI: Add a more clear description to bazelrc options for CI and Remote execution

---

library/common/http/client.cc
library/common/http/client.h
test/common/http/client_test.cc

Description: Populates initial fields of StreamIntel with values from the underlying stream on each callback.

http: plug in StreamIntel

---

.github/workflows/android_build.yml

ci: increase Android example app timeouts due to flakiness

---

examples/swift/hello_world/AsyncDemoFilter.swift
examples/swift/hello_world/BufferDemoFilter.swift
examples/swift/hello_world/DemoFilter.swift
library/swift/filters/AsyncRequestFilter.swift
library/swift/filters/AsyncResponseFilter.swift
library/swift/filters/Filter.swift
library/swift/filters/RequestFilter.swift
library/swift/filters/ResponseFilter.swift
test/swift/integration/CancelStreamTest.swift
test/swift/integration/DemoFilter.swift
test/swift/integration/DirectResponseFilterMutationIntegrationTest.swift
test/swift/integration/FilterResetIdleTest.swift
test/swift/integration/GRPCReceiveErrorTest.swift
test/swift/integration/ReceiveErrorTest.swift

Description: Updates iOS filter interfaces to support receiving StreamIntel on callbacks. Underlying data is not yet populated.
Docs Changes: Pending

filters: expose StreamIntel for iOS filters

---

examples/kotlin/hello_world/AsyncDemoFilter.kt
examples/kotlin/hello_world/BufferDemoFilter.kt
examples/kotlin/hello_world/DemoFilter.kt
examples/kotlin/hello_world/MainActivity.kt
library/kotlin/io/envoyproxy/envoymobile/BUILD
library/kotlin/io/envoyproxy/envoymobile/StreamCallbacks.kt
library/kotlin/io/envoyproxy/envoymobile/StreamIntel.kt
library/kotlin/io/envoyproxy/envoymobile/filters/AsyncRequestFilter.kt
library/kotlin/io/envoyproxy/envoymobile/filters/AsyncResponseFilter.kt
library/kotlin/io/envoyproxy/envoymobile/filters/Filter.kt
library/kotlin/io/envoyproxy/envoymobile/filters/RequestFilter.kt
library/kotlin/io/envoyproxy/envoymobile/filters/ResponseFilter.kt
library/kotlin/io/envoyproxy/envoymobile/mocks/MockStream.kt
test/kotlin/integration/CancelStreamTest.kt
test/kotlin/integration/GRPCReceiveErrorTest.kt
test/kotlin/integration/ReceiveErrorTest.kt

Description: Updates Android filter interfaces to support receiving StreamIntel on callbacks. Underlying data is not yet populated.
Docs Changes: Pending

filters: expose StreamIntel for Android filters

---

library/common/extensions/filters/http/platform_bridge/c_types.h
library/common/extensions/filters/http/platform_bridge/filter.cc
library/common/extensions/filters/http/platform_bridge/filter.h
library/common/jni/jni_interface.cc
library/java/io/envoyproxy/envoymobile/engine/JvmFilterContext.java
library/java/io/envoyproxy/envoymobile/engine/types/EnvoyHTTPFilter.java
library/kotlin/io/envoyproxy/envoymobile/filters/Filter.kt
library/objective-c/EnvoyEngine.h
library/objective-c/EnvoyEngineImpl.m
library/swift/filters/Filter.swift
test/common/extensions/filters/http/platform_bridge/platform_bridge_filter_test.cc

Description: Populates initial fields of StreamIntel with values from the underlying stream in platform filter callbacks.

filters: wire StreamIntel for platform filters

---

library/common/config/config.cc

Description: Compile out inline config comments.
Testing: CI

config: compile out inline config comments

---

library/cc/engine.cc

cc: clean up uses of this in engine.cc

---

library/common/main_interface.h

main interface: add missing docstring for terminate

---

test/python/unit/test_basics.py

includes: https://github.com/envoyproxy/envoy/pull/17775 and https://github.com/envoyproxy/envoy/pull/17780

envoy:  26dae5d6542

---

test/swift/integration/SetEventTrackerTestNoTracker.swift

test: temporarily disable test with invalid remote

---

library/common/jni/jni_interface.cc

jni: clean up several instances of unused jclass refs

---

test/python/unit/test_basics.py

python test: fix error match in unit test

---

test/common/main_interface_test.cc

https://github.com/envoyproxy/envoy-mobile/pull/1761 with fixed formatting in tests.
Description: Only works on iOS and Android API >= 24 currently.

core: log and emit event listing available network interfaces

---

NOTICE

license: update notice

---

library/common/config/config.cc
test/java/org/chromium/net/CronetUrlRequestTest.java

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:

extending propercasing to the last missed cluster

---

.bazelrc
.github/workflows/android_build.yml
.github/workflows/android_tests.yml
.github/workflows/artifacts.yml
.github/workflows/core.yml
.github/workflows/format.yml
.github/workflows/ios_build.yml
.github/workflows/ios_tests.yml
ci/BUILD
ci/mac_ci_setup.sh
docs/root/start/building/building.rst

bazel: update to Xcode 12.5.1

---

library/common/config/config.cc

config: add protocol options to h2 clusters

---

envoy_build_config/extensions_build_config.bzl

envoy: update upstream to 44bcb12

---

examples/kotlin/hello_world/MainActivity.kt
library/proguard.txt

Description: Add EnvoyLogger to proguard exlcusion 
Testing: hello world test

Add EnvoyLogger to proguard exlcusion

---

library/kotlin/io/envoyproxy/envoymobile/PulseClient.kt
library/kotlin/io/envoyproxy/envoymobile/PulseClientImpl.kt
library/swift/PulseClient.swift
library/swift/PulseClientImpl.swift

Description: Adding public logging API for kotlin and swift. The API does not function at the moment.
Testing: ci
Docs Changes: Will add docs when the API is wired up and start fuctioning

Add logging public api

---

library/kotlin/io/envoyproxy/envoymobile/PulseClient.kt
library/kotlin/io/envoyproxy/envoymobile/PulseClientImpl.kt
library/swift/PulseClient.swift
library/swift/PulseClientImpl.swift

Reverts envoyproxy/envoy-mobile#1823
according to recent discussions

Revert "Add logging public api"

---

library/java/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java
library/java/org/chromium/net/impl/NativeCronetEngineBuilderImpl.java
library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt
library/objective-c/EnvoyConfiguration.m
library/objective-c/EnvoyEngine.h
library/swift/EngineBuilder.swift
test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt
test/swift/EngineBuilderTests.swift

Description: Provides public API to configure interface binding; disabled by default.
Testing: Updated tests & CI

network: allow interface binding to be configured in programmatic API

---

library/common/network/configurator.cc

network: add some additional instrumentation to dns refresh

---

test/common/network/BUILD
test/common/network/configurator_test.cc

network: add basic unit coverage for dns refresh

---

library/common/jni/jni_support.h

Description: declare functions as c functions (as opposed to c++ functions)
Testing: ci

make functions as c functions

---

library/common/common/lambda_logger_delegate.cc
library/common/common/lambda_logger_delegate.h

envoy: 7351734f60

---

library/common/http/client.h
test/common/http/client_test.cc

envoy: 3b27d1d34f282

---

library/common/network/configurator.cc

network: filter alt interfaces for binding by well-known prefixes

---

.github/workflows/perf.yml
ci/mac_ci_setup.sh

I couldn't change these in the original PR since it relied on the main
branch having this file too.

ci: Change last bazel references to bazelw

---

library/common/extensions/filters/http/network_configuration/filter.cc
library/common/extensions/filters/http/platform_bridge/filter.cc
library/common/extensions/retry/options/network_configuration/predicate.cc
library/common/http/BUILD
library/common/http/client.cc
library/common/http/client.h

https://github.com/envoyproxy/envoy/compare/23e5fc2939e1782416155509edfca323150e8a59...eb39110eca961af1ee8147a1cbb373c6cced247d

Bumping Envoy to 247deb39110eca961af1ee8147a1cbb373c6cced247d

---

library/common/extensions/filters/http/platform_bridge/BUILD
library/common/extensions/filters/http/platform_bridge/filter.cc
library/common/http/BUILD
library/common/http/client.cc
library/common/http/client.h
library/common/stream_info/BUILD
library/common/stream_info/extra_stream_info.cc
library/common/stream_info/extra_stream_info.h
test/common/http/client_test.cc
test/common/stream_info/BUILD
test/common/stream_info/extra_stream_info_test.cc

coauthered-by: carloseltuerto 
Most of https://github.com/envoyproxy/envoy-mobile/issues/1520

Various fixes to final stream intel to send in all cases

---

library/common/http/client.cc
library/common/http/client.h

envoy: 8c66c42eb9

---

library/common/config/config.cc
library/objective-c/EnvoyConfiguration.m

Needed in order to have the default configuration be type constraint from Any

dns typed config: add @type field

---

test/java/org/chromium/net/BUILD

Description: undo pr1980
Risk Level: N/A
Testing: N/A

Re-enable Cronet test

---

docs/root/api/starting_envoy.rst

docs: missing EngineBuilder documentation

---

test/kotlin/io/envoyproxy/envoymobile/EngineBuilderTest.kt
test/swift/EngineBuilderTests.swift

tests: add missing EngineBuilder tests

---

docs/root/intro/version_history.rst

version history: add missing v0.4.2 release notes

---

docs/root/intro/version_history.rst

version history: add v0.4.3 release notes

---

library/common/http/client.cc
library/common/http/header_utility.cc
library/common/http/header_utility.h
test/common/http/header_utility_test.cc

part of https://github.com/envoyproxy/envoy-mobile/issues/1546

adding alpn as a response header

---

library/common/http/client.cc

https://github.com/envoyproxy/envoy-mobile/pull/1969 and https://github.com/envoyproxy/envoy-mobile/pull/1965/files didn't merge conflict but test-conflicted.

fixing a bad merge

---

docs/root/intro/comparison.rst

Description: Fix documentation typo
Testing: N/A
Docs Changes: typo fix

Fix typo of mvfst in docs

---

bazel/pom_template.xml

pom: Update developers in pom xml file

---

library/common/extensions/filters/http/platform_bridge/filter.cc
test/common/extensions/stat_sinks/metrics_service/mobile_grpc_streamer_integration_test.cc

fixing merge for https://github.com/envoyproxy/envoy/pull/19959

macro removal

---

.github/actions/pr_notifier/pr_notifier.py
.github/lyft_maintainers.yml
OWNERS.md
bazel/pom_template.xml

Introduce a new owner @Augustyniak who is going to replace an existing owner @buildbreaker.
Description:
Testing: N/A

ci: Augustyniak for buildbreaker

---

README.md

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:

docs: adding the community meeting

---

OWNERS.md

owners: move junr03 to emeritus

---

.github/lyft_maintainers.yml

support rotation: remove junr03

---

bazel/flatbuffers.bzl

The generated code couldn't be used with private_deps because it
imported FlatBuffers normally and created a bunch of public types.
Ideally this would be an option to the generator instead of doing this.
This will have to be updated to a loop to support multiple input files

bazel: Add flatbuffers Swift hack

---

bazel/envoy_mobile_repositories.bzl

rules_apple diff: https://github.com/bazelbuild/rules_apple/compare/d1d40821dc932ee488eb22c0b9712e26f39c04fa...0.34.0
rules_swift diff: https://github.com/bazelbuild/rules_swift/compare/a81f40700f1ba45034465a82673f46bd2631be62...0.27.0
Testing: Existing

Update rules_apple & rules_swift

---

envoy_build_config/BUILD
envoy_build_config/extension_registry.cc

build: add missing registration of APC extension

---

library/common/http/client.cc

rollback #2193

---

.github/workflows/release.yml
docs/root/development/releasing/releasing.rst

Create a GitHub Release, uploading the build artifacts, and deploy to CocoaPods.
Addresses #624.

Automate more of the release process

---

.github/workflows/bump_support_rotation.yml
tools/bump_lyft_support_rotation.sh

Post to the [#envoy-mobile-collaboration](https://envoyproxy.slack.com/archives/C02F93EEJCE) channel.

support: Post Lyft support rotation changes to Slack

---

test/swift/EngineBuilderTests.swift

cleanup: fix test with inaccurate description

---

test/common/network/configurator_test.cc

Description: Just makes the test a little more comprehensive. Had this as stashed state from my local testing of the feature and missed including it.
Testing: Included

test: refine connection drain test

---

bazel/envoy_mobile_repositories.bzl

Upgrading rules_jvm_external from 4.1 -> 4.2
Signed-off-by: Benjamin Lee <ben@ben.cm>

Upgrade rules_jvm_external from 4.1 -> 4.2

---

test/common/integration/client_integration_test.cc

Part of https://github.com/envoyproxy/envoy-mobile/issues/2192

test: adding a cancel test, cleaning up copy-paste code

---

tools/vscode_compdb.sh

Follow-up to https://github.com/envoyproxy/envoy-mobile/pull/2277.

tools: use `bazelw` bazel wrapper in `vscode_compdb.sh`

---

.github/workflows/submodule_update.yml

As suggested in https://github.com/envoyproxy/envoy-mobile/pull/2282#pullrequestreview-975923246

ci: assign support maintainer as a reviewer for Envoy bump PRs

---

.github/workflows/bump_support_rotation.yml
tools/bump_lyft_support_rotation.sh
tools/post_to_slack.sh

And include the PR URL in the Slack message

ci: assign support rotation bump PRs to the next maintainer

---

.github/workflows/release.yml

The value was set at the wrong level, it needs to be nested in the `with:`.

Fix release GitHub workflow

---

test/kotlin/integration/ReceiveErrorTest.kt

Discussion: https://envoyproxy.slack.com/archives/C02F93EEJCE/p1653485522681549

kotlin: fix flaky receive error test

---

.github/workflows/release.yml
bazel/envoy_mobile_repositories.bzl

To pull in https://github.com/bazelbuild/rules_apple/pull/1484
```
du -h bazel-bin/library/swift/Envoy.xcframework.zip
366M	bazel-bin/library/swift/Envoy.xcframework.zip
```

bazel: update rules_apple

---

docs/root/intro/version_history.rst
library/cc/engine_builder.cc
library/cc/engine_builder.h
library/common/config/config.cc
library/common/config/templates.h
library/common/jni/jni_interface.cc
library/java/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java
library/java/io/envoyproxy/envoymobile/engine/EnvoyEngineImpl.java
library/java/io/envoyproxy/envoymobile/engine/JniLibrary.java
library/java/org/chromium/net/impl/NativeCronetEngineBuilderImpl.java
library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt
test/cc/unit/envoy_config_test.cc
test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt
test/java/org/chromium/net/BrotliTest.java

Adding the option to configure brotli in the bulder
Risk Level: low off by default
Testing: cc unit tests, updated java tests
Release Notes: inline

Adding knobs to configure brotli

---

library/objective-c/EnvoyEngineImpl.m

cleanup: remove unused function and resolve warning

---

library/common/jni/jni_utility.cc

Description: Did a search and found a few more of these to clean up.
Risk: Low
Testing: CI

cleanup: convert some more uses of NULL to nullptr

---

library/common/jni/jni_utility.cc

cleanup: fix warning in JNI layer

---

.github/workflows/release.yml

iOS: fix xcframework upload in release workflow

---

library/common/config/config.cc

As suggested in https://github.com/envoyproxy/envoy-mobile/pull/2367#issuecomment-1156538132

config: add additional comment to `disallow_global_stats`

---

bazel/envoy_mobile_repositories.bzl

bazel: bump rules_apple and rules_swift to latest releases

---

library/objective-c/EnvoyEngineImpl.m
test/swift/integration/BUILD
test/swift/integration/KeyValueStoreTest.swift

Description: Also adds new end-to-end test coverage.
Testing: New e2e coverage.

ios: fix missing registration for KV store

---

ci/mac_ci_setup.sh

Fixes https://github.com/envoyproxy/envoy-mobile/issues/2443

ci: fix Android environment

---

test/cc/integration/lifetimes_test.cc
test/cc/integration/send_headers_test.cc

Description: Makes these more readable, and easier to validate.
Testing: CI

tests: use raw string literals in cc integration tests

---

test/java/integration/AndroidEnvoyExplicitFlowTest.java
test/java/integration/AndroidEnvoyFlowTest.java
test/java/integration/BUILD
test/java/io/envoyproxy/envoymobile/engine/testing/BUILD
test/java/io/envoyproxy/envoymobile/engine/testing/QuicTestServerTest.java
test/java/io/envoyproxy/envoymobile/engine/testing/RequestScenario.java
test/java/io/envoyproxy/envoymobile/engine/testing/Response.java

Factor out RequestScenario and Response from test/java/integration
Risk Level: None - Test-only

Factor out RequestScenario and Response from test/java/integration

---

.github/actions/retest-action/Dockerfile

Follow-up to https://github.com/envoyproxy/envoy-mobile/pull/2478.

ci: install bash in docker image for retest action

---

.github/actions/retest-action/entrypoint.sh

Discussion: https://envoyproxy.slack.com/archives/CKQ2LK23G/p1660773611243599

ci: also rerun cancelled & timed out jobs on `/retest`

---

test/java/org/chromium/net/BidirectionalStreamTest.java
test/java/org/chromium/net/CronetUrlRequestContextTest.java
test/java/org/chromium/net/testing/CronetTestRule.java
test/java/org/chromium/net/testing/CronetTestRuleTest.java
test/java/org/chromium/net/urlconnection/CronetFixedModeOutputStreamTest.java

Description: These changes are prerequisite for
https://github.com/envoyproxy/envoy-mobile/issues/1549
Signed-off-by: Chidera Olibie <colibie@google.com>
Testing: Cronvoy test

Cronvoy: Update CronetTestRule with Cronet changes

---

.pre-commit-config.yaml
test/kotlin/io/envoyproxy/envoymobile/FlatBuffersTest.kt

test: fix Kotlin FlatBuffersTest warnings

---

test/kotlin/io/envoyproxy/envoymobile/HeadersBuilderTest.kt

cleanup: fix typo in kotlin test

---

docs/root/intro/version_history.rst

The original plan was to release it yesterday but it's going to happen today instead.

docs: fix release date

---

bazel/envoy_mobile_repositories.bzl

bazel: update rules_apple & rules_swift

---

ci/sonatype_nexus_upload.py

Fixes https://github.com/envoyproxy/envoy-mobile/issues/2524

ci: fix Sonatype deploys

---

docs/root/intro/version_history.rst

Description: Update version history. A follow up to https://github.com/envoyproxy/envoy-mobile/pull/2528.
Testing: N/A

docs: update version history

---

.github/workflows/ios_build.yml
test/swift/apps/baseline/ViewController.swift

Risk Level: low (test only)
Testing: yes
Fixes https://github.com/envoyproxy/envoy-mobile/issues/2546

swift: moving baseline to use http

---

OWNERS.md

owners: add abeyad

---

.github/workflows/ios_build.yml

Risk Level: n/a
Testing: n/a
(hopefully) fixes https://github.com/envoyproxy/envoy-mobile/issues/2652

ci: increasing timeouts

---

.bazelrc

Fixes https://github.com/envoyproxy/envoy-mobile/issues/175

build: removing alwayslink

---

test/common/integration/base_client_integration_test.cc

cleanup: Remove unused variable

---

ci/linux_ci_setup.sh
test/java/org/chromium/net/testing/data/content_length_mismatch.html

This gets EM to pass Envoy format checks.

cleanup for repo merge

---

library/cc/headers_builder.cc

Follow up from https://github.com/envoyproxy/envoy-mobile/pull/2667/files/2499cc1751d8de78d0e74ca7acc2da622dbc402e#diff-767c4a04d30b269fb25067e63d4b374c1e43dbc201bbea33121cac3af963abdc

Move values in HeadersBuilder::set

---

.github/workflows/coverage.yml
library/common/extensions/cert_validator/platform_bridge/platform_bridge_cert_validator.cc
test/common/extensions/cert_validator/platform_bridge/BUILD
test/common/extensions/cert_validator/platform_bridge/platform_bridge_cert_validator_test.cc

Add unit tests of the PlatformBridgeCertValidator
