envoyproxy/envoy-mobile

library/cc/bridge_utility.cc
library/common/extensions/filters/http/platform_bridge/filter.cc
library/common/http/header_utility.cc
library/common/jni/jni_interface.cc
library/common/jni/jni_utility.cc
library/common/types/c_types.cc
library/common/types/c_types.h
library/objective-c/EnvoyBridgeUtility.h
test/common/extensions/filters/http/platform_bridge/platform_bridge_filter_test.cc
test/common/http/dispatcher_test.cc
test/common/http/header_utility_test.cc
test/common/integration/dispatcher_integration_test.cc
test/common/main_interface_test.cc

Description: introduce `envoy_data_map_entry` and `envoy_data_map` to be reused. the first and existing use case is `envoy_headers`. this pr updated utility methods to match the newly introduced data structure(s).
Risk Level: medium
Testing: unit, ci
Co-authored-by:Jose Nino <jnino@lyft.com>

bridge: rename envoy_headers to envoy_map for generalized usage

---

library/common/jni/jni_interface.cc
library/java/io/envoyproxy/envoymobile/engine/JvmStringAccessorContext.java

Missed rename when we were trying to unify Swift and Kotlin interfaces here: #1301
Description: jni: Fix JvmStringAccessorContext.getEnvoyString accessor in jni_interface
Testing: local

jni: Fix JvmStringAccessorContext.getEnvoyString accessor in jni_interface

---

bazel/envoy_mobile_repositories.bzl

Updating boringssl to be the same version as upstream envoy
Description: deps: update boring ssl
Testing: ci

deps: update boring ssl

---

library/common/http/header_utility.h
library/common/stats/utility.cc
library/common/stats/utility.h
library/common/types/c_types.cc
library/common/types/c_types.h

Description: https://github.com/envoyproxy/envoy-mobile/pull/1271 introduced envoy_stats_tags and transformation utility into C++. This PR updates the transformation utility to free the c struct after copy inline with existing utility functions.
Risk Level: low - fixes existing memory leak in tests and main_interface
Testing: ASAN ci run.

stats utility: fix memory leak

---

.bazelrc

Description: Adds new upstream flag for temporarily disabling HTTP/3.

build: update envoy and disable h3 (for now)

---

library/cc/headers.cc
library/cc/headers.h
library/python/module_definition.cc

Description: Adds an iterator to the `Headers` classes to iterate through headers. Note that this violates C++ design by iterating through the header key, not the header key/value pair. I chose this design because `pybind11` was giving me invalid memory access errors while trying to iterate through pairs. That said, I'm happy to make the key/value -> key downgrade inside of a shim if preferred.
Testing: N/A

python: add in a headers iterator

---

library/common/engine.cc

Description: Until now, we've relied upon the implicit behavior that Envoy will start at most one worker without a connection-based listener. This explicitly sets concurrency to 0 to prevent multiple workers from starting.

engine: set concurrency to 0

---

.github/workflows/android_build.yml

Description: Updates build job to use cached library artifact when run on the same SHA, allowing retries for connectivity failure or flakiness to run much faster.
Testing: CI

ci: cache build artifact across runs

---

library/swift/EngineBuilder.swift

Description: Hit a couple warnings while testing dispatcher; noticed these were missing.

swift: add a couple missing discardable annotations to EngineBuilder

---

bazel/BUILD
library/common/jni/BUILD
library/common/jni/java_jni_support.cc
library/common/jni/jni_interface.cc
library/common/jni/jni_support.h
library/common/jni/jni_utility.cc
library/common/jni/ndk_jni_support.cc

This reverts commit 0f5403ee5a05a3bdd35a921f93ee784b6d0a8ea1.
Description: jni: separate out jvm and ndk logs
Testing: device/ci

jni: separate out jvm and ndk logs

---

bazel/envoy_mobile_repositories.bzl

Description: updating apple and swift rules. We had observed weird behavior in CI which seemed to not be using previously pinned values. Both versions have been tested with at least bazel 3.1.0
Testing: CI

bazel: update rules apple and swift

---

library/common/BUILD
library/common/common/BUILD
library/common/common/lambda_logger_delegate.cc
library/common/common/lambda_logger_delegate.h
library/common/engine.cc
library/common/engine.h
test/common/common/BUILD
test/common/common/lambda_logger_delegate_test.cc
test/common/main_interface_test.cc

Description: adds a new SinkDelegate called LambdaDelegate which uses user-provided callbacks to drive `log` functionality.
Testing: new unit tests and integration test in main_interface_test.

logging: add LambdaDelegate

---

library/common/jni/jni_interface.cc
library/java/io/envoyproxy/envoymobile/engine/AndroidEngineImpl.java
library/java/io/envoyproxy/envoymobile/engine/EnvoyEngine.java
library/java/io/envoyproxy/envoymobile/engine/EnvoyEngineImpl.java
library/java/io/envoyproxy/envoymobile/engine/JniLibrary.java
library/kotlin/io/envoyproxy/envoymobile/mocks/MockEnvoyEngine.kt

Adding termination functionality to the android and java interfaces. This is functionality is not really necessary for Android applications. 
This functionality is needed for running unit tests where controlling the start and shutdown of Envoy is required to avoid abrupt shutdown crashes.
Description:  jni: pipe through terminating engine functionality
Testing: future unit tests

jni: pipe through terminating engine functionality

---

library/common/jni/jni_interface.cc

Description: jni: ensure jvm_on_engine_running handles null
Testing: unit

jni: ensure jvm_on_engine_running handles null

---

library/common/extensions/filters/http/platform_bridge/filter.cc
library/objective-c/EnvoyEngineImpl.m

Description: fixes two leaks in the platform filter chain. One in the common code, and one specific to iOS
Testing: ran with Lyft's Driver app under xcode's memory profiler.

platform brdige: fix leak in platform bridge filter in core code and in iOS code

---

.github/workflows/artifacts.yml

Description: Noticed this was timing out on main.
Testing: CI

ci: extend iOS artifact timeout

---

.github/workflows/coverage.yml

Description: This needs to run since CI requires it to pass; as a future optimization we can short-circuit if there's no changes to these directories.
Testing: CI

ci: always run coverage

---

.github/workflows/coverage.yml

Description: Updates coverage check to automatically pass for PRs that contain no changes to //library/common. Coverage will always run after a merge to main.
Testing: CI

ci: conditionally run coverage based on context

---

.github/workflows/asan.yml
.github/workflows/tsan.yml

Description: Sanitization checks constitute our two slowest current CI jobs. Updates these checks to automatically pass for PRs that contain no changes to //library/common. Checks will always run after a merge to main.
Testing: CI

ci: conditionally run asan/tsan based on context

---

library/objective-c/EnvoyEngineImpl.m

Description: add explicit autoreleaseloop blocks to all objective-c code executed in the Envoy event loop. This is necessary for correct memory management.
Testing: Lyft app under memory profiling.

ios: memory management for objc objects initialized inside Envoy's event loop

---

library/common/jni/jni_interface.cc

Description: Fixes a leak in our usage of strings produced by JNI translation. The introduction of the stats interface changes this from something that would only occur O(1) on engine creation, to something that will occur as frequently as stats are emitted.

stats: fix leaky jni strings

---

library/common/config_template.cc
library/common/extensions/stat_sinks/metrics_service/config.cc
library/common/extensions/stat_sinks/metrics_service/config.proto
test/common/extensions/filters/http/platform_bridge/platform_bridge_filter_integration_test.cc

Description: the primary goal is to pull this pr https://github.com/envoyproxy/envoy/pull/16125, as it includes behavior of metrics_sink to send `tags` as `labels` of the `MetricFamily` field.
Risk Level: medium
Testing: local build/ci

update envoy to f40e279

---

library/common/config_template.cc
library/common/http/client.cc
library/common/http/client.h
library/common/types/c_types.h
test/common/http/client_test.cc

Description: Adds built-in support for cleartext HTTP requests, without requiring custom config. TLS will be negotiated or not based off the request scheme. If cleartext is chosen, h2 protocol options will be ignored, and h1 will be used regardless.
Risk Level: Lowish
Testing: Local, Unit, CI

core: set up cleartext http request path

---

.github/workflows/ios_tests.yml

Description: Short-circuits Android/JVM CI runs when a branch contains no changes to any of:
- //library/common/...
- //library/java/...
- //library/kotlin/...
- //test/common/...
- //test/java/...
- //test/kotlin/...
- .bazelrc WORKSPACE bazel/* envoy/*
Tests will always run on main.
Testing: CI

ci: add fast pass to obj-c/swift CI for immaterial branches

---

.github/workflows/android_tests.yml

Description: Short-circuits Android/JVM CI runs when a branch contains no changes to any of:
- //library/common/...
- //library/java/...
- //library/kotlin/...
- //test/common/...
- //test/java/...
- //test/kotlin/...
- .bazelrc WORKSPACE bazel/* envoy/*
Tests will always run on main.
Testing: CI

ci: add fast pass to JVM/Android CI for immaterial branches

---

library/common/engine.cc

Description: These guards were only needed before Pulse calls were universally dispatched, and were insufficient and not thread-safe, besides.

pulse: remove obsolete engine checks

---

library/common/engine.h
library/common/event/provisional_dispatcher.h
library/common/http/client.h

Description: It's Envoy convention to define these types and use these in place of wrappers.
Testing: CI

core: define some missing pointer types

---

.bazelrc

Description: We get a ton of noise transitively from proto compilation due to this warning. This makes it much easier to parse build output.

build: suppress deprecated declaration warnings

---

library/kotlin/io/envoyproxy/envoymobile/grpc/GRPCStreamPrototype.kt
test/kotlin/integration/BUILD
test/kotlin/integration/GRPCReceiveErrorTest.kt
test/swift/integration/GRPCReceiveErrorTest.swift

Description: kotlin: add grpc receive error test
Testing: unit

kotlin: add grpc receive error test

---

test/swift/integration/SendDataTest.swift

The change is just to extract out the matching request body to a constant.
Description: swift: SendDataTest.swift clean up
Testing: ci

swift: SendDataTest.swift clean up

---

bazel/swift_static_framework.bzl

Remote Build without the Bytes and/or Remote Execution doesn't work otherwise.
Signed-off-by: Brentley Jones <brentleyjones@lyft.com>
Testing: Unit tests.

bazel: add missing input for swift generated header

---

bazel/apple_test.bzl
experimental/swift/BUILD
library/objective-c/BUILD
test/objective-c/BUILD
test/objective-c/EnvoyBridgeUtilityTest.m
test/swift/BUILD
test/swift/integration/BUILD
test/swift/stats/BUILD

Description: Adds requisite setup for objective-c unit tests, and a single example for EnvoyBridgeUtility. Fixes #1280

test: set up objc unit tests

---

library/common/config_template.cc

Description: This defaults to 15 seconds, including all retries. This disables the timeout entirely, in preference of more granular settings via a request's retry policy.
Testing: CI, Pending

engine: disable the default route timeout

---

library/common/engine.cc

Description: It's critical that postinit setup is thread-safe relative to the dispatcher, but we can't actually call Event::Dispatcher::isThreadSafe() because it blows up at this juncture. This safety check is leveraged elsewhere by Envoy to execution is happening on the main thread regardless of dispatch.

engine: ensure thread-safety in postinit setup

---

library/common/config_template.cc

Description: While it might be unusual to run up against these limits as currently configured, there's simply no reason to be opinionated about them at all in default config. Benchmarking, stress testing, and unanticipated use cases could still run up against them. This PR increases them to their practical maximum.
Testing: CI

config: increase some arbitrary limits to practical maximums

---

library/common/config_template.cc
library/java/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java
library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt
library/objective-c/EnvoyConfiguration.m
library/objective-c/EnvoyEngine.h
library/swift/EngineBuilder.swift
test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt
test/kotlin/io/envoyproxy/envoymobile/EngineBuilderTest.kt
test/swift/EngineBuilderTests.swift

Description: Exposes HTTP stream idle timeout as a configurable option via the Swift and Kotlin EngineBuilders.

engine: add configurable stream idle timeout

---

library/cc/engine_builder.cc
library/cc/engine_builder.h

Description: Fixes a bug where C++ and Python couldn't start because `stream_idle_timeout_seconds` wasn't populated on the C++-lib `EngineBuilder`
Testing: `bazel test //test/cc/...` and `bazel test //test/python/...`

add stream_idle_timeout_seconds to cc lib

---

library/common/extensions/filters/http/platform_bridge/filter.cc
library/common/extensions/filters/http/platform_bridge/filter.h
test/common/extensions/filters/http/platform_bridge/platform_bridge_filter_test.cc

Description: Previously asynchronous filter resumption of a bridged platform filter was guarded in the PBF by a weak_ptr that ensured the object was still around. It turns out this is not sufficient, as filters are submitted for delayed destruction and the presence of the object isn't enough to ensure it's still associated with a functional stream. This fix adds an additional check to ensure we don't attempt to resume iteration on a PlatformBridgeFilter that is pending destruction.
Testing: Unit and CI

filters: ensure PBFs pending destruction can't be resumed async

---

library/python/BUILD

Description: `manylinux2010` doesn't actually support `aarch64` as an architecture, so `pip` cannot install the wheel that's produced until it has been renamed. [Docs](https://www.python.org/dev/peps/pep-0599/#the-manylinux2014-policy), specifically "This list adds support for... ARMv8 (aarch64)."
Testing: on an arm64 build `build //library/python:envoy_requests_whl`

python: correct linux arm64 wheel name

---

library/cc/BUILD
library/common/BUILD
library/common/engine.cc
library/common/engine.h
library/common/engine_common.cc
library/common/engine_common.h
test/common/BUILD
test/common/engine_common_test.cc

Description: This parallels the naming relationship between main and main_common in Envoy, and arguably better captures its purpose, especially as we move to add more library-specific logic here. Also, envoy_mobile_main_common is a mouthful.

core: rename EnvoyMobileMainCommon to EngineCommon

---

library/common/config_template.cc
library/common/engine.cc
library/common/http/BUILD
library/common/http/client.cc
library/common/http/client.h
test/common/http/client_test.cc
test/common/integration/client_integration_test.cc

Description: The objective here is to make it less likely for a given connection class to suffer "catastrophic" failure of all outbound requests due to a network blip, by distributing requests across a minimum of two potential connections per connection class.
Testing: Local, In-App, Unit, CI

http client: select from a pair of clusters for each connection class

---

bazel/swift_static_framework.bzl

Description: These inputs are required for remote execution - otherwise the remote machine doesn't stage them.
Testing: bazel build with remote execution enabled
See https://stackoverflow.com/questions/52769846/custom-c-rule-with-the-cc-common-api
Signed-off-by: Ulf Adams <ulf@engflow.com>

Swift static framework: add toolchain inputs

---

test/python/BUILD

Description: Comments out the benchmark test so that we don't run it in CI. Alternate implementation is to change `.github/workflows/python_tests.yml` to not `bazel test //test/python...` and instead target specifics tests (i.e. `//test/python/runtest_unit` and `//test/python/runtest_integration`, since they auto-discover tests anyways). My take is that we'll more often want to have tests included than excluded, so its better to make this the one-off.
Testing: N/A

python: don't run python benchmark in CI

---

library/common/engine.cc

Description: More than once we've been bitten by a complete failure to start up manifesting as a simple log statement and then broken software that simply continues to run without networking. There's maybe an argument to be made for making this configurable, but for now, making exceptions fatal seems like a saner default.

engine: convert Envoy exceptions to crashes

---

library/objective-c/EnvoyEngineImpl.m

Description: Thought to check obj-c and sure enough it needed the same cleanup. Says good things about the level of parity we've managed to maintain though.

objc: simple factoring of duplicate config code

---

test/common/http/client_test.cc

I started writing tests for https://github.com/envoyproxy/envoy-mobile/pull/1513 and decided I wanted to do less copy-pasting
If this is Ok with envoy-mobile style I'll land test refactors here, so the test changes/additions are clean in 1513.
Risk Level: n/a (test only)
Testing: test passes

test: refactoring client_test

---

library/common/event/provisional_dispatcher.cc
library/common/event/provisional_dispatcher.h
test/common/mocks/event/mocks.h

Description: matches the Event::Dispatcher interface. 
Testing: existing

provisional dispather: update isThreadSafe to be const

---

library/common/config_template.cc

This should prevent us from having to force-register `envoy.cluster.static` to run tests that have direct responses with dead stripping enabled (`-all_load` removed).

config: use LOGICAL_DNS instead of STATIC for fake remote clusters

---

library/common/event/provisional_dispatcher.cc
library/common/event/provisional_dispatcher.h

Description: The dispatcher lives beyond the scope of EngineCommon, and so generic logger access is unsafe in this context.

core: remove unsafe logging from ProvisionalDispatcher

---

library/common/http/client.cc
library/common/http/client.h
test/common/http/client_test.cc
test/common/integration/client_integration_test.cc

Description: These calls are always dispatched asynchronously, so nothing can consume a return value, and always returned ENVOY_SUCCESS, besides.
Testing: CI

http client: use void return type for external API

---

library/common/http/BUILD
library/common/http/client.cc
library/common/http/client.h

Description: The Http::Client is all single-threaded code now and this synchronizer is no longer used in tests.

http client: remove test synchronizer

---

examples/kotlin/hello_world/MainActivity.kt
examples/swift/hello_world/ViewController.swift
library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt
library/swift/EngineBuilder.swift
test/swift/EngineBuilderTests.swift
test/swift/integration/ReceiveDataTest.swift
test/swift/integration/SendDataTest.swift
test/swift/integration/SendHeadersTest.swift
test/swift/integration/SendTrailersTest.swift

Description: Updates builder to allow Kotlin constructor shorthand for specifying filter factory methods, while still supporting block long-form if needed.

pbf: update builder to allow both shorthand and block form factories

---

library/java/io/envoyproxy/envoymobile/engine/JvmBridgeUtility.java

Many Cronet tests expect the response headers to be exposed in the same order as they were received. The existing implementation reorders those headers, based on the HashCode of the header name (they were put in a regular HashMap). The PR keeps the original order by rather using a LinkedHashMap.
Description: Avoid random ordering of response headers
Risk Level: Minimal
Testing: None

Keep response headers in same order as received.

---

library/java/org/chromium/net/impl/CronetUrlRequest.java

[PR1541](https://github.com/envoyproxy/envoy-mobile/pull/1541) avoids the insertion of the "server" header in the response. Its removal performed by CronetUrlRequest is therefore not needed anymore.
Description: Adjust CronetUrlRequest to PR1541
Risk Level: none
Testing: unit tests still pass

Remove deletion of the "server" header from CronetUrlRequest

---

library/common/extensions/filters/http/platform_bridge/filter.cc
library/common/http/client.cc
test/common/extensions/filters/http/platform_bridge/platform_bridge_filter_test.cc

Description: Fixes an uninitialized value in filters when the attempt count header was missing, and sets attempt_count consistently to 1. Cleanup of "optional" attempt_counts coming in a subsequent PR.
Testing: Unit, Local & CI

errors: consistently set attempt_count when missing

---

library/common/extensions/filters/http/platform_bridge/filter.cc
test/kotlin/integration/GRPCReceiveErrorTest.kt
test/kotlin/integration/ReceiveErrorTest.kt
test/swift/integration/GRPCReceiveErrorTest.swift
test/swift/integration/ReceiveErrorTest.swift

Description: Platform filters could fail to correctly transition to a completed state due to the lack of a response body on gRPC error responses. This resulted in spurious cancellation callbacks when the filter was scheduled for destruction due to the invalid "incomplete" status of the stream.
Testing: Integration, Local & CI

filters: prevent spurious cancellation callbacks from the gRPC error path

---

library/common/extensions/filters/http/platform_bridge/c_types.h
library/common/extensions/filters/http/platform_bridge/filter.cc
library/common/extensions/filters/http/platform_bridge/filter.h
library/common/jni/jni_interface.cc
library/java/io/envoyproxy/envoymobile/engine/EnvoyHTTPFilterCallbacksImpl.java
library/java/io/envoyproxy/envoymobile/engine/types/EnvoyHTTPFilterCallbacks.java
library/kotlin/io/envoyproxy/envoymobile/filters/RequestFilterCallbacks.kt
library/kotlin/io/envoyproxy/envoymobile/filters/RequestFilterCallbacksImpl.kt
library/kotlin/io/envoyproxy/envoymobile/filters/ResponseFilterCallbacks.kt
library/kotlin/io/envoyproxy/envoymobile/filters/ResponseFilterCallbacksImpl.kt
library/objective-c/EnvoyEngine.h
library/objective-c/EnvoyHTTPFilterCallbacksImpl.m
library/swift/filters/RequestFilterCallbacks.swift
library/swift/filters/RequestFilterCallbacksImpl.swift
library/swift/filters/ResponseFilterCallbacks.swift
library/swift/filters/ResponseFilterCallbacksImpl.swift

Description: This may be useful if a filter stops iteration for an extended period of time, since stream timeouts will still apply. The callback may be called periodically to continue to indicate "activity" on the stream. Note the final call to Envoy is commented out in this PR as we need the upstream change to land as well. Uncommenting and integration tests will come in a subsequent update.
Testing: Local

filters: add resetIdleTimer filter callback

---

library/common/extensions/filters/http/platform_bridge/filter.cc

Description: Unit/integration tests are still coming, but this will let us validate in the wild in parallel.
Testing: Ongoing

filters: enable reset idle timer in filters

---

.bazelrc
.github/workflows/ios_build.yml
BUILD

Add a shadow workflow that uses a remote execution cluster for the iOS
build.
Signed-off-by: Ulf Adams <ulf@engflow.com>
Description:
Risk Level: LOW
Testing: We previously built envoy mobile on the remote execution cluster.

CI: add macos remote execution config and workflow

---

.github/workflows/ios_build.yml

Description: It looks like Bazel doesn't pick up the credentials env
variable if it is already running. Unfortunately, there isn't an easy
way to test this hypothesis without merging a commit to main.
Risk Level: LOW
Testing: N/A
Signed-off-by: Ulf Adams <ulf@engflow.com>

CI: shut down bazelisk before running it

---

library/common/jni/jni_utility.cc

The data coming in from the logging interface doesn't seem to be null terminated in all cases. This constructs
a std::string and uses c_str() to get a null terminated version of the data that honors the specified length.
Risk Level: Medium, JNI changes

jni: null terminate strings before passing to NewStringUTF

---

library/objective-c/EnvoyEngine.h
library/objective-c/EnvoyEngineImpl.m
library/swift/Engine.swift
library/swift/EngineImpl.swift
library/swift/mocks/MockEnvoyEngine.swift

This is already exposed in Kotlin/Java.

swift: expose `terminate()` interface

---

ci/mac_ci_setup.sh
ci/mac_start_emulator.sh

Description: 
1) github made a [change](https://github.com/actions/virtual-environments/issues/3638) on android sdkmanager, this pr follows the migration step from the announced change.
2) android build-tools 31.0.0 (the version installed on the ci machines for now) is missing dx.jar, which causes android build to fail, this pr uninstalls 31.0.0 and installs 30.0.3 for the android build to complete.
Testing: CI

ci: update path to android sdk and use build-tools 30.0.3 for android build

---

library/cc/engine_builder.cc

Description: Remove the designated initializer I used in `engine_builder.cc` and instead populate `null_logger` field-by-field. Turns out this syntax is one of this parts of C++ that's _not_ the same as C.
Testing: `bazel test //test/...`

cc: remove designated initializer

---

library/common/config/config.cc

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Part of #1557

http: stop sending x-envoy headers upstream

---

library/java/io/envoyproxy/envoymobile/engine/AndroidNetworkMonitor.java

Adding a full try-catch as there are observations on users still trips on the permission error despite our check in the [method](https://github.com/envoyproxy/envoy-mobile/pull/1607/files#diff-7c0801593adac06d1a4d2a0239de95d28b977d9007dc4d23f4c9a86a9766a457R56-R63) (there are only two [states](https://github.com/envoyproxy/envoy-mobile/pull/1607/files#diff-7c0801593adac06d1a4d2a0239de95d28b977d9007dc4d23f4c9a86a9766a457R56-R63) to check)
Description: android: try-catch network callback registration
Testing: local
[Optional Fixes …

android: try-catch network callback registration

---

bazel/apple_test.bzl

Similar to some other envoy rules add a way to specify a repository when invoking `envoy_mobile_swift_test` rule. This is needed for cases when `envoy_mobile_swift_test` is invoked from outside of `envoy_mobile`.
Description:
Risk Level: Low (testing only, additive)
Release Notes: None

testing: add repository argument

---

test/swift/integration/StatFlushIntegrationTest.swift

Description: noticed this test was flaking.
Testing: ran with 100 reps locally.

test: deflake stats flush integration test

---

.github/workflows/core.yml
.github/workflows/ios_build.yml

Description: I've noticed that these jobs are timing out making CI red on PRs and main. Being conservative, specially with the App runs because we don't want them to run _too_ long.

ci: increase timeout for some jobs

---

.github/workflows/cc_tests.yml

Description: CC has been slower lately and this is another flow that's been timing out.

ci: extend cc test timeout

---

.github/workflows/ios_build.yml

Description: This is in preparation for changing the remote execution
service authentication configuration. We could theoretically do
it without downtime, but since this isn't on the critical path yet,
let's go the easier route.
Testing: n/a

CI: disable shadow build for upgrade

---

.gitignore
tools/vscode_compdb.sh

Adds a wrapper script that calls Envoy's comp db generation script suitable for envoy-mobile for use with VS Code.
This will create a compile_commands.json file in the root of the repo, allowing for the clangd plugin to pick this up and
provide intelisense for native code.
Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:

add vscode comp db script

---

examples/swift/hello_world/AsyncDemoFilter.swift

Description: Bugfix. The AsyncDemoFilter would hold headers-only responses indefinitely, leading to a timeout. Encountered this testing error responses with the example apps.

examples: fix AsyncDemoFilter in swift example app

---

examples/kotlin/hello_world/AsyncDemoFilter.kt

Description: Bugfix. The AsyncDemoFilter would hold headers-only responses indefinitely, leading to a timeout. Encountered this testing error responses with the example apps.

examples: fix AsyncDemoFilter in kotlin example app

---

library/java/io/envoyproxy/envoymobile/engine/types/EnvoyHTTPFilterCallbacks.java

java: add missing docstrings to EnvoyHTTPFilterCallbacks

---

.bazelrc
.github/workflows/ios_build.yml

Description: Re-enable remote execution shadow build for iOS.
- use GITHUB_TOKEN for authentication
- use `--config=remote` for consistency with Envoy
- reduce number of jobs to match the current layout
Testing: Manually tested

CI: update authentication + config

---

library/swift/EngineBuilder.swift

This matches what the Kotlin version allows
Testing: n/a

swift: Make EngineBuilder open to allow for subclassing

---

bazel/envoy_mobile_dependencies.bzl
library/swift/BUILD

This can be used to attach extra source files to the main swift_library
target, which is useful for including private additions.

bazel: Add envoy_mobile_extra_swift_sources repository

---

ci/mac_start_emulator.sh

Description:  Fixing Android emulator as it currently fails with `Package "Android Emulator" with revision at least 30.8.2 not available.` when CI jobs for Android hello world apps (Java and Kotlin) are run.
Testing: N/A

ci: use channel 3

---

test/swift/integration/FilterResetIdleTest.swift

Adds an assertion that we don't get a cancel callback, which fails consistently locally. Ignore the test
until we can fix the underlying issue
Description:
Testing: n/a

test: add failing assertion to flaky swift test and ignore it

---

.bazelrc
test/common/engine_test.cc

Ensures that we shut down and join the engine thread in engine_test, preventing a data race from happening when the test runner
writes to Envoy::Logger::current_log_context during shutdown. 
Also updates the tsan-dev option to specify the same overrides as upstream Envoy, without this we see failures when using absl::Notification.
Description: n/a
Risk Level: Low, test only

test: ensure we properly shut down the engine thread in test

---

bazel/kotlin_test.bzl

This should allow a repo that consumes envoy-mobile via a submodule to reuse this test rule.
Testing: n/a

build: allow reusing android test rule via submodule

---

.bazelrc
ci/BUILD

Description:
With remote execution, envoy mobile spends a significant fraction
of its built time in loading/analysis phase, and specificaly, in a
7.5 minutes build, around 2.7 minutes in evaluating @local_config_xcode
which auto configures Bazel with the locally installed Xcode versions.
Since envoy mobile passes `--xcode_version=12.4` in its `.bazelrc`, thus
requires a specific Xcode version, we can make the build significantly
faster by creating our own `xcode_config` target instead of relying
on Bazel's auto configuration.
Example invocation: https://envoy.cluster.engflow.com/invocation/a23bd20b-f0b9-472b-9a07-b9e5bc629b30#performance
Testing: local/CI

Use self-provided xcode_config target instead of relying on @local_config_xcode

---

.github/workflows/ios_build.yml

Description: Builds are failing with `java.io.IOException: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: RESOURCE_EXHAUSTED: Not enough space to create a replica`. Reverting to previous setup.
Testing: CI

ci: revert EngFlow ios_build changes

---

.github/workflows/ios_build.yml

Description:
This reverts commit 1adf02d1cb46357f6db11ad2370e2879d212d2ec.
The machine was running out of space because it was keeping large replicas of build artifacts for too long. We've since increased the disk space as well as decreased the timeout for evicting those large artifacts. Performance may be slightly degraded if those artifacts need to go to disk to be fetched but by looking at previous results it'll probably be ok
Testing: See ios_build presubmit

Revert "ci: revert EngFlow ios_build changes (#1700)"

---

bazel/envoy_mobile_repositories.bzl

Risk Level: low  (Envoy upstream uses this version)
Testing: assuming extra tests validate

build: bumping boring to HTTP/3 compatible version

---

.github/workflows/ios_build.yml

Description: This reverts commit 35ac59d54f4172e60c6bc902776c2254b43bc880.
The RBE ios_build job has been timing out every time in CI, and switching back to running on GHA runners resolves the issue.

ci: revert of EngFlow ios_build changes due to timeouts

---

library/common/config/config.cc
test/java/org/chromium/net/CronetUrlRequestTest.java

This is causing some TLS errors:
```upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER```
This reverts commit 6e507d3e753a0725eef6398d10dd1503c5dc3010.
Description: Revert "extending propercasing to legacy clusters, header sanitization to all routes (#1621)"
Risk Level: medium
Testing: manual testing

Revert "extending propercasing to legacy clusters, header sanitization to all routes (#1621)"

---

library/cc/engine_builder.cc
library/common/BUILD
library/common/engine.cc
library/common/engine.h
library/common/extensions/filters/http/test_accessor/filter.cc
library/common/extensions/filters/http/test_event_tracker/filter.h
library/common/jni/jni_interface.cc
library/common/main_interface.cc
library/common/main_interface.h
library/java/io/envoyproxy/envoymobile/engine/EnvoyEngineImpl.java
library/java/io/envoyproxy/envoymobile/engine/JniLibrary.java
library/objective-c/EnvoyEngine.h
library/objective-c/EnvoyEngineImpl.m
library/objective-c/EnvoyEventTracker.m
test/common/engine_test.cc
test/common/main_interface_test.cc
test/kotlin/integration/SetEventTrackerTest.kt
test/swift/integration/BUILD
test/swift/integration/SetEventTrackerTest.swift
test/swift/integration/SetEventTrackerTestNoTracker.swift

Description: Send an envoy event with the use of envoy event tracker every time an assertion is hit. The event contains two fields: `name` equal to `assertion` and location which contains the information about the name of the file and line number for where the assertion was hit.
Risk Level: Low. Optional feature that's active only when `DENVOY_LOG_DEBUG_ASSERT_IN_RELEASE` compilation flag is specified.
Testing: Unit/Integration

assert: emit events for assertions

---

library/common/config/config.cc

Description: This PR (which picks up work started on #1567) adds outlier detection to all configured clusters.
The main objective of this configuration is to drain connections that are perceived to be "dead" so that the cluster is forced to establish a new connection for future streams. 
Currently the outlier detector will not eject already ejected hosts. And host ejection is what causes connection drain. In mobile, the desire is not to keep hosts ejected, but rather to cycle the underlying upstream connections. Hence the short base/max ejection time and the the tight unejection interval. The unejection interval is not any tighter because to balance timer churn.
The idea with the current configuration is that most, if not all "dead" connections will be reaped without having any adverse …

config: add outlier detection config

---

library/common/config/config.cc

Description: adds allow list for outlier detection stats to instrument #1718 
Risk Level: low - while the stats tree is somewhat wide, the current config only will emit stats for consecutive 5xx limiting the number of stats emitted.

stats: add outlier detection stats

---

.github/workflows/ios_build.yml

Description:
CI: Re-enable ios_build in Engflow's remote execution.
The builds were timing out because the machines were down in AWS due to a restart.
Testing: See ios_build check

CI: Re-enable ios_build in Engflow's remote execution 

---

.github/workflows/core.yml

Description: 
Move core workflow to Engflow's remote execution and reduce build times by 3x
Before (~1h30min):
After(<30min):
Testing: See core check

CI: Move core workflow to Engflow's remote execution

---

library/common/config/certificates.inc
library/common/config/config.cc

Description: The Envoy Mobile h2 clusters force h2 to be the underlying protocol regardless, but this change has them advertise h2 via ALPN to be closer aligned with the standard.

config: advertise h2 alpn string when forcing h2

---

library/kotlin/io/envoyproxy/envoymobile/filters/Filter.kt

Description: android: pass constructed stream intel for filters
Testing: local
Need tests: https://github.com/envoyproxy/envoy-mobile/issues/1735

android: pass constructed stream intel for filters

---

library/common/config/config.cc

This updates the TLS configuration to allow TLS 1.3 (up from a max of 1.2)
Testing: n/a

common: allow TLS 1.3 for upstream connections

---

.bazelrc

Description: Enable gRPC keepalives. We have seen cases where the
connection is closed without a TCP RST, in which case Bazel
can wait (almost) indefinitely for a response from the server. This
avoids that by sending a keepalive after a 61s of not receiving any
messages from the server. Note that the server is configured to
send one update per minute for execute calls, so this should
generate very little additional traffic in most cases.
Testing: CI
Signed-off-by: Ulf Adams <ulf@engflow.com>

Bazel: enable keepalive ~once / minute

---

test/java/org/chromium/net/CronetUrlRequestTest.java
test/java/org/chromium/net/testing/CronetTestRule.java

Respecting header name capitalization caused other tests to fail, and related PR had to be rolled back. See [PR1710](https://github.com/envoyproxy/envoy-mobile/pull/1710)
Description: tests not related to request header capitalization are re-enabled. 
Testing: re-enabling tests

Re-enable tests that were disabled due to PR1710

---

library/common/config/config.cc

Description: Allows TLS 1.3 in the case of the forced H2 clusters.
Testing: CI

config: enable TLS 1.3 on forced H2 socket

---

library/common/bridge/BUILD
library/common/bridge/utility.cc
library/common/bridge/utility.h
library/common/engine.cc
library/common/extensions/filters/http/local_error/config.cc
library/common/extensions/filters/http/local_error/filter.cc
library/common/extensions/filters/http/local_error/filter.h
library/common/extensions/filters/http/platform_bridge/BUILD
library/common/extensions/filters/http/platform_bridge/filter.cc
library/common/extensions/filters/http/platform_bridge/filter.h
library/common/extensions/filters/http/test_event_tracker/filter.cc
library/common/http/BUILD
library/common/http/client.cc
library/common/http/client.h
library/objective-c/EnvoyEngine.h
test/common/bridge/utility_test.cc
test/common/http/client_test.cc
test/common/main_interface_test.cc
test/kotlin/integration/CancelStreamTest.kt
test/kotlin/integration/StreamIdleTimeoutTest.kt
test/python/unit/test_basics.py
test/swift/integration/BUILD
test/swift/integration/CancelStreamTest.swift
test/swift/integration/IdleTimeoutTest.swift
test/swift/integration/SetEventTrackerTestNoTracker.swift

Description: Removes previous hacky workaround to infer local library errors and migrates to an explicit callback from Envoy.
Testing: Updated unit tests; existing and new integration coverage

core: integrate callback-based error path

---

.bazelrc
WORKSPACE

Description:
CI: Add clang configs for Engflow's remote execution.
This change is a no-op that will be used for switching more CI workflows to Engflow's remote execution.
See https://github.com/envoyproxy/envoy-mobile/pull/1745 for preliminary results.
Testing: Manually tested

CI: Add clang configs for Engflow's remote execution

---

test/swift/integration/CancelStreamTest.swift
test/swift/integration/DirectResponseContainsHeadersMatchIntegrationTest.swift
test/swift/integration/DirectResponseExactHeadersMatchIntegrationTest.swift
test/swift/integration/DirectResponseExactPathMatchIntegrationTest.swift
test/swift/integration/DirectResponseFilterMutationIntegrationTest.swift
test/swift/integration/DirectResponsePrefixHeadersMatchIntegrationTest.swift
test/swift/integration/DirectResponsePrefixPathMatchIntegrationTest.swift
test/swift/integration/DirectResponseSuffixHeadersMatchIntegrationTest.swift
test/swift/integration/DrainConnectionsTest.swift
test/swift/integration/FilterResetIdleTest.swift
test/swift/integration/GRPCReceiveErrorTest.swift
test/swift/integration/IdleTimeoutTest.swift
test/swift/integration/ReceiveDataTest.swift
test/swift/integration/ReceiveErrorTest.swift
test/swift/integration/SendDataTest.swift
test/swift/integration/SendHeadersTest.swift
test/swift/integration/SendTrailersTest.swift
test/swift/integration/SetEventTrackerTest.swift
test/swift/integration/SetEventTrackerTestNoTracker.swift

Description: Explicitly terminates the engine at the conclusion of each test and randomizes the port to avoid flakiness from overlapping socket bind attempts.

tests: fix flaky swift integration tests

---

test/java/org/chromium/net/CronetUrlRequestTest.java

Remove 3 ```@ignore``` from CronetUrlRequestTest
Description: enable tests ensuring that the Connection header is returned with the response header
Risk Level: N/A
Testing: enables tests

Add tests related to the Connection response header

---

test/kotlin/integration/CancelStreamTest.kt
test/kotlin/integration/StreamIdleTimeoutTest.kt

Description: Similar to #1764, this will help prevent port reuse from concurrently running tests.

tests: use random remote port in kotlin integration tests

---

library/common/engine.cc

This ensures that logs and log events emitted early on in engine startup makes it through the attached logger.

common: register logger before engine start

---

.github/workflows/format.yml

Description:
CI: Move Kotlin workflow in format to Engflow's remote execution and cut format workflow build time by a half.
Before:
After:
Testing: See format workflow

CI: Move Kotlin workflow in format to Engflow's remote execution

---

library/common/engine.cc
library/common/engine.h
test/common/main_interface_test.cc

Description: Emit Envoy event every time an Envoy bug is detected. Envoy bug is similar to Envoy assert.
Risk Level: Low, new functionality
Testing: Unit

core: emit envoy event every time envoy bug macro is called

---

.bazelrc
bazel/BUILD
library/common/network/BUILD
library/common/network/mobile_utility.cc
third_party/BUILD
third_party/android/LocalArray.h
third_party/android/ScopedFd.h
third_party/android/ifaddrs-android.h

Description: The range of Android versions supported by Envoy Mobile don't all have native getifaddrs(3) support. In order to ship a single distributable package that can support all versions, this change conditionally bundles the custom Android Gingerbread implementation, which is (mostly) contained in a single header.

android: conditionally build internal getifaddrs support

---

library/common/config/config.cc

Turning up propercasing for HTTP/1.1, now avoiding the SAN issues.
Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
Fixes https://github.com/envoyproxy/envoy-mobile/issues/1558

reinstating propercasing

---

library/java/io/envoyproxy/envoymobile/engine/JvmBridgeUtility.java
library/kotlin/io/envoyproxy/envoymobile/RetryPolicy.kt
library/objective-c/EnvoyBridgeUtility.h
library/swift/RetryPolicyMapper.swift
test/java/io/envoyproxy/envoymobile/engine/JvmBridgeUtilityTest.kt
test/kotlin/io/envoyproxy/envoymobile/RetryPolicyMapperTest.kt
test/swift/RetryPolicyMapperTests.swift

Description: reverts earlier logic that splits comma-separated headers introduced in #1212 #1213. Upon further inspection of the Envoy code we now understand that the Envoy behavior to coalesce headers with multiple appearances in the header map is limited to Envoy's inline headers. Thus this PR reverts the Envoy Mobile logic to split up headers which should have no semantic impact in headers per RFC. However, we do add logic to the Envoy Mobile RetryPolicy classes which need individual values in order to correctly map to the swift/kotlin enum cases specific to those classes.
Risk Level: med - changes header handling logic
Testing: added unit tests

header handling: delete splitting comma-separated header values and add specific logic to the RetryPolicy classes

---

library/cc/engine_builder.cc
library/cc/engine_builder.h
library/common/config/config.cc
library/java/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java
library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt
library/objective-c/EnvoyConfiguration.m
library/objective-c/EnvoyEngine.h
library/swift/EngineBuilder.swift
test/cc/unit/envoy_config_test.cc
test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt
test/kotlin/io/envoyproxy/envoymobile/EngineBuilderTest.kt
test/swift/EngineBuilderTests.swift

Description: adds engine builder and config plumbing to setup h2 ping support
Risk Level: low - exposed API. Default config is no-op in Envoy
Testing: added tests
Docs Changes: pending if reviewers agree with API

engine: add H2 ping config API

---

test/java/org/chromium/net/CronetUrlRequestTest.java
test/java/org/chromium/net/testing/CronetTestRule.java

Remove last remnant associated with Issue [1558](https://github.com/envoyproxy/envoy-mobile/issues/1558)
Description: Fully test capitalization with HTTP/1
Testing: testing only PR

Remove remaining test crutch for HTTP/1 capitalization

---

.bazelrc

The android define logger conflicts with the logger lambda API such that the logger lambda would not be called if Envoy Mobile is built with the flag.
Description: android: release builds avoids defining logger
Testing: local

android: release builds avoids defining logger

---

library/common/config/config.cc

Description: On mobile, backgrounding might cause the host to be past its TTL without good reason. Given the host would be deleted, and new streams for a given domain would have to wait for resolution, it is better to not delete existing hosts; especially since deletion only happens when re-resolving is already in progress. There is no way to disable so the value below is equivalent to 24 hours.
Testing: CI

dns: effectively disable host ttl

---

envoy_build_config/BUILD
envoy_build_config/extension_registry.cc
envoy_build_config/extension_registry.h
envoy_build_config/extensions_build_config.bzl
library/common/config/config.cc
library/common/engine.cc
library/common/engine.h
library/common/extensions/filters/http/socket_selection/BUILD
library/common/extensions/filters/http/socket_selection/config.cc
library/common/extensions/filters/http/socket_selection/config.h
library/common/extensions/filters/http/socket_selection/filter.cc
library/common/extensions/filters/http/socket_selection/filter.h
library/common/extensions/filters/http/socket_selection/filter.proto
library/common/http/BUILD
library/common/http/client.cc
library/common/http/client.h
library/common/main_interface.cc
library/common/network/BUILD
library/common/network/mobile_utility.cc
library/common/network/mobile_utility.h
test/common/http/client_test.cc
test/common/integration/client_integration_test.cc

TODO:
Description: Removes network-specific clusters and replaces with a filter that sets unique socket options based on current preferred network (via Reachability) status. Envoy internally creates a different socket pool for a unique set of socket options, so the effect of this is that we still use different sets of connections per interface, but no longer rely on a large set of clusters to do so. This PR also lays the groundwork for us to experiment with interface-bound sockets.
Risk Level: High
Testing: Existing unit and integration coverage

network: create SocketSelectionFilter 

---

test/swift/BUILD
test/swift/integration/BUILD
test/swift/integration/GRPCReceiveErrorTest.swift
test/swift/stats/BUILD

Ideally, similar to cc_test targets, these would all be separate. But
with iOS tests this has a bunch of downsides:
1. You have to re-link every test bundle (same as cc_tests) which takes
a huge amount of time for these tests (on the order of minutes per
target)
2. You have to re-create and launch a fresh simulator for every test
target which is a huge amount of overhead
3. You have to separately maintain a duplicative list of deps
Combining these does have some small downsides
1. You link a bit more when iterating on a test, this is nothing
compared to the overall deps you end up linking from envoy, so it
shouldn't meaningfully impact performance
2. You over-specify deps for some test cases, considering how few deps
tests have today this shouldn't be an issue
Overall I think this is …

bazel: unify envoy_mobile_swift_test targets

---

bazel/envoy_mobile_swift_bazel_support.bzl

This is covered by envoy's dependencies. I don't see any reason why we
need to force it to load earlier or differently from when envoy would do
it.

bazel: remove unnecessary rules_foreign_cc load

---

ci/mac_start_emulator.sh

These should be the same, but this one is installed by default

ci: use $ANDROID_HOME relative sdkmanager

---

library/common/http/client.cc
library/common/http/client.h
test/java/integration/AndroidEnvoyExplicitFlowTest.java
test/java/integration/BUILD

- Comes with a specific Envoy Mobile test for Explicit Flow Control.
- bonus: fixes a bug: the wrong `end_stream` boolean was sent to the callback.
Description: Solve crashes for explicit flow control 
Risk Level: small - better than crashes for sure.
Testing: CI

Save latest StreamIntel as StreamInfo may become unavailable when accessed.

---

library/objective-c/EnvoyBridgeUtility.h

header handling: prevent nil header value crashes in obj-c

---

library/common/config/config.cc
library/common/extensions/filters/http/network_configuration/config.cc
library/common/extensions/filters/http/network_configuration/filter.cc
library/common/extensions/filters/http/network_configuration/filter.h
library/common/extensions/filters/http/network_configuration/filter.proto
library/common/network/configurator.cc
library/common/network/configurator.h

Description: Pass interface binding configuration and state through the NetworkConfiguration filter to the NetworkConfigurator. Down the road, we may want to have a dedicated extension for configuring this sort of thing.
Testing: Existing integration.

network: wire interface binding config through core filter

---

.github/workflows/android_tests.yml
.github/workflows/asan.yml
.github/workflows/cc_tests.yml
.github/workflows/coverage.yml
.github/workflows/format.yml
.github/workflows/perf.yml
.github/workflows/python_tests.yml
.github/workflows/tsan.yml
WORKSPACE

Description:
https://github.com/envoyproxy/envoy/pull/18220 updated run_bazel_coverage_script.sh to require clang 12 thus making the current coverage script to always fail due to https://github.com/envoyproxy/envoy/blob/0656e34e0c87a77fb87273be89afd4922a30c7db/test/run_envoy_bazel_coverage.sh#L5. This PR updates the Ubuntu CI images in the envoy-mobile repo to match the image in Envoy.
Testing: See CI workflows

CI fix: Upgrade CI image to use clang 12

---

.bazelrc

This enables -debug-prefix-map to rewrite Swift compile's pwd to .,
similar to what we were already doing for C++ with
debug_prefix_map_pwd_is_dot

bazel: Fix absolute Swift paths

---

library/common/engine.cc
third_party/android/ifaddrs-android.h

Description:
As of today the third party implementation of `getifaddrs` we are using
returns interfaces but doesn't iterate over all addresses so the v6_vec
is always empty given that the kernel always returns v4 first.
Docs Changes: No

Fix getifaddrs to return all addresses

---

bazel/envoy_mobile_repositories.bzl

Description: Upgrades rules_jvm_external to 4.1. this brings in some bug fixes that are needed to support downloading newer Dokka versions.
Testing: Manual build

bazel: upgrade rules_jvm_external to 4.1

---

bazel/android_artifacts.bzl
bazel/dokka.bzl
bazel/envoy_mobile_dependencies.bzl
bazel/envoy_mobile_repositories.bzl

Description: Upgrade Dokka to 1.5.31. This is needed in order to use JDK 11.
Testing: Compared old javadocs output to new output. Attached are both the outputs.
Docs Changes: Javadocs now output in a more modern format. The main change is having a search bar instead of iFrames. This matches JDK 11 javadocs output.
[new_javadocs.jar.zip](https://github.com/envoyproxy/envoy-mobile/files/7286482/new_javadocs.jar.zip)
[old_javadocs.jar.zip](https://github.com/envoyproxy/envoy-mobile/files/7286483/old_javadocs.jar.zip)
Signed-off-by: Brentley Jones <brentleyjones@lyft.com>

docs: Upgrade Dokka to 1.5.31

---

bazel/BUILD
bazel/EnvoyMobileTestSuite.kt
bazel/envoy_mobile_dependencies.bzl

Description: Fixed `EnvoyMobileTestSuite` for JDK 11. In JDK 9 you can no longer cast `ClassLoader` to `URLClassLoader`.
Risk Level: Low. Affects tests only.
Testing: Ran locally.
Thanks to @bencodes for helping me resolve this.
Signed-off-by: Brentley Jones <brentleyjones@lyft.com>

tests: Fix `EnvoyMobileTestSuite` for JDK 11

---

bazel/envoy_mobile_repositories.bzl

Additional Info:
- v3.10.4 of  nlohmann/json introduced [CPP 17 specific functionality](https://github.com/nlohmann/json/compare/v3.10.2..v3.10.4#diff-8477168a53cf806fd7b9fba0ee3b7f4e28e378a5b0b2737cdddd8cf49f99b318R396). Envoy Mobile itself is compatible with CPP 17. However, there is specific functionality not available on iOS <13. This means that this dependency cannot be updated until Envoy Mobile moves the [minimum iOS version to 13](https://github.com/envoyproxy/envoy-mobile/blob/69a697d9052d8f6842e147d5e8b9d7a34e8fdf64/.bazelrc#L12).

envoy: c926499ed

---

library/common/engine.cc
library/common/engine.h
library/common/network/BUILD
library/common/network/configurator.cc
library/common/network/configurator.h
library/common/network/src_addr_socket_option_impl.cc
library/common/network/src_addr_socket_option_impl.h
test/common/network/configurator_test.cc

Description: `SO_BINDTODEVICE` will generally only be useable by an Android app running as root, so the present interface-binding approach on Android is mostly a non-starter. Instead, this change binds the interface indirectly by finding the local IP of the interface and setting that as the source IP of the socket.
To do so, it passes a "synthetic" socket option through to the internal connection API. When applied, instead of setting an actual socket option on the socket, this object sets the source IP property on the connection before bind() is called.
Testing: Local & On Device

network: support interface binding on Android

---

library/common/network/src_addr_socket_option_impl.cc
test/common/network/BUILD
test/common/network/src_addr_socket_option_impl_test.cc

Description: Adds defensive handling since returned addresses may be null (especially after filtering: #1901).
Testing: Local & On Device

network: make SrcAddrSocketOptionImpl safely handle null addresses

---

.bazelrc
ci/platform/BUILD

This adds an explicit platform to use for remote execution on macOS.
While this is more verbose than using `--remote_default_exec_properties`, it has the benefit that Bazel will
merge the specified platform properties with the ones specified by actions/targets instead of replacing them
(e.g., if a target has `exec_properties = {"cache-silo-key": "1"}`, the actions for this target will have
`{"Pool": "macos", "cache-silo-key": "1"}`. With `--remote_default_exec_properties=Pool=macos`, the actions
would only get `{"cache-silo-key": "1"}`, i.e. it would be executed on the "default" pool which doesn't exist
on the backend).
Testing: See workflows

Define platform target for macOS CI

---

WORKSPACE
bazel/envoy_mobile_swift_bazel_support.bzl

Description: Remove useless `swift_support()` macro. It was being called, but `build_bazel_apple_support` is already being declared with `apple_rules_dependencies()`.
Testing: Local builds.

bazel: Remove useless `swift_support()` macro

---

bazel/envoy_mobile_repositories.bzl
library/swift/BUILD

Description: Update rules_apple and rules_swift. This is in preperation for Bazel 5.0.
Testing: Local builds.

bazel: Update rules_apple and rules_swift

---

.bazelrc

Description: Remove `--incompatible_objc_compile_info_migration` bazel flag. It is now default in Bazel 4.1, and the flag is removed in Bazel 5.0.
Testing: Local build.

bazel: Remove `--incompatible_objc_compile_info_migration`

---

.bazelrc

Description: Set `--java_runtime_version` for Bazel. This is a noop until Bazel 5.0, but it allows one to use 5.0 locally without setting additional flags.
Testing: Local builds.

bazel: Set `--java_runtime_version`

---

library/swift/BUILD

Description: Don't cache or remote exec `ios_framework`. Since this file changes frequently, and it's very large, it's more performant to not cache it and not run it remotely. Requires Bazel 5.0 and newer rules_apple to work.
Testing: Local builds.

bazel: Don't cache or remote exec `ios_framework`

---

.github/workflows/android_tests.yml

See [Issue 1932](https://github.com/envoyproxy/envoy-mobile/issues/1932)
Description: Allows PR to be submitted - now currently blocked by systematic failures.
Risk Level: small
Testing: removes testing

Disable test/kotlin/integration tests for Mac

---

library/common/http/client.cc
library/common/http/client.h
test/java/integration/AndroidEnvoyExplicitFlowTest.java

Description: Race condition between stream destruction and runLowWatermarkCallbacks
Risk Level: small
Testing: CI, and a new test failing if the fix is absent.
Fixes #1931

Fix race condition for last resumeData

---

library/swift/grpc/GRPCStreamPrototype.swift

As of https://github.com/envoyproxy/envoy-mobile/commit/d7b6af3e3e02c2f1152e9ee7f179418c4b5062c4 this no longer retains `self`.

swift: remove outdated documentation

---

library/cc/BUILD
library/cc/bridge_utility.cc
library/cc/engine_builder.cc
library/cc/engine_callbacks.cc
library/cc/stream_callbacks.cc
library/python/BUILD
test/cc/integration/BUILD
test/cc/unit/BUILD

This fixes an issue where depending on this library would fail due to the use of C++ 20 designated initializers.
Risk Level: Low, build only
Docs Changes: n/a 

cc: avoid use of designated initializers

---

.bazelversion

These should likely always match since envoy's build configs could
depend on it.

bazel: change .bazelversion to be symlink from envoy

---

.github/workflows/ios_build.yml
examples/swift/async_await/AppDelegate.swift
examples/swift/async_await/BUILD
examples/swift/async_await/Base.lproj/LaunchScreen.storyboard
examples/swift/async_await/ContentView.swift
examples/swift/async_await/Info.plist

I built this while debugging an issue a user had reported, and thought it would be useful to keep as an example app.
This example showcases a few integrations that weren't being exercised elsewhere I could find:
* Swift 5.5's new async/await & structured concurrency features
* Concurrent uploads to https://httpbin.org
* Starting streams on concurrent GCD queues
* SwiftUI interface
Finally, also add a CI job to validate that this example builds and logs the expected output.

[examples] Add Swift async/await example app

---

external/requirements.txt

This doesn't seem to be used at all and is affecting some source mapping while debugging the example app

remove external folder

---

library/common/jni/jni_utility.cc

Description: #1906 introduced path whereby the check for whether a buffer is direct was skipped, then treated the -1 value returned by the capacity check as an unsigned size for allocation. This fix ensures the check always happens.
Testing: Kotlin integration tests need to be re-enabled.

jni: fix support for non-direct byte buffers

---

library/objective-c/EnvoyEngineImpl.m
library/objective-c/EnvoyHTTPStreamImpl.m

Description: This is a followup to https://github.com/envoyproxy/envoy-mobile/pull/1937.
Risk Level: I believe these extra parameters are safe to ignore if we don't need to propagate them to the Objective-C interface, but would like someone else to confirm that.
Testing: Example apps still work, and downstream (closed source) consumers now compile again.
Docs Changes:
Release Notes:

Update Objective-C on error/cancel to include final_stream_intel

---

.github/workflows/ios_tests.yml
library/objective-c/EnvoyBridgeUtility.h
test/objective-c/EnvoyBridgeUtilityTest.m

Description: Fix `NSString` to `envoy_data` conversion for non-ascii strings such as '台灣大哥大'. `-length` is the number of UTF-16 code units in the receiver whereas `-lengthOfBytesUsingEncoding:` is the number of UTF8 bytes. Using the latter is necessary since we're using this value to determine how many bytes to copy from the string.
Testing: Added an Objective-C unit test, and enabled running on CI.
Docs Changes:
Release Notes:

[EnvoyBridgeUtility] Fix NSString to envoy_data conversion

---

library/common/engine.cc

Description: Both `v4_interfaces` and `v6_interfaces` were using V4 interfaces likely due to a typo. This is a follow-up to https://github.com/envoyproxy/envoy-mobile/pull/1897.
Risk Level: Low, just fixing a log.
Testing:
Docs Changes:
Release Notes:

Fix V6 interface binding logging

---

library/common/engine.cc
library/common/http/header_utility.cc
library/common/network/BUILD
library/common/network/android.cc
library/common/network/android.h
library/common/network/configurator.cc
test/common/integration/client_integration_test.cc
test/common/network/configurator_test.cc

Changes: https://github.com/envoyproxy/envoy/compare/23e5fc2939e1782416155509edfca323150e8a59...70a5f295da789610b9d078015f43e39c6a76d4b6

Update Envoy to 70a5f29

---

WORKSPACE

Bazel builds default to 32.0.0 build tools version. This is a work around till we update to bazel 5.x
Description: android: hardcode build_tools_version to 30.0.2
Testing: n/a

android: hardcode build_tools_version to 30.0.2

---

library/common/bridge/utility.cc
library/common/bridge/utility.h

Changes makeEnvoyMap to work with not only a vector of pairs, but any
map-like container type.

common: make makeEnvoyMap more generic

---

test/java/org/chromium/net/BUILD

This test has been flaky in several unrelated PRs. I am disabling for now to investigate in parallel so it does not block forward progress on other PRs.

cronet: disable cronet_url_request_test

---

library/common/http/client.h

Description: expands the buffer size of the DirectStream from 65kb to 1mb. 
Risk Level: low - previously responses reaching the limit size would have resulted in an error.
Testing: tested with the example apps and this Envoy diff
```
diff --git a/source/common/http/filter_manager.cc b/source/common/http/filter_manager.cc
index 2864da7758..ec102fa515 100644
--- a/source/common/http/filter_manager.cc
+++ b/source/common/http/filter_manager.cc
@@ -1531,6 +1531,7 @@ Buffer::InstancePtr ActiveStreamEncoderFilter::createBuffer() {
[this]() -> void { this->responseDataDrained(); },
[this]() -> void { this->responseDataTooLarge(); },
[]() -> void { /* TODO(adisuissa): Handle overflow watermark */ });
+  ENVOY_LOG_MISC(error, "setting buffer limit {}", parent_.buffer_limit_); …
```

buffer size: expand response buffer limit to 1Mb

---

examples/objective-c/hello_world/ViewController.m
examples/swift/hello_world/AsyncDemoFilter.swift
examples/swift/hello_world/BufferDemoFilter.swift
examples/swift/hello_world/DemoFilter.swift
library/kotlin/io/envoyproxy/envoymobile/StreamPrototype.kt
library/kotlin/io/envoyproxy/envoymobile/filters/ResponseFilter.kt
library/objective-c/EnvoyEngine.h
library/objective-c/EnvoyEngineImpl.m
library/objective-c/EnvoyHTTPStreamImpl.m
library/swift/BUILD
library/swift/FinalStreamIntel.swift
library/swift/StreamCallbacks.swift
library/swift/StreamIntel.swift
library/swift/StreamPrototype.swift
library/swift/filters/Filter.swift
library/swift/filters/ResponseFilter.swift
library/swift/grpc/GRPCStreamPrototype.swift
library/swift/mocks/MockStream.swift
test/swift/integration/CancelStreamTest.swift
test/swift/integration/FilterResetIdleTest.swift
test/swift/integration/GRPCReceiveErrorTest.swift
test/swift/integration/IdleTimeoutTest.swift
test/swift/integration/ReceiveErrorTest.swift

Description: I've changed up my approach here. Previously, I mirrored Android/core APIs by having a separate struct for FinalStreamIntel. Upon further consideration, I feel it's a significant improvement to the API's usability and future flexibility to have FinalStreamIntel be a true superset (and derivative) of StreamIntel. With this change the terminal callbacks - onComplete (previously not exposed in the public API), onCancel, and onError contain a FinalStreamIntel object, and other callbacks contain the prior StreamIntel subset.
Testing: Unit, Integration

stream intel: wire iOS FinalStreamIntel for parity with jvm/android

---

bazelw

This uses a fat binary version of bazelisk to better support arm bazel

bazel: change bazelisk for M1 support

---

.github/workflows/core.yml
bazel/apple_test.bzl
docs/root/intro/version_history.rst
library/common/config/config.cc
test/common/integration/BUILD
test/swift/integration/BUILD

Commit Message: Decompress even when `no-transform` is specified
Additional Description: This leverages the flag added in https://github.com/envoyproxy/envoy/pull/19399 to always decompress responses, regardless of the presence of a `no-transform` cache control header, matching the more lenient behavior of other client-side networking libraries such as OkHttp or URLSession, especially in cases where the remote server is not under the client developer's control.
Risk Level: Low, responses that would previously fail to decode will now succeed when a compressed response comes with a `no-transform` cache control header.
Testing: Added unit tests in Envoy and manually confirmed in an Android app that gzipped responses with `no-transform` that previously failed now succeed.
Docs Changes: Not …

Decompress even when `no-transform` is specified

---

bazelw

This reverts commit fa75a60839a570eec54a086d24f1735f2e1d96e1.
Unfortunately still not working on M1.
E.g.
```
$ ./bazelw build //library/common:envoy_main_interface_lib
ERROR: While resolving toolchains for target @com_envoyproxy_protoc_gen_validate//:protoc-gen-validate: no matching toolchains found for types @io_bazel_rules_go//go:toolchain
ERROR: Analysis of target '//library/common:envoy_main_interface_lib' failed; build aborted: no matching toolchains found for types @io_bazel_rules_go//go:toolchain
```

Revert "bazel: change bazelisk for M1 support (#1966)"

---

RELEASE.md

Risk Level: n/a
Testing: no
Docs Changes: yes
Release Notes: no

docs: addding release notes instructions

---

bazel/envoy_mobile_repositories.bzl

Also fixes a build error for those of us with pedantic compilers

bump boringssl to Envoy's version

---

library/common/extensions/filters/http/platform_bridge/filter.cc
library/common/http/client.h
library/common/stream_info/extra_stream_info.cc
library/common/types/c_types.h
library/swift/FinalStreamIntel.swift

Description: Default timestamp to -1 for envoy_final_stream_intel
Risk Level: small
Testing: CI

Default timestamp to -1 for envoy_final_stream_intel

---

bazel/envoy_mobile_dependencies.bzl
test/java/org/chromium/net/CronetUrlRequestTest.java

Reduce the number of concurrent requests for CronetUrlRequestTest.testManyRequests to 1000.
This solves this crash:
```
[2022-01-23 17:01:31.159][9613895][critical][assert] [external/envoy/source/common/network/connection_impl.cc:604] assert failure: !connecting_.
```
This ran on a 2017 MacBookPro without errors:
```
bazel test --define=signal_trace=disabled --runs_per_test=1000 test/java/org/chromium/net:cronet_url_request_test
```
However, this PR does not solve the root cause, it only mitigates it. **It should not be possible for this ASSERT to fail**.
Description: EM has a 1024 concurrent request limit that is now respected by Cronet tests
Risk Level: N/A
Testing: Solves CI "android_tests / java_tests_mac" failure
Signed-off-by: Charles Le Borgne …

Solve CI flakiness for test/java/org/chromium/net/urlconnection:urlconnection_test 

---

.github/workflows/android_tests.yml

These jobs fail when run with remote execution but pass when run directly on GitHub Actions agents.

Run Kotlin macOS tests without EngFlow

---

bazel/envoy_mobile_repositories.bzl

Previous URL started returning a zip archive with a different checksum: https://github.com/bazelbuild/rules_android/issues/43

[deps] Update rules_android to a stable release URL

---

OWNERS.md

If I may be so bold, I'm adding myself as an owner and moving Michael Rebello to a new "Emiritus maintainers" section to match the structure and naming used by the Envoy project.

[OWNERS] Update Envoy Mobile owners

---

library/common/stream_info/extra_stream_info.cc
test/common/integration/client_integration_test.cc

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:

timing test

---

WORKSPACE
bazel/android_configure.bzl

So consumers can override which versions they want if it differs from the values used here.

bazel: Allow configuring Android toolchain versions

---

test/common/integration/BUILD

//test/common/integration:client_integration_test requires networking
which is not allowed by default. This allows the test to use the
localhost network.
Signed-off-by: Will <will@engflow.com>
Description: //test/common/integration:client_integration_test requires networking which is not allowed by default. This allows the  test to use the localhost network.
Testing: See  unit_tests  workflow
Fixes #2020

Fixed network policy of client_integration_test

---

library/common/jni/jni_utility.cc
library/common/stream_info/extra_stream_info.cc
library/common/types/c_types.h
library/java/io/envoyproxy/envoymobile/engine/EnvoyFinalStreamIntelImpl.java
library/java/io/envoyproxy/envoymobile/engine/types/EnvoyFinalStreamIntel.java
library/java/org/chromium/net/impl/CronetUrlRequest.java
library/kotlin/io/envoyproxy/envoymobile/FinalStreamIntel.kt
library/kotlin/io/envoyproxy/envoymobile/mocks/MockStream.kt
library/swift/FinalStreamIntel.swift
test/common/integration/client_integration_test.cc
test/common/stream_info/extra_stream_info_test.cc

Pure refactoring.
For consistency, request_start has also been renamed to stream_start.
Description: Rename request_end to stream_end, and adjust documentation.
Testing: CI

Rename request_end to stream_end, and adjust documentation.

---

.bazelrc
.gitignore
BUILD
bazel/android_artifacts.bzl
bazel/android_debug_info.bzl
library/common/jni/BUILD
library/kotlin/io/envoyproxy/envoymobile/BUILD

When building the jni dylib for android, we previously stripped all
debug info to decrease the artifact size. With this change we now
produce the same stripped binary as before, but before stripping it we
create a dump of the debug info suitable for crash reporting.
This is made overly difficult for a few reasons:
1. Bazel doesn't support fission for Android https://github.com/bazelbuild/bazel/pull/14765
2. Extra outputs from rules are not propagated up the dependency tree,
so just building `android_dist` at the top level, isn't enough to get
the extra outputs built as well
3. Building the library manually alongside the android artifact on the
command line results in 2 separate builds, one for android as a
transitive dependency of `android_dist` and one for the host
platform
This change …

bazel: Add custom rule to produce android debug info

---

.bazelrc
BUILD
bazel/android_debug_info.bzl
library/common/jni/BUILD

There are a few changes here:
1. Add back debug info disables for release, the info we were creating
here was ~6gb per architecture
2. Switch to just generating the symbol table which should be enough for
crash reporting, and compressed is only ~10mb per architecture
3. Remove a rouge `-Wl,-s` that made this not work at all with my
original change

bazel: Improve android symbol map generation

---

.gitignore
bazel/android_debug_info.bzl

This makes it clear it's a gzip archive

bazel: Rename objdump output

---

library/java/io/envoyproxy/envoymobile/engine/types/EnvoyHTTPCallbacks.java
library/objective-c/EnvoyEngine.h
library/objective-c/EnvoyHTTPStreamImpl.m
library/swift/StreamCallbacks.swift
library/swift/StreamPrototype.swift

Description: Adds the previously Kotlin-only feature to the iOS public interface.
Release Notes: Added onSendWindowAvailable callback on iOS for when explicit flow control is enabled. This brings it in line with the Kotlin API.

ios: add explicit flow control onSendWindowAvailable to public interface

---

library/objective-c/BUILD
library/objective-c/EnvoyEngineImpl.m

Right now the swift/obj-c targets cannot build on their own, relying on being wrapped in a ios_test or similar in order to
build with the right libraries. This makes some few surgical changes in order to let the targets build on their own. This opens up for running swift_binaries etc. that consume EM, with a few of the iOS specific bits disabled.
Risk Level: Low, macos only
Testing: Verified that we can build swift_binaries that target 
```
"@envoy_mobile//library/swift:ios_lib",
"@envoy_mobile//library/objective-c:envoy_engine_objc_lib",
```
on macos

support building swift/obj-c targets on macos

---

library/java/org/chromium/net/impl/CronetUrlRequest.java
test/common/integration/BUILD
test/common/integration/autonomous_upstream.cc
test/common/integration/autonomous_upstream.h
test/common/integration/quic_test_server.cc
test/common/integration/quic_test_server.h
test/java/io/envoyproxy/envoymobile/engine/testing/QuicTestServer.java
test/java/io/envoyproxy/envoymobile/engine/testing/QuicTestServerTest.java

Attempts to mimic this: https://source.chromium.org/chromium/chromium/src/+/main:components/cronet/testing/test_server/data/quic_data/simple.txt
The original QuicTestServer reads that file and caches it while booting up, and precomputes the full response out of it.
Description: provide a canned response to a specific request.
Risk Level: N/A - only changes test infrastructure
Testing: CI

Have QuicTestServer to support Cronet request

---

.github/lyft_maintainers.yml
.github/workflows/bump_support_rotation.yml
docs/Support.md
tools/bump_lyft_support_rotation.sh

This change includes:
* Documentation stating the purpose, function and reasoning behind the Lyft support rotation.
* A YAML file capturing the rotation list of GitHub user names and who's currently on rotation.
* A script to bump who's on rotation to the next person.
* A GitHub Action that runs weekly to automatically update who's on rotation.
There's a lot of room for growth in this system, such as posting who's on rotation to Slack, generating a calendar viewable in Google Calendar or other calendar clients, automatically assigning PRs, extending to have rotations for different companies or project areas etc.

[Project] Establish a Lyft support rotation

---

.bazelrc
WORKSPACE
bazel/envoy_mobile_repositories.bzl

These are the different low hanging fruit fixes to reduce the dynamic library size. Note wins were calculated in isolation against a fixed target for just one architecture so they are not necesarily additive.
- remove api v2 dependency (Mostly done here: https://github.com/envoyproxy/envoy/pull/18817)
- Estamated wins: -1.8Mi
- compile optimizing for size
- [commit c2d7084] Estimated wins: -0.66Mi
- set default visibility to hidden
- [commit ed2975e] Estimated wins: -5.66Mi
- override pgv validations with NOP functions
- [commit 255eb5a] Estimated wins: -3.7Mi
**For the measured case (a few months back) the size reduction accounted for about -46.2%**
This PR is better reviewed commit by commit.

size: optimizations for dynamic library

---

library/common/config/config.cc
library/java/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java
library/objective-c/EnvoyConfiguration.m
test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt
test/swift/EngineBuilderTests.swift

Description: In addition to needing the DNS lookup family to be set to ALL, it turns out Happy Eyeballs also requires a runtime flag (`envoy.reloadable_features.allow_multiple_dns_addresses`) to be enabled to function.

happy eyeballs: fix missing runtime configuration

---

library/common/config/config.cc
library/java/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java
library/java/org/chromium/net/impl/NativeCronetEngineBuilderImpl.java
library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt
test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt
test/java/org/chromium/net/testing/BUILD
test/java/org/chromium/net/testing/CronetTestRule.java
test/java/org/chromium/net/testing/Http2TestServer.java
test/java/org/chromium/net/testing/Http2TestServerTest.java

PLEASE READ
- With this PR, only one `UpstreamTlsContext` supports the configurable `trust_chain_verification`:  [`&base_tls_h2_socket`](https://github.com/envoyproxy/envoy-mobile/blob/v0.4.5.02082022/library/common/config/config.cc#L112). The other one, `&base_tls_socket`, does not.
- `&base_tls_h2_socket` has been inlined. Consequently, `&base_tls_h2_socket` does not exist anymore. Unfortunately, when a config variable is assigned in the Java code, it won't get substituted when encountered inside another config variable.
- Swift/objective-c/c++ configuration classes were not updated. Only Java and Kotlin were.
Description: Allow tests to avoid TLS Cert Verification
Risk Level: Small
Testing: New test and CI
Signed-off-by: Charles Le Borgne …

Add test support for H2

---

library/common/config/config.cc
library/common/http/client.cc
library/java/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java
library/java/org/chromium/net/impl/NativeCronetEngineBuilderImpl.java
library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt
library/objective-c/EnvoyConfiguration.m
library/objective-c/EnvoyEngine.h
library/swift/EngineBuilder.swift
test/common/http/client_test.cc
test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt
test/kotlin/io/envoyproxy/envoymobile/EngineBuilderTest.kt
test/swift/EngineBuilderTests.swift

Description: Adds public API and support for providing a list of domains to which H2 connections will be established *without* protocol negotiation (i.e. ALPN). See Envoy docs for the domain name patterns supported:
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-route
Testing: Unit
Co-authored-by: Mike Schore <mike.schore@gmail.com>

engine builder: add option to add a list of H2-Raw domain names

---

examples/swift/async_await/ContentView.swift

It was never safe to do a case-sensitive lookup, but this broke in https://github.com/envoyproxy/envoy-mobile/pull/2088#issuecomment-1064237716.
|Before|After|
|-|-|
|![Simulator Screen Shot - TestDevice - 2022-03-10 at 11 16 00](https://user-images.githubusercontent.com/474794/157707093-fe1db924-c91a-4258-870a-52945de306f0.png)|![Simulator Screen Shot - TestDevice - 2022-03-10 at 11 09 32](https://user-images.githubusercontent.com/474794/157707086-5f837a47-9f68-43f7-9630-43bfe6bc52cc.png)|

Fix iOS async/await example app

---

WORKSPACE
bazel/envoy_mobile_repositories.bzl
library/common/http/client.h

update envoy to latest

---

.github/workflows/android_build.yml
ci/mac_ci_setup.sh

It takes a very long time to download and install the Android NDK & build tools so we should skip it if it's not needed.

[CI] Only install Android tool dependencies when needed

---

bazelw

Description: Modifies the `bazelw` shell script to bootstrap `bazelisk` for arm64 on both Darwin and Linux. This unblocks work to re-enable Python builds for py-envoy-mobile internally. Note that this may not work until #2085 is in, as (iirc) it includes fixes to arm64 builds for Envoy.
Testing: No unit testing, but tested on arm64 both on macOS (natively) and Linux (Docker). See below. I don't have an x86_64 laptop on hand at the moment, so if someone wouldn't mind checking that this still works on x86_64, that'd be much appreciated!
<details>
<summary>macOS</summary> …

builds: make bazelw support arm64 builds

---

docs/root/intro/version_history.rst
library/java/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java
test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt

Description: [StringJoiner](https://developer.android.com/reference/java/util/StringJoiner) was added in Android API level 24 but we still support back to API level 21, so this results in `NoClassDefFoundError` errors on devices running older Android versions.
Risk Level: Medium, this code is simple and unit tested.
Testing: Existing unit tests
Release Notes: Added

[Android] Replace uses of `StringJoiner` with `StringBuilder`

---

bazelw

See https://github.com/envoyproxy/envoy-mobile/issues/2101

[bazelw] Use amd64 binary on darwin-arm64

---

library/common/bridge/utility.cc
library/common/config/config.cc
library/common/engine.cc
library/common/extensions/filters/http/local_error/filter.cc
test/swift/integration/IdleTimeoutTest.swift

update envoy to 82b1f66

---

library/common/config/config.cc

Includes https://github.com/envoyproxy/envoy/pull/19758 so we now need to set the config option.
Will wait until @snowp resolves the upstream break in https://github.com/envoyproxy/envoy-mobile/pull/2105 to land this

envoy: c911818721586

---

.swiftlint.yml
library/objective-c/EnvoyConfiguration.m
library/objective-c/EnvoyEngine.h
library/swift/EngineBuilder.swift
test/swift/EngineBuilderTests.swift

Description: Adds feature parity to the Android/JVM engine builder, and allows TLS trust chain verification to be bypassed.
Testing: Unit & CI

ios: add support for toggling trust chain verification

---

.bazelrc
docs/root/intro/version_history.rst
library/objective-c/BUILD
library/objective-c/EnvoyEngineImpl.m
library/objective-c/EnvoyNetworkMonitor.m

Enable path monitor reachability state observation on both iOS and macOS.
It was disabled in https://github.com/envoyproxy/envoy-mobile/pull/2052 because we didn't have a minimum macOS version set but this API is available as of 10.14.
It seems the `@platforms//os:macos` condition meant that the host was macOS, not that the compilation target was macOS.
Risk Level: Low, re-enabling something that was enabled until fairly recently.
Testing: Validated that preferred network changes are logged when toggling WiFi on/off in the Swift example apps on a physical iPhone. Also confirmed that the library still builds for macOS with `./bazelw build //library/objective-c:envoy_engine_objc_lib --config=macos`.
Release Notes: Added.

[iOS/macOS] Fix reachability

---

library/objective-c/EnvoyEngineImpl.m
library/objective-c/EnvoyNetworkMonitor.m

Description: `TARGET_OS_MAC` is defined on iOS, but is not truth-y, so the previous checks were not sufficient.
Risk Level: Low, re-enabling something that used to be enabled on iOS.
Testing: Verified in our sample apps that WLAN/WWAN interfaces are properly logged when reachability changes.
Docs Changes:
Release Notes:

[iOS] Fix macOS/iOS compiler conditionals

---

library/common/config/config.cc
library/java/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java
library/java/org/chromium/net/impl/NativeCronetEngineBuilderImpl.java
library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt
library/objective-c/EnvoyConfiguration.m
library/objective-c/EnvoyEngine.h
library/swift/EngineBuilder.swift
test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt
test/kotlin/io/envoyproxy/envoymobile/EngineBuilderTest.kt
test/swift/EngineBuilderTests.swift

Description: Add EngineBuilder options for configuring minimum DNS refresh rate and per-host max connections.
Testing: Unit & CI

api: new dns and connection configuration options 

---

library/common/config/config.cc

Description: This plays nicer with some upstreams that have this commonly configured as default because it preemptively allows for local queueing to occur and/or additional  connections to be utilized. However we should iterate and consider the following improvements:
1. make globally configurable
2. make configurable per-host
3. remember server settings for next time
Risk: Low
Testing: Local

config: temporarily hardcode h2 max concurrent streams to 100

---

CONTRIBUTING.md

Signed-off-by: Will Martin <will@engflow.com>
Description: Update CONTRIBUTING.md to specify that you must initialize sub-repos before setting up DCO.
Testing: N/A
Docs Changes: Added a line to CONTRIBUTING.md

Update CONTRIBUTING.md to include updating subrepos

---

library/common/config/config.cc

Description: Modify config to enable more metrics. Mainly focused on downstream requests, DNS updates and h2 ping timeouts. The changes add around 44 new metrics (a move from around 250 to around 290).
Testing: N/A

stats: enable more metrics

---

bazel/flatbuffers.bzl
bazel/kotlin_lib.bzl

This allows the pom rule to pick up the dependency, ensuring that it gets included in the <dependency> stanza of the final Envoy POM file. 
Risk Level: Low, build only
Testing: Generated the POM file and verified flatbuffers-java now appear

build: export flatbuffer jvm dep

---

.bazelrc

This was added ages ago for local build performance. This breaks
rules_rust currently because of https://github.com/bazelbuild/rules_rust/issues/1244
I did a test and the clean build time of `ios_dist` was 687s with
sandboxing disabled, and 705s with it enabled on my M1 Max MBP. I think
this is small enough that we can remove this for now to enable using
rust, and revisit in the future if that issue is fixed.

bazel: remove sandbox disable

---

bazel/android_debug_info.bzl

Description: Generate symbol mapping file as opposed to symbol table mapping file as it contains more information. Bugsnag's guide explaining the difference between symbol table mapping files and symbol mapping files and how  to generate the latter can be found at https://docs.bugsnag.com/api/ndk-symbol-mapping-upload/#uploading-mapping-files. 
See this Bugsnag Android Github issue https://github.com/bugsnag/bugsnag-android/issues/1609.
Risk Level: Low, affects debugging features only, not production code
Testing: N/A

ci: create symbol mapping file

---

library/cc/stream.cc
library/cc/stream.h
library/cc/stream_prototype.cc
library/common/jni/android_jni_interface.cc
library/common/jni/android_test_jni_interface.cc
library/common/jni/jni_interface.cc
library/common/main_interface.cc
library/common/main_interface.h
library/java/io/envoyproxy/envoymobile/engine/AndroidEngineImpl.java
library/java/io/envoyproxy/envoymobile/engine/AndroidJniLibrary.java
library/java/io/envoyproxy/envoymobile/engine/AndroidNetworkMonitor.java
library/java/io/envoyproxy/envoymobile/engine/EnvoyEngine.java
library/java/io/envoyproxy/envoymobile/engine/EnvoyEngineImpl.java
library/java/io/envoyproxy/envoymobile/engine/EnvoyHTTPStream.java
library/java/io/envoyproxy/envoymobile/engine/JniLibrary.java
library/java/io/envoyproxy/envoymobile/engine/types/BUILD
library/java/io/envoyproxy/envoymobile/engine/types/EnvoyNetworkType.java
library/kotlin/io/envoyproxy/envoymobile/mocks/MockEnvoyEngine.kt
library/kotlin/io/envoyproxy/envoymobile/mocks/MockEnvoyHTTPStream.kt
library/objective-c/EnvoyEngine.h
library/objective-c/EnvoyEngineImpl.m
library/objective-c/EnvoyHTTPStreamImpl.m
library/objective-c/EnvoyNetworkMonitor.m
library/swift/mocks/MockEnvoyEngine.swift
library/swift/mocks/MockEnvoyHTTPStream.swift
library/swift/mocks/MockStreamPrototype.swift
test/common/engine_test.cc
test/common/main_interface_test.cc

In preparation for removing the singleton. This is split off into its own independent change to minimize the scope of the main singleton removal work.
We were already doing this in many places, this just adds more instances of passing the engine handle so we do so comprehensively.
Description: Pass engine handles throughout API
Risk Level: Medium, changing some JNI interfaces, removing some static state
Testing: Unit tests and sample apps
Docs Changes: N/A internal only
Release Notes: N/A internal only

internal: pass engine handles throughout API

---

library/common/jni/BUILD

When working on rust support we hit this issue
https://github.com/rust-lang/compiler-builtins/issues/353 which seems to
still be persistent even in the case you have the nightly version
mentioned there. I haven't been able to reproduce the issue in a
separate project, but the core seems to be that both libgcc and rust's
compiler builtins module vendor some float math symbols and both are
included. This change is as scoped as possible so that no real issues
could sneak in with this disabled, which should mostly be covered by
only passing this for the single arch.

bazel: Allow multiple definitions for armeabi android links

---

bazel/envoy_mobile_dependencies.bzl

This changes the conflict resolution policy of maven_install to pin, and specifies all the Kotlin libs by default. This ensures that dependent projects that add more deps won't result in Kotlin dependencies that conflict with the ones brought in by the Kotlin rules

pin maven dependencies

---

.bazelrc
library/common/config/config.cc
library/common/extensions/key_value/platform/config.cc
library/common/extensions/key_value/platform/config.h
library/common/extensions/key_value/platform/platform.proto
test/common/extensions/key_value/platform/platform_store_test.cc
test/kotlin/integration/SetLoggerTest.kt
test/swift/integration/SetLoggerTest.swift

Propagates the new platform mappings command, fixes the platform k-v store and updates the config now that a typed_config is required

bump envoy to 5181d2355f208061688922572727fe06ba8b3a07

---

library/common/http/client.cc

Description: Adds a debug log statement to help more clearly indicate when the a stream has been cancelled via the programmatic API. Additionally, noticed that the cancellation callback could theoretically be called for a manual stream that was not currently open, and moved the call into the guard.
Testing: CI

http client: add cancel log and limit callback to open streams

---

.bazelrc

I asked around and it sounds like these flags have no downside, but when
we only set them for remote exec, if you swapped between using remote
exec and then not using it, it would invalidate your build and you'd
rebuild the world. I'm hoping we can fix this rough edge in bazel but in
the meantime it should be safe to set them globally.
https://github.com/bazelbuild/bazel/pull/15203
https://github.com/bazelbuild/bazel/pull/15204

bazel: set inmemory remote exec flags globally

---

library/common/jni/BUILD

This allows depending on jni_interface.cc as a standard cc library
Risk Level: Low, test only (JVM target)

extract jni lib out of cc_binary 

---

.github/workflows/artifacts.yml

Fix CI setup command for `main_android_dist_ci` GitHub Action

---

docs/root/development/releasing/releasing.rst

These had expired, and rather than have to hunt around the Internet for how to renew them when this happens again in 2024, document the steps here.

Add documentation on renewing GPG keys

---

.github/workflows/ios_tests.yml
envoy_build_config/extensions_build_config.bzl
library/common/config/config.cc
library/common/config/templates.h
library/common/http/client.cc
library/common/jni/jni_interface.cc
library/java/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java
library/java/io/envoyproxy/envoymobile/engine/EnvoyEngineImpl.java
library/java/io/envoyproxy/envoymobile/engine/JniLibrary.java
library/java/org/chromium/net/impl/NativeCronetEngineBuilderImpl.java
library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt
test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt

Description: Adds *experimental* support for negotiating H3/QUIC connections. To enable this, `enableHttp3` must be set to true on the EngineBuilder AND the header "x-envoy-mobile-upstream-protocol" must be set to "http3" on the request. If the upstream does not support H3, the standard ALPN over TCP configuration will still be used by default.
Testing: Updated Unit Coverage
Co-authored-by: Alyssa Wilk <alyssar@chromium.org>

h3/quic: add experimental option to the Android/JVM EngineBuilder

---

BUILD

Description: a061f3dcdd2cdeec50a171973eabf0660bc9a8c6 caused build failures when attempting to build the android_dist target locally. This ensures the target can write the to the `dist/` directory when built.

build: set 'local' tag on android_dist builds

---

bazel/apple_test.bzl
bazel/config.bzl
examples/objective-c/hello_world/BUILD
examples/swift/hello_world/BUILD
library/swift/BUILD
test/swift/apps/baseline/BUILD
test/swift/apps/experimental/BUILD

This way we make sure the examples stay in sync with the framework

bazel: Add constant for minimum iOS version

---

bazelw

Now that we've pulled in https://github.com/envoyproxy/envoy/pull/20852, I'm no longer seeing linker errors when running Swift tests for iOS as reported in https://github.com/envoyproxy/envoy-mobile/issues/2101.
Risk Level: Low to the libraries, Moderate to local development on an M1 Mac.
Testing: `./bazelw test //test/swift:test --config=ios` passes

[bazelw] Use arm64 binary on darwin-arm64

---

docs/root/development/releasing/releasing.rst

From `mmddyy` to `yyyymmdd`, which is less ambiguous and sorts chronologically.
As discussed in the community meeting earlier today.

Update pre-release versioning scheme documentation

---

.github/workflows/artifacts.yml

* Drop the "v" prefix from versions in the pom file
* Build Android release for more architectures: `x86` -> `x86,x86_64,armeabi-v7a,arm64-v8a`
Fixes https://github.com/envoyproxy/envoy-mobile/issues/2109
Risk Level: Low, we haven't published Maven releases in two years
Testing: Ran the GitHub Actions, verified pulling the release from Maven
Central in an Android app project in Android Studio.
Release Notes: Pending...

Fix Maven deploy CI job

---

.github/workflows/ios_tests.yml
envoy_build_config/extensions_build_config.bzl
library/common/config/config.cc
library/common/config/templates.h
library/common/http/client.cc
library/common/jni/jni_interface.cc
library/java/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java
library/java/io/envoyproxy/envoymobile/engine/EnvoyEngineImpl.java
library/java/io/envoyproxy/envoymobile/engine/JniLibrary.java
library/java/org/chromium/net/impl/NativeCronetEngineBuilderImpl.java
library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt
test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt

Description: This reverts commit b08883bc90b53e55a7dac2c8baef14e5e34cd376. We were able to confirm the crash we saw with our integration was specific to our integration and not to the public implementation.
Testing: Manual & CI

h3/quic: re-add experimental option to enable on Android/JVM

---

.bazelrc

Description: Include debug info in the Android release binary. This allows us to have an objdump file with all of the relevant symbols. The change is needed as we moved from symbol mapping table files to symbol mapping files in https://github.com/envoyproxy/envoy-mobile/commit/f955257e940b7bf3a9f4463fd2f061d3eea6f6ea
Risk Level: low, tooling only
Testing: N/A

bazel: Include debug info in Android release binary

---

library/java/org/chromium/net/impl/AtomicCombinatoryState.java
library/java/org/chromium/net/impl/BUILD
library/java/org/chromium/net/impl/CronetUrlRequest.java
test/java/org/chromium/net/impl/AtomicCombinatoryStateTest.java
test/java/org/chromium/net/impl/BUILD
test/java/org/chromium/net/testing/Http2TestServer.java

At the end of a request, mRequestFinishedListener is used to post the CronetMetrics. Before doing so, two events must have occurred first: the "final user callback" and the "final Network callback". The Thread involved with the last of these two events is in charge of the posting the CronetMetrics - this is intrinsically racy. This PR ensures a proper behaviour.
Description: Solves CI test flakiness: unexpected java_tests_mac failure: test/java/org/chromium/net:net_tests 
Risk Level: N/A (Cronet is still in development)
Testing: CI, and local multi runs
Fixes #2136

Fix race condition when posting CronetMetrics

---

library/common/http/client.cc

Description:  Solves more CI test flakiness: unexpected java_tests_mac failure: test/java/org/chromium/net:net_tests
Risk Level: Small
Testing: CI, multiple local runs
Fixes #2192 

Fix race condition when saving FinalStreamIntel

---

bazel/apple_test.bzl

These should only ever be used by tests, so if they depend on testonly
libraries this is required.

bazel: make test swift_library testonly

---

bazel/envoy_mobile_repositories.bzl

No longer needed as Envoy's is newer and this version is breaking
private fuzz tests.

build: remove rules_python override

---

docs/root/start/building/building.rst

I only saw the sources when I checked this the first time, without realising sources contains the prebuilt AAR.
Description: Clarify the release artifact in markdown docs.
Testing: None
Docs Changes: markdown change
Release Notes: Clarify the release artifact name

Clarify the release artifact

---

.github/workflows/android_build.yml
.github/workflows/android_tests.yml
.github/workflows/core.yml
.github/workflows/format.yml
.github/workflows/ios_build.yml
.github/workflows/ios_tests.yml
.github/workflows/release.yml
.github/workflows/release_validation.yml
ci/mac_ci_setup.sh

https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md
This is a pre-requisite for updating to the latest Xcode version (#2100)
Risk Level: Low, some tools we rely on may change versions
Testing: Locally for 2-3 months

ci: Update macOS version to macOS 12

---

bazel/kotlin_lib.bzl

The genrule doesn't work well with sandboxing on Linux since we're modifying files we're not supposed to touch:
```
chmod: changing permissions of 'bazel-out/aarch64-dbg/bin/loop/test/kt/io/envoyproxy/loop/logging/libloop_test_lib.so': Read-only file system
```
This simplifies the rule to just copy the .so into a .jnilib.
Risk Level: Low, build only

build: simplify jnilib copy

---

.bazelrc
bazel/android_debug_info.bzl

Description: The new files turned out to be so big (1.1GB each, 4 of them total) that using them may lead to pipeline issues. We are moving back to using symbol mapping table files and may revisit using symbol mapping files again after we figure out aforementioned pipeline issues.
Testing: N/A

bazel: move back to symbol mapping table files

---

docs/root/api/starting_envoy.rst
docs/root/intro/version_history.rst
library/common/config/config.cc
library/common/engine.cc
library/java/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java
library/java/org/chromium/net/impl/NativeCronetEngineBuilderImpl.java
library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt
library/objective-c/EnvoyConfiguration.m
library/objective-c/EnvoyEngine.h
library/swift/EngineBuilder.swift
test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt
test/kotlin/apps/experimental/MainActivity.kt
test/kotlin/io/envoyproxy/envoymobile/EngineBuilderTest.kt
test/swift/EngineBuilderTests.swift
test/swift/apps/experimental/ViewController.swift

Diff: https://github.com/envoyproxy/envoy/compare/03f23769d19e1baaf37fe52dcfe3f840429f9d06...d0befbbb952c979782857bdb986bec562d9a3c2f
To Do:

envoy: update to `d0befbb` & add `h2ExtendKeepaliveTimeout`

---

.github/workflows/android_build.yml
ci/mac_start_emulator.sh

This is much more common than 32 bit, so it makes sense to test for this over x86

use 64 bit emulators for test

---

bazel/envoy_mobile_repositories.bzl
tools/check_format.sh

This will make it easier to run locally in addition to CI where it's already running.

format: add SwiftLint to check-format script

---

.github/actions/retest-action/Dockerfile
.github/actions/retest-action/action.yml
.github/actions/retest-action/entrypoint.sh
.github/workflows/commands.yml

Commenting `/retest` on a PR will re-run failed jobs in its GitHub Actions workflows.
Copied from https://github.com/containernetworking/plugins.

ci: add support for `/retest` command

---

bazel/envoy_mobile_repositories.bzl

Released here: https://github.com/bazelbuild/rules_apple/releases/tag/0.34.2
This is needed to update to bazel 6.x

Bump rules_apple to 0.34.2

---

library/common/network/configurator.cc
library/common/network/configurator.h
test/common/network/configurator_test.cc

Description: Limits connection draining to be based on specific hosts as each host's DNS resolution occurs following a triggered DNS refresh.
Testing: Additional Unit Coverage

network: perform post-DNS connection drain on a per-host basis

---

library/common/http/client.cc

cleanup: remove comment in Http::Client that no longer applies

---

library/common/jni/jni_interface.cc

The Java side expects an `int` return value: https://github.com/envoyproxy/envoy-mobile/blob/c930fec015c363e2a6db56f93635beddba19fa5f/library/java/io/envoyproxy/envoymobile/engine/JniLibrary.java#L323

jni: fix mismatched return value types

---

tools/bump_lyft_support_rotation.sh

Got this error when bumping this morning:
```
{"ok":false,"error":"channel_not_found","warning":"missing_charset","response_metadata":{"warnings":["missing_charset"]}}
```
Logs: https://github.com/envoyproxy/envoy-mobile/runs/6258460166?check_suite_focus=true

Fix `bump_lyft_support_rotation.sh` posting to Slack

---

library/java/org/chromium/net/impl/BUILD
library/java/org/chromium/net/impl/CancelProofEnvoyStream.java
test/java/org/chromium/net/impl/BUILD
test/java/org/chromium/net/impl/CancelProofEnvoyStreamTest.java

Description: Wrapper for the EnvoyStream guaranteeing that a another stream method can't be called after a "cancel"
Risk Level: None - Cronvoy only
Testing: CI

CancelProofEnvoyStream

---

library/java/org/chromium/net/impl/CancelProofEnvoyStream.java
library/java/org/chromium/net/impl/CronetBidirectionalStream.java
test/java/org/chromium/net/BidirectionalStreamTest.java

Description: Add comments
Testing: N/A
fixes: #1642

Add comments to CronetBidirectionalStream

---

bazel/envoy_mobile_dependencies.bzl

Following up https://github.com/envoyproxy/envoy-mobile/pull/2249 to update the standard libraries to 1.6.21
Signed-off-by: Benjamin Lee <ben@ben.cm>

Update Kotlin standard libraries to 1.6.21

---

docs/root/intro/version_history.rst
library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt
test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt

Description: After experimenting with it in Lyft apps we saw a positive impact of enabling filtering. It's enabled to all Lyft users who have EM enabled.
Risk Level: Low, experimented with.
Testing: N/A
Docs Changes:  Done
Release Notes: Done

configuration: filter unroutable addresses on Android by default

---

docs/root/intro/version_history.rst

I found these while looking at the changeset since 0.4.6.

Add version history entries for user-facing changes

---

bazel/kotlin_test.bzl

tests: add -Xcheck:jni to kotlin integration tests by default

---

docs/root/development/debugging/ios_local.rst

I'm not very familiar with reST so I'm not sure if this is correct, but it does remove the following warning:
> WARNING: Mismatch: both interpreted text role prefix and reference suffix

docs: fix sphinx reference mismatch warning

---

.gitattributes

From https://git-scm.com/docs/git-merge-file
> Instead of leaving conflicts in the file, resolve conflicts favouring our (or their or both) side of the lines.
Also see this blog post: https://about.gitlab.com/blog/2015/02/10/gitlab-reduced-merge-conflicts-by-90-percent-with-changelog-placeholders/

git: avoid merge conflicts when adding changelog entries

---

docs/root/api/starting_envoy.rst
docs/root/intro/version_history.rst
library/common/config/config.cc
library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt
library/swift/EngineBuilder.swift
test/kotlin/apps/experimental/MainActivity.kt
test/swift/apps/experimental/ViewController.swift

net: enable happy eyeballs by default

---

tools/vscode_compdb.sh

Running tools/vscode_compdb.py to generate the code completion symbols for VSCode produces an error because the .bazelversion in Envoy may not be available in certain environments. The recommendation is to use bazelisk, but the compilation database script defaults to using bazel. This change enables the VSCode compilation database generation script to use bazelisk if it is available on the system; if not, it will use bazel.
Signed-off-by: Ali Beyad abeyad@google.com
Testing: local

tools: Enable the VSCode completion db to use bazelisk if available

---

.github/workflows/submodule_update.yml

We're currently 2.5 weeks behind, and there are a significant number of breaking changes to account for.
This would be easier to manage if we kept the updates smaller.

ci: add scheduled job to update Envoy weekly

---

bazel/envoy_mobile_repositories.bzl

Released here: https://github.com/buildbuddy-io/rules_xcodeproj/releases/tag/0.3.0

Update rules_xcodeproj to 0.3.0

---

BUILD
bazel/apple_test.bzl
experimental/swift/BUILD
experimental/swift/QUICStreamTest.swift
test/objective-c/BUILD
test/swift/BUILD
test/swift/integration/BUILD
test/swift/stats/BUILD

This list isn't comprehensive, but it's the most common targets in which I work with for the iOS side of things.
Note that it doesn't look like the Objective-C/C++ targets correctly reflect build failures right now, but you still get autocomplete and other IDE features.

xcode: add libraries & tests to Xcode project

---

docs/root/intro/version_history.rst

Fix spelling of Cronvoy in release notes which I broken in #2292.

Fix spelling of Cronvoy in release notes

---

library/common/config/config.cc

Switching off of deprecated http2 and watchdog configs. 
_Should_ be a functional no-op.
Risk Level:
Testing: no test changes

config: cleaning up deprecated configs

---

test/common/integration/BUILD
test/common/integration/client_integration_test.cc

Risk Level: n/a
Testing: test still passes
Docs Changes: n/a (test only)
Release Notes: n/a (test only)

mobile: moving the c++ integration test to use default config

---

third_party/android/ifaddrs-android.h

Reverts envoyproxy/envoy-mobile#2081
This broke detection of ipv6 interfaces.

Revert "android: use local addresses as opposed to prefix"

---

docs/root/intro/version_history.rst
library/common/extensions/filters/http/platform_bridge/BUILD
library/common/extensions/filters/http/platform_bridge/config.cc
library/common/extensions/filters/http/platform_bridge/filter.cc
library/common/extensions/filters/http/platform_bridge/filter.h
library/common/http/BUILD
library/common/http/client.cc
library/common/http/client.h
test/common/extensions/filters/http/platform_bridge/BUILD
test/common/extensions/filters/http/platform_bridge/platform_bridge_filter_test.cc

Description: Adds Envoy histograms (timers) to most platform-provided callbacks in the Http::Client and in PlatformBridge Filters. Beyond a hardcoded threshold (1s), a warn-level LOG_EVENT will be emitted for slow-to-execute callbacks.
Testing: Manual & Existing Coverage

instrumentation: add timers and warnings to platform callbacks

---

docs/root/start/building/building.rst

Signed-off-by: Andrés Felipe Barco Santa <andrez.fbs@gmail.com>
Description: Corrected documentation typo in environment variable for NDK path
Testing: N/A
Docs Changes: One character (from SDK to NDK) 
Release Notes:

docs: Corrected NDK typo in documentation for Android building requirements

---

test/kotlin/integration/GRPCReceiveErrorTest.kt

Fixes https://github.com/envoyproxy/envoy-mobile/issues/2301
Discussion: https://envoyproxy.slack.com/archives/C02F93EEJCE/p1653485522681549

kotlin: fix flaky grpc test

---

bazel/envoy_mobile_repositories.bzl

To pull in https://github.com/bazelbuild/rules_apple/pull/1478
```
Envoy.xcframework
├── Info.plist
├── ios-arm64
│ ├── Envoy.a
│ ├── Envoy.swiftmodule
│ │ ├── arm64.swiftdoc
│ │ └── arm64.swiftinterface
│ └── Headers
│     ├── Envoy.h
│     └── module.modulemap
└── ios-arm64_x86_64-simulator
├── Envoy.a
├── Envoy.swiftmodule
│ ├── arm64.swiftdoc
│ ├── arm64.swiftinterface
│ ├── x86_64.swiftdoc
│ └── x86_64.swiftinterface
└── Headers
├── Envoy.h
└── module.modulemap
```
Testing: Validated by pulling in this version in Xcode and running on device + simulator

bazel: update rules_apple

---

.github/workflows/release.yml

bazel uses zip as a container with no compression.
Reduces the size of the zip from 1.0GB to 352MB.
Testing: Ran the commands locally

Compress xcframework release asset

---

library/common/config/config.cc

stats: include new metrics in config

---

.github/workflows/release.yml
.gitignore
bazel/envoy_mobile_repositories.bzl
docs/root/intro/version_history.rst
library/swift/BUILD
tools/docc.sh

And include in GitHub release artifacts
Updates rules_swift to pull in https://github.com/bazelbuild/rules_swift/pull/838
When users open the archive, they'll have rich docs they can explore using Xcode's documentation navigator.
When we update to Xcode 13.4, we'll be able to generate HTML docs with this approach and publish to the documentation website. Here's a demo of what that static site looks like: https://envoy-mobile-docc-demo.netlify.app/documentation/envoy/
https://user-images.githubusercontent.com/474794/171704142-993072a3-fbc2-4db6-9c70-65e9e1a47aac.mp4
Testing: Local, CI
Docs Changes: Added
Release Notes: Added

swift: generate API docs as a DocC archive

---

.github/workflows/release.yml

Bazel's archive leads to bad CRC values.
Works around https://github.com/bazelbuild/rules_apple/issues/1489.

release: re-package xcframework zip

---

.bazelrc

Sometimes these downloads fail due to transient errors (example: https://github.com/envoyproxy/envoy-mobile/runs/6728606246?check_suite_focus=true) and a retry will succeed.
Configure the downloader to retry twice before giving up.
Fixes https://github.com/envoyproxy/envoy-mobile/issues/2337

bazel: retry repository downloads

---

test/common/integration/BUILD
test/common/integration/base_client_integration_test.cc
test/common/integration/base_client_integration_test.h
test/common/integration/client_integration_test.cc
test/common/integration/rtds_integration_test.cc

This test does a simple verification that the RTDS protocol within the
xDS family is working correctly.  A subsequent PR will improve upon the
test coverage.
As part of this change, the common parts of running a Envoy Mobile
client integration test were refactored out into a new
BaseClientIntegrationTest class.  Both ClientIntegrationTest and
RtdsIntegrationTest inherit from BaseClientIntegrationTest.
Testing: Test only PR

tests: Adds an RTDS integration test for Envoy Mobile

---

docs/root/intro/version_history.rst
library/objective-c/EnvoyConfiguration.m
library/objective-c/EnvoyEngine.h
library/objective-c/EnvoyEngineImpl.m
library/swift/BUILD
library/swift/EngineBuilder.swift
library/swift/KeyValueStore.swift
test/swift/EngineBuilderTests.swift

Description: Adds EngineBuilder API and internal support for registering a platform key-value store on iOS. Internally this may be leveraged for HTTP caching, endpoint protocol support caching, and use in filters.
Risk: Moderate
Testing: Updated coverage.

ios: add support for registering a platform KV store

---

docs/root/api/starting_envoy.rst
docs/root/intro/version_history.rst
library/kotlin/io/envoyproxy/envoymobile/BUILD
library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt
library/kotlin/io/envoyproxy/envoymobile/KeyValueStore.kt
library/kotlin/io/envoyproxy/envoymobile/android/SharedPreferencesStore.kt
library/kotlin/io/envoyproxy/envoymobile/extras/AndroidSharedPreferencesStore.kt
test/kotlin/apps/experimental/MainActivity.kt
test/kotlin/integration/KeyValueStoreTest.kt

Description: Updates the exposed KeyValueStore type to be a more traditional implementable interface, and provides a simple persisting implementation based on Android SharedPreferences.
Risk: Low
Testing: Application

android: create persistent SharedPreferences-based KV store

---

docs/root/api/starting_envoy.rst
docs/root/intro/version_history.rst
library/objective-c/EnvoyEngine.h
library/objective-c/EnvoyEngineImpl.m
library/swift/BUILD
library/swift/EngineBuilder.swift
library/swift/NetworkMonitoringMode.swift
library/swift/mocks/MockEnvoyEngine.swift
test/swift/EngineBuilderTests.swift

We may be interested in experimenting with network monitoring & interface switching completely disabled to assess the impact of this feature.
Disabling network switching is not something we recommend generally.
Risk Level: Low, adds the ability to disable network switching on an opt-in basis
Testing: Updated unit tests
Docs Changes: Added
Release Notes: Added

iOS: add a way to disable network monitoring

---

docs/root/development/performance/vpn_analysis.rst

Description: Update the list of clusters in docs.
Risk Level: None.
Testing: N/A

docs: update the list of clusters

---

.github/workflows/android_build.yml
ci/mac_ci_setup.sh

To account for recent changes to defaults: https://github.com/actions/virtual-environments/issues/5595

ci: update Android setup

---

.bazelrc
.github/workflows/release.yml
docs/root/intro/version_history.rst

Bitcode is all but dead at this point.
Here's a deprecation note from the Xcode 14 beta 1 release notes:
https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-14-release-notes
> Starting with Xcode 14, bitcode is no longer required for watchOS and
> tvOS applications, and the App Store no longer accepts bitcode
> submissions from Xcode 14.
> Xcode no longer builds bitcode by default and generates a warning
> message if a project explicitly enables bitcode: “Building with
> bitcode is deprecated. Please update your project and/or target
> settings to disable bitcode.” The capability to build with bitcode
> will be removed in a future Xcode release. IPAs that contain bitcode
> will have the bitcode stripped before being submitted to the App
> Store. Debug symbols for past …

iOS: stop embedding bitcode in releases

---

library/common/jni/jni_interface.cc

cleanup: consistently use nullptr in cc contexts

---

.github/workflows/bump_support_rotation.yml
.github/workflows/submodule_update.yml

Description: Improves security with respect to third-party actions. See:
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
I also read through the recent commits and updated to the latest release, since it contained a few bugfixes.
Risk: Low
Testing: CI

ci: pin external GitHub Action

---

library/common/config/config.cc
library/objective-c/EnvoyConfiguration.m

Replacing the default dns resolver in the config string to be correct for the OS in question.
Replaced overrides in the swift code now that the base config handles it.
Testing: existing tests should verify correctness
Release Notes: did not add

config: hopefully fixing C++ config default for apple

---

library/common/config/config.cc

These are already being filtered out of our stats inclusion list, so this isn't a user-facing change, but this is needed to support the singleton removal work in https://github.com/envoyproxy/envoy-mobile/pull/2129.
Splitting this out into its own PR to reduce the scope of the singleton removal change.
Testing: None
Docs Changes: N/A, not a user-facing change
Release Notes: N/A, not a user-facing change

stats: disable global stats in config

---

test/common/integration/base_client_integration_test.h

test cleanup

---

BUILD
WORKSPACE
bazel/envoy_mobile_repositories.bzl
docs/root/development/debugging/ios_local.rst
examples/BUILD
examples/swift/async_await/BUILD
examples/swift/hello_world/BUILD
test/swift/apps/baseline/BUILD
test/swift/apps/experimental/BUILD

To simplify running sample iOS apps for physical devices.

bazel: use `device_and_simulator` rule

---

.github/workflows/android_build.yml
.github/workflows/ios_build.yml

Description: Platform specific CI jobs that run mobile applications have their timeouts set to 25 minutes. This is not enough to build Envoy Mobile itself and the apps that are used to verify that EM works as expected. Make CI jobs (that have timeouts equal to 25 minutes) depend on the 'main' CI job that's supposed to build Envoy Mobile binary and has a timeout of 90 minutes. This way, when platform specific CI jobs start they can reuse the cache that's populated by the CI job with timeout equal to 90 minutes.
Risk Level: N/A
Testing: N/A

ci: make CI jobs depend on Envoy build CI job

---

.drstring.toml
library/swift/Engine.swift
library/swift/EngineBuilder.swift
library/swift/EngineImpl.swift
library/swift/HeadersBuilder.swift
library/swift/KeyValueStore.swift
library/swift/PulseClient.swift
library/swift/RetryPolicyMapper.swift
library/swift/StreamPrototype.swift

It was missing the files in the `library/swift` directory.
Testing: Ran the DrString check, addressed the issues it found
Docs Changes: Updated

swift: fix docstrings and docstring linter

---

docs/root/api/starting_envoy.rst
docs/root/intro/version_history.rst
library/common/config/config.cc
library/java/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java
library/objective-c/EnvoyConfiguration.m
library/objective-c/EnvoyEngine.h
library/swift/EngineBuilder.swift
test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt
test/swift/EngineBuilderTests.swift
test/swift/apps/experimental/ViewController.swift

Mirroring what was done for Android in https://github.com/envoyproxy/envoy-mobile/pull/2379 and leveraging the recent changes in Envoy in https://github.com/envoyproxy/envoy/pull/21913.
Risk Level: Moderate.
Testing: Unit tests, integration tests & being exercised in the experimental app. Tested with the experimental app in the iOS Simulator and on an iPhone 13 Pro, verified that an IPv4 address gets mapped to a valid IPv6 address.
Docs Changes: Added.
Release Notes: Added.

iOS: add `forceIPv6(...)` builder option

---

test/common/integration/BUILD
test/common/integration/base_client_integration_test.cc
test/common/integration/base_client_integration_test.h
test/common/integration/rtds_integration_test.cc
test/common/integration/sds_integration_test.cc
test/common/integration/xds_integration_test.cc
test/common/integration/xds_integration_test.h

As part of this change, common xDS test functionality has been factored
out into the XdsIntegrationTest class, and both the SdsIntegrationTest
and RtdsIntegrationTest subclass XdsIntegrationTest.  Future xDS
integration tests should also subclass the XdsIntegrationTest to get the
common functionality and setup.

test: Adds an integration test for SDS

---

WORKSPACE

This upgrades `rules_foreign_cc` to a version including
https://github.com/bazelbuild/rules_foreign_cc/pull/938, which fixes
a build failure when the requested Apple SDK from `--xcode_version` does
not match the system's default Xcode's SDKs.
Example output:
```
rules_foreign_cc: Build failed!
rules_foreign_cc: Keeping temp build directory and dependencies directory for debug.
rules_foreign_cc: Please note that the directories inside a sandbox are still cleaned unless you specify --sandbox_debug Bazel command line flag.
rules_foreign_cc: Printing build logs:
_____ BEGIN BUILD LOGS _____
xcrun: error: SDK "macosx12.1" cannot be located
xcrun: error: SDK "macosx12.1" cannot be located
xcrun: error: unable to lookup item 'Path' in SDK 'macosx12.1'
+ XCODE_VERSION_OVERRIDE=13.2.1.13C100
+ …
```

Upgrade rules_foreign_cc

---

.pre-commit-config.yaml
docs/root/api/stats.rst
docs/root/intro/version_history.rst
library/java/org/chromium/net/CronetEngine.java
test/python/unit/test_pre_build_engine.py

Description: Update codespell to v2.1.0 due to an issue that surfaced in https://github.com/envoyproxy/envoy-mobile/pull/2400 : `/usr/local/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/codecs.py:905: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
file = builtins.open(filename, mode, buffering)`. According to https://github.com/codespell-project/codespell/issues/1331 the update is what fixes it.
Risk Level: Low, linting change only
Testing: N/A
Release Notes: Done

ci: update codespell to v2.1.0

---

bazel/envoy_mobile_repositories.bzl

https://github.com/buildbuddy-io/rules_xcodeproj/releases/tag/0.5.0
Testing: Local testing in Xcode

bazel: update rules_xcodeproj to 0.5.0

---

docs/root/intro/version_history.rst

Description: Updating version history to reflect user facing changes introduced in https://github.com/envoyproxy/envoy-mobile/pull/2400.
Testing: N/A

docs: update version_history

---

library/common/engine.cc

`ExtensionRegistry::registerFactories()` doesn't do any work at runtime, its purpose is to guarantee that the linker won't strip away these factories as dead code because they're discovered at runtime as opposed to being referenced statically.
So it's safe to call on engine creation because it's a no-op at runtime.

engine: remove outdated comment about `registerFactories()`

---

library/objective-c/EnvoyNetworkMonitor.m

And properly clean up reachability ref.
Testing: Validated using the memory graph debugger in Xcode with both reachability and path monitor modes

iOS: fix retain cycles in `EnvoyNetworkMonitor`

---

bazel/android_artifacts.bzl
bazel/apple_test.bzl
examples/objective-c/hello_world/BUILD
library/common/jni/BUILD
library/common/jni/import/BUILD
library/objective-c/BUILD
test/common/jni/BUILD
test/swift/integration/BUILD
third_party/rbe_configs/cc/BUILD

I'm removing rules_cc from
envoy as well https://github.com/envoyproxy/envoy/pull/19760 so this
mirrors that.

bazel: remove rules_cc references

---

docs/conf.py

Description: This change is an attempt to fix images in the generated documentation. As it is now they do not work - [example](https://envoy-mobile.github.io/docs/envoy-mobile/latest/development/debugging/android_local.html). The issues seems to be caused by the fact that Sphinx puts all of the images in `_images` directory and Github Pages, backed by `jekyll`, ignores all directories whose names start with `_`. The idea is to use `sphinx.ext.githubpages` extension that puts `.nojekyll` file in the root of the generated sphinx artifacts which is supposed to fix the issue as reported in https://stackoverflow.com/a/64544659. Not a great way to test this e2e locally so may need to revert the change if it turns out that the issue persists.
Risk Level: Low, documentation changes
Testing: …

docs: use sphinx githubpages extension

---

docs/root/intro/version_history.rst
envoy_build_config/extensions_build_config.bzl
library/cc/engine_builder.cc
library/cc/engine_builder.h
library/java/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java
library/java/org/chromium/net/impl/NativeCronetEngineBuilderImpl.java
library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt
test/cc/unit/envoy_config_test.cc
test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt
test/kotlin/apps/experimental/MainActivity.kt

For non-Apple platforms like Linux and Android.
Updated the Kotlin, Java & C++ builders.
Added here: https://github.com/envoyproxy/envoy/pull/22080
Risk Level: Low to moderate, off by default but I had to refactor some stuff.
Testing: Added.
Docs Changes: Documentation comments.
Release Notes: Added.

dns: allow using the `getaddrinfo`-based system DNS resolver

---

library/common/jni/jni_interface.cc
library/common/jni/jni_utility.cc

I currently see 3 build warnings when I try to build Envoy Mobile. 
```
INFO: From Compiling library/common/jni/jni_interface.cc:
library/common/jni/jni_interface.cc:1195:13: warning: unused function 'jvm_verify_x509_cert_chain' [-Wunused-function]
static void jvm_verify_x509_cert_chain(const std::vector<std::string>& cert_chain,
^
1 warning generated.
INFO: From Compiling library/common/jni/jni_utility.cc:
In file included from library/common/jni/jni_utility.cc:6:
In file included from external/envoy/source/common/common/assert.h:5:
In file included from external/envoy/source/common/common/logger.h:13:
external/envoy/source/common/common/fine_grain_logger.h:20:1: warning: inline variables are a C++17 extension [-Wc++17-extensions]
inline const char* kDefaultFineGrainLogFormat = …
```

Squelch two JNI build warnings

---

library/common/jni/android_jni_utility.cc

Fix isCleartextTrafficPermitted by finding a static method (instead of an object method) and calling 
the static method of the AndroidNetworkLibrary class instead of calling the instance method on a string.
Testing: Needs tests :)]

Fix isCleartextTrafficPermitted

---

docs/conf.py

Description: Revert https://github.com/envoyproxy/envoy-mobile/pull/2418 as the change did not fix the issues with images not appearing in documentation. https://github.com/envoy-mobile/envoy-mobile.github.io/pull/24 fixed the issues instead.
Risk Level: None. 
Testing: N/A

docs: revert "docs: use sphinx githubpages extension (#2418)"

---

docs/root/development/debugging/android_local.rst
examples/kotlin/hello_world/.bazelproject
examples/kotlin/hello_world/tools/android-studio-run-configurations/run_configuration_example_debug_arm64.xml

Description: Add an arm64 run configuration for Envoy example app so that it's possible to run and debug Envoy Mobile example app on ARM machines (i.e., M1 Macbooks). Following steps from https://envoy-mobile.github.io/docs/envoy-mobile/latest/development/debugging/android_local.html#adding-envoy-mobile-project-into-android-studio it's possible to set up an Android project that makes it possible to run and debug Envoy Mobile example app (put symbolic breakpoints in Envoy code). As it is now, the configured/added run configuration supports running of x86 builds only which do not work on ARM machines. 
Testing: Run new configuration locally on M1 Macbook.

tools: add arm64 debug run configuration

---

.bazelrc
examples/kotlin/hello_world/tools/android-studio-run-configurations/run_configuration_example_debug_arm64.xml
examples/kotlin/hello_world/tools/android-studio-run-configurations/run_configuration_example_debug_x86.xml

Description: Per our documentation, the following should be true "While breaking on a C++ function, Android Studio should present the source file and highlight the line where the breakpoint hit with all scope information". That feature did not work - I didn't confirm this but it's possible that the functionality was broken when https://github.com/envoyproxy/envoy-mobile/pull/2184 was merged. Anyway, the issue was that https://github.com/envoyproxy/envoy-mobile/blob/581ba40f2f8597243efccb2bdccade8193ff4559/.bazelrc#L44 config setting was not applied when Envoy Mobile was built for the runs of example apps. This has been fixed by making run configurations that are used by Envoy Mobile example apps specify `--config=dbg` setting explicitly.
Testing: Confirmed that Android …

tools: fix source mapping

---

bazel/envoy_mobile_repositories.bzl

Which will be needed when we update to the latest version of bazel: https://github.com/envoyproxy/envoy/pull/22295
Testing: CI

bazel: update rules_kotlin to v1.7.0-RC-2

---

bazel/envoy_mobile_dependencies.bzl
bazel/envoy_mobile_repositories.bzl

We were on a very old release. This is also going to be needed to update to the latest bazel 6.x release which we need to do to update Envoy.
Testing: CI, Lyft apps

bazel: update rules-proto-grpc to 4.1.1

---

README.md
docs/README.md
docs/publish.sh
examples/java/hello_world/README.md
examples/kotlin/hello_world/README.md
examples/objective-c/hello_world/README.md
examples/swift/hello_world/README.md
test/kotlin/apps/baseline/README.md
test/kotlin/apps/experimental/README.md
test/performance/test_binary_size.cc
test/swift/apps/baseline/README.md
test/swift/apps/experimental/README.md

New URL: https://envoymobile.io
Old URLs from https://envoy-mobile.github.io should redirect transparently.

docs: update website URL to envoymobile.io

---

library/common/jni/jni_interface.cc

Description: Release passed data to avoid a mem leak.
Risk Level: Low, proper handling of memory
Docs Changes: N/A 

jni: release data to avoid memory leak

---

.bazelrc
examples/kotlin/hello_world/MainActivity.kt
examples/kotlin/hello_world/tools/android-studio-run-configurations/run_configuration_example_debug_arm64.xml
examples/kotlin/hello_world/tools/android-studio-run-configurations/run_configuration_example_debug_x86.xml

Description: After finding an interface binding related crash in https://github.com/envoyproxy/envoy-mobile/pull/2456 I noticed that our `dbg`  bazel config does not specify `--define=include_ifaddrs=true` which is supposed to ensure that we compile code that's required for proper functioning of Envoy Mobile on Android. Introduce `dbg-android` and `dbg-ios` which are intended to be platform specific `dbg` configurations.
Risk Level: None, does not impact release configurations.
Testing: Ran Kotlin example app manually.

bazel: reorganize dbg configs

---

library/cc/bridge_utility.cc
library/common/http/header_utility.cc
test/common/integration/base_client_integration_test.cc
test/common/integration/base_client_integration_test.h
test/common/integration/client_integration_test.cc
test/common/integration/rtds_integration_test.cc
test/common/integration/sds_integration_test.cc
test/common/integration/xds_integration_test.cc
test/common/integration/xds_integration_test.h

In the commit https://github.com/envoyproxy/envoy-mobile/pull/2362 we added a `custom_headers_` field on the `BaseClientIntegrationTest` class to use for custom headers.  
This commit replaces that class field by instead instantiating a `custom_headers` object inside tests when necessary. Then adds a helper function to convert it from the `TestRequestHeaderMapImpl` (an easy to edit type) to `RequestHeaders` (envoy header type).
Signed-off-by: caschoener <schoener@google.com>

test: use TestRequestHeaderMapImpl for building custom headers

---

examples/kotlin/hello_world/MainActivity.kt

Description: Disable interface binding in Android Kotlin example app as we have no clear plans for enabling interface binding anytime soon and having it disabled makes debugging of the example app (and Envoy Mobile) easier. On top of that, the same feature is _not_ enabled in iOS example apps.
Risk Level: None, example app change only.
Testing: Example app run manually.
Release Notes: N/A 

example apps: disable interface binding

---

docs/build.sh

Description: [docs]: Added --no-deps for pip install in docs/build.sh
Testing: The docs built successfully
Release Notes:
Signed-off-by: Andrés Felipe Barco Santa <andres@engflow.com>

[docs]: Added --no-deps for pip install in docs/build.sh

---

.github/lyft_maintainers.yml

Description: Removing @goaway from the list of Lyft maintainers.
Testing: N/A

[CI] Remove a lyft maintainer

---

.github/actions/retest-action/entrypoint.sh

Previously it didn't retry all failed workflows, just one.
Risk Level: Low, CI automation only
Testing: I've verified locally that this works by running the script on this PR: https://github.com/envoyproxy/envoy-mobile/pull/2472
Docs Changes: N/A, not user facing
Release Notes: N/A, not user facing

ci: fix `/retest` command

---

BUILD
bazel/envoy_mobile_repositories.bzl

This will make it possible for us to define custom schemes.
Release info: https://github.com/buildbuddy-io/rules_xcodeproj/releases/tag/0.7.0
Risk Level: Low, local dev only
Testing: Local

bazel: update rules_xcodeproj to 0.7.0 release

---

BUILD
bazel/envoy_mobile_repositories.bzl
docs/root/development/debugging/ios_local.rst

This makes it much easier to find relevant schemes (there were over 2,000 schemes before this) and labels them with more descriptive and human-readable names than `__examples_swift_hello_world_app`.
```console
$ ls Envoy.xcodeproj/xcshareddata/xcschemes | wc -l
2231
$ ls Envoy.xcodeproj/xcshareddata/xcschemes | wc -l
7
```
New scheme picker looks like this:
<image  src=https://user-images.githubusercontent.com/474794/185428361-cb8b42a9-e7e1-4ddd-85db-a834b9796780.png width=250 />
I've separated the "Swift Library" scheme from the "iOS Tests" one because the Swift Library can be built for macOS too, but the tests only run on iOS.
If you want to build a scheme that's not in this list, you can quickly revert back to the previous behavior to generate schemes for all transitive dependencies by …

bazel: define custom Xcode schemes

---

library/java/org/chromium/net/BUILD
library/java/org/chromium/net/ChromiumNetManifest.xml
library/java/org/chromium/net/impl/CronvoyManifest.xml
library/java/org/chromium/net/urlconnection/URLConnectionManifest.xml

Signed-off-by: Renjie Tang <renjietang@chromium.org>
Description: Add a Cronvoy binary target for the integration of Cronet-dependent projects
Testing: build file only.

Add a binary build target for Cronvoy

---

library/proguard.txt

Description: Update proguard so that AndroidNetworkLibrary is not stripped/obfuscated by proguard. Needed to fix https://github.com/envoyproxy/envoy-mobile/issues/2432.
Risk Level: Low, the change should be additive.
Testing: Manual.

proguard: update rules to account for AndroidNetworkLibrary

---

library/common/jni/android_jni_interface.cc
library/common/jni/jni_utility.cc
library/common/jni/jni_utility.h
library/java/io/envoyproxy/envoymobile/engine/AndroidJniLibrary.java

Description: The change is needed in order for JNI to be able to find classes which are defined in our repository (as opposed to built in Java types). Google documents in [here](https://developer.android.com/training/articles/perf-jni#native-libraries) touches on this issue. The implementation could be improved by adding some caching to it but I am inclined to keep it simple unless we find out that its performance is an issue. Needed  for https://github.com/envoyproxy/envoy-mobile/issues/2432.
Risk Level: None, not used anywhere as of now.

jni: introduce custom find_class method

---

third_party/rbe_configs/config/BUILD

The old style will stop working in Bazel 6.0 (see https://github.com/bazelbuild/bazel/commit/3469784a4935c91b4ac22bcfed6be52e6dfec878)
Signed-off-by: Benjamin Peterson <benjamin@engflow.com>
Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:

Switch to using new-style Bazel platform constraints.

---

.github/workflows/android_tests.yml
.github/workflows/asan.yml
.github/workflows/cc_tests.yml
.github/workflows/coverage.yml
.github/workflows/format.yml
.github/workflows/perf.yml
.github/workflows/python_tests.yml
.github/workflows/release.yml
.github/workflows/tsan.yml

The `ubuntu-18.04` image has been deprecated: https://github.com/actions/runner-images/issues/6002
May explain why our Linux CI jobs started being cancelled before even starting. https://envoyproxy.slack.com/archives/C02F93EEJCE/p1661181247759129

ci: update GitHub Actions Linux runners to run on `ubuntu-latest`

---

library/common/jni/jni_interface.cc

Description: Avoid leaking config/log_level related strings. The leak happens during engine initialization.
Docs Changes:  N/A

jni: release strings after they are no longer needed

---

library/java/org/chromium/net/impl/CronetUrlRequestContext.java
test/java/org/chromium/net/CronetUrlRequestContextTest.java

Signed-off-by: Renjie Tang <renjietang@chromium.org>
Description: Modify version string of the Cronvoy native engine so that it matches https://source.chromium.org/chromium/chromium/src/+/main:components/cronet/android/java/src/org/chromium/net/impl/CronetUrlRequestContext.java;l=319?q=getversionstring&ss=chromium%2Fchromium%2Fsrc:components%2Fcronet%2F
Testing: n/a

Correct version string for CronetUrlRequestContext

---

library/common/jni/jni_utility.h

Description: Update the documentation of `find_class` method as it seems to accept `/` and `.` and using `/` should be less confusing as this is what `env->findClass` expects.
Testing: Manual confirmed that the current implementing of tagging works and it does uses `/` as opposed to `.`.
Signed-off-by: Rafał Augustyniak <Augustyniak@users.noreply.github.com>

docs: update find_class documentation

---

library/common/config/config.cc

Remove unnecessary google_re2 messages from config.cc in order to squelch runtime warnings about google_re2 being deprecated.
Risk Level: Low since this field is no longer needed after https://github.com/envoyproxy/envoy/pull/21633
Testing: Existing
Release Notes: None

Remove unnecessary google_re2 messages from config.cc

---

library/common/jni/android_jni_utility.cc
library/common/jni/android_test_jni_interface.cc
library/common/jni/jni_utility.h

Description: Update the implementation of `Java_io_envoyproxy_envoymobile_engine_AndroidJniLibrary_initialize` so that it takes a `class_loader` argument which was introduced in https://github.com/envoyproxy/envoy-mobile/pull/2483. It turns out that this method is implemented in two separate places - `android_jni_interface.cc` and  and `android_test_jni_interface.cc` files - and my previous PR updated only the former. This is needed to make `find_class` method work in tests as tests depend on  the implementation from `android_test_jni_interface.cc` file.
Risk Level: None, additive change for test targets only.
Testing: None, a follow up tests that depend on `find_class` method are being worked on.
Signed-off-by: Rafal Augustyniak …

testing: make find_class method work in tests

---

library/common/jni/android_jni_utility.cc
library/java/org/chromium/net/AndroidNetworkLibrary.java

Description: Fixes a crash https://github.com/envoyproxy/envoy-mobile/issues/2432
Risk Level: Low, it effectively does nothing other than returning `true` and should prevent the app from crashing

android: add an empty implementation of isCleartextTrafficPermitted

---

test/java/org/chromium/net/impl/CronvoyEngineTest.java
test/java/org/chromium/net/urlconnection/CronetInputStreamTest.java

Do not hard code MockWebServer url as it varies between "https://localhost:xxxx" or
"https://127.0.0.1:xxxx".
Signed-off-by: Chidera Olibie <colibie@google.com>
Description: For some reason, the mockwebserver url is not the same across board, so these tests were failing on my setup. So instead use the mockwebserver.url() method.
Risk Level: none: only touches Cronvoy
Testing: N/A

[Cronvoy] Remove hardcoded test url

---

docs/root/intro/version_history.rst
library/cc/engine_builder.h
library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt
test/cc/unit/envoy_config_test.cc
test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt
test/kotlin/apps/experimental/MainActivity.kt

Description: Rather than c-ares. In our tests, the system DNS resolver consumes less CPU and memory while otherwise performing similarly overall.
Risk Level: Medium, although it's performed well in our tests, it's possible that some situations we haven't tested perform worse than c-ares. Users can still disable this in the engine builder though.
Testing: Lyft apps & unit tests
Docs Changes: Docstrings updated to reflect new default
Release Notes: Added

android: default to use the system DNS resolver

---

docs/root/intro/version_history.rst
library/common/config/config.cc
test/kotlin/apps/experimental/MainActivity.kt
test/swift/apps/experimental/ViewController.swift

Description: Fix admin interface on Android. Enable admin interface in experimental example app.
Risk Level: low, admin interface is disabled by default and it's crashing on app launch on Android without the change from this PR anyway.
Testing: manual on iOS and Android
Docs Changes: none
Release Notes: updated

android: fix admin interface

---

ci/sonatype_nexus_upload.py

Follow-up on https://github.com/envoyproxy/envoy-mobile/pull/2526
Some instances were missed.
See https://github.com/envoyproxy/envoy-mobile/runs/8214998717?check_suite_focus=true

ci: fix Sonatype deploys

---

.bazelproject
docs/root/development/debugging/android_local.rst
examples/java/hello_world/.bazelproject
examples/java/hello_world/AndroidManifest.xml
examples/java/hello_world/tools/android-studio-run-configurations/run_configuration_example_debug_arm64.xml
examples/java/hello_world/tools/android-studio-run-configurations/run_configuration_example_debug_x86.xml
test/kotlin/apps/baseline/.bazelproject
test/kotlin/apps/baseline/AndroidManifest.xml
test/kotlin/apps/baseline/AsyncDemoFilter.kt
test/kotlin/apps/baseline/BUILD
test/kotlin/apps/baseline/BufferDemoFilter.kt
test/kotlin/apps/baseline/DemoFilter.kt
test/kotlin/apps/baseline/MainActivity.kt
test/kotlin/apps/baseline/tools/android-studio-run-configurations/run_configuration_example_debug_arm64.xml
test/kotlin/apps/baseline/tools/android-studio-run-configurations/run_configuration_example_debug_x86.xml
test/kotlin/apps/experimental/.bazelproject
test/kotlin/apps/experimental/AndroidManifest.xml
test/kotlin/apps/experimental/AsyncDemoFilter.kt
test/kotlin/apps/experimental/BUILD
test/kotlin/apps/experimental/BufferDemoFilter.kt
test/kotlin/apps/experimental/DemoFilter.kt
test/kotlin/apps/experimental/MainActivity.kt
test/kotlin/apps/experimental/tools/android-studio-run-configurations/run_configuration_example_debug_arm64.xml

Description: Make it easy to run all of the example apps. Previously it was possible to use Android Studio to run Kotlin example app. This PR adds support for: Java example app, baseline test example app and experimental test example app.
Risk Level: None, touches example apps only

android: make it easy to run all example apps

---

.github/workflows/android_build.yml

Description: baseline and experimental Android test apps were broken as part of https://github.com/envoyproxy/envoy-mobile/pull/2539.
Testing: CI
Docs Changes: N/A 
Release Notes: N/A 

ci: fix test apps

---

.github/workflows/android_build.yml
test/kotlin/apps/baseline/MainActivity.kt

This changes the kotlin baseline app to test HTTP requests rather than HTTPS
To do this we disable the async filter and buffer filter, as they do not handle responses without bodies properly.
Testing: yes

changing   kotlin baseline to test HTTP

---

library/common/config/config.cc

Description: The change is needed for EM to emit virtual cluster stats. It used to work but was broken as part of https://github.com/envoyproxy/envoy-mobile/issues/2530 where we increase the number of virtual hosts from 1 to 2 and changed the name of the existing virtual host (which used to be called `api`).
Risk Level: Low, enables additional instrumentation
Testing: Manual using admin interface and curling `stats` endpoint.

config: update stats regex

---

library/java/org/chromium/net/AndroidNetworkLibrary.java

The java changes from the initial PR (https://github.com/envoyproxy/envoy-mobile/pull/2318/commits/9759f4edb781f45cf0ef57bbacc5fb07e6a9c6c3) got lost in one of the subsequent pushes :-(

android: fix cleartext implementation checks

---

library/common/api/external.cc
library/common/extensions/key_value/platform/config.cc
library/common/extensions/key_value/platform/config.h
library/common/extensions/key_value/platform/platform.proto
test/common/extensions/key_value/platform/platform_store_test.cc

The PlatformKeyValueStoreFactory used to take a PlatformInterfaceImpl where the registered KV store was found in the API registry and used to bridge the PlatformKeyValueStore with the native underlying store (e.g. SharedPrefs on Android).
However, registered factory classes only have their default constructor invoked, so the current PlatformKeyValueStoreFactory constructor taking in the PlatformInterfaceImpl would not have worked.
Instead, we use a globally known registered API name to fetch the registered KV store, and use it to create a static global PlatformInstanceImpl.

key_value: Use known registered name to create global PlatformInterfaceImpl

---

docs/root/intro/what_is_envoy_mobile.rst

Description: Replace an old link that does not work anymore (404) with a new one.
Testing: 
Checked that I can open the page
Docs Changes:
fix link url

docs: update an old 404 link to a new one

---

test/kotlin/integration/EngineApiTest.kt
test/kotlin/integration/StatFlushIntegrationTest.kt

Using setLogger ends up routing all the logs to the callback, which drastically reduces visibility into why the test is failing. This moves tests that aren't specifically testing the logging callback to use the startup callback instead. 
Risk Level:  Low, test only
Testing: n/a

prefer using onEngineRunning over setLogger

---

library/cc/engine.h
library/common/extensions/filters/http/network_configuration/filter.cc
library/common/extensions/filters/http/network_configuration/filter.h
library/common/main_interface.cc
library/common/network/connectivity_manager.cc
library/common/network/connectivity_manager.h
library/common/network/proxy_settings.h
test/common/extensions/filters/http/network_configuration/BUILD
test/common/extensions/filters/http/network_configuration/network_configuration_filter_test.cc
test/common/integration/base_client_integration_test.cc
test/common/integration/base_client_integration_test.h
test/common/integration/client_integration_test.cc
test/common/network/connectivity_manager_test.cc
test/common/network/proxy_settings_test.cc
test/kotlin/integration/proxying/BUILD
test/kotlin/integration/proxying/PerformHTTPSRequestBadHostname.kt
test/kotlin/integration/proxying/PerformHTTPSRequestUsingAsyncProxyTest.kt

modifying the NetworkConfigurationFilter to do asynchronous DNS lookups for non-IP-address proxies.
If address resolution fails, the request will be short circuited by sendLocalReply rather than being sent upstream without being proxied.
This PR also changes ConnectivityManager to have a pure API and an Impl for testing.
Testing: unit tests, integration test
part of https://github.com/envoyproxy/envoy-mobile/issues/1622 
fixes #2532

proxy monitor async version

---

library/common/config/config.cc
library/java/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java
library/java/org/chromium/net/impl/NativeCronetEngineBuilderImpl.java
library/kotlin/io/envoyproxy/envoymobile/EngineBuilder.kt
library/objective-c/EnvoyConfiguration.m
library/objective-c/EnvoyEngine.h
library/swift/EngineBuilder.swift
test/java/io/envoyproxy/envoymobile/engine/EnvoyConfigurationTest.kt
test/kotlin/integration/StatFlushIntegrationTest.kt
test/swift/EngineBuilderTests.swift
test/swift/integration/StatFlushIntegrationTest.swift

This introduces a `addExtraStatSinks(List<String>)` function to the builders, allowing for the injection of arbitrary stat sink configuration to use. The function accepts a list of YAML strings, which allows callers to inject any stat sink compiled into the Envoy configuration.
The motivation for this YAML-based API is to support injecting stat sinks that aren't available in the OSS.
One plus of this is that we are able to deprecate the statsd API on the JVM side (only used for test) and instead use this more flexible API.
Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:

support configuring multiple stat sinks

---

library/common/http/BUILD
library/common/http/client.h

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:

bump Envoy, fix build

---

library/java/io/envoyproxy/envoymobile/engine/AndroidProxyMonitor.java
test/kotlin/integration/proxying/PerformHTTPRequestUsingProxyTest.kt
test/kotlin/integration/proxying/PerformHTTPSRequestBadHostname.kt
test/kotlin/integration/proxying/PerformHTTPSRequestUsingAsyncProxyTest.kt
test/kotlin/integration/proxying/PerformHTTPSRequestUsingProxyTest.kt

Description: Add support for PAC proxies. Fixes https://github.com/envoyproxy/envoy-mobile/issues/2531.
Risk Level: Low, the change should be additive and it's guarded with an engine builder flag (`enableProxying(true/false)` that's disabled by default.
Testing: Manual testing for PAC proxies, integrations tests for other types of proxies.
Release Notes: WIP

android proxy: add support for PAC proxies

---

README.md

The old link (https://envoyslack.cncf.io) seems to be broken. 
Signed-off-by: Filip Busic <61715767+filip-doordash@users.noreply.github.com>

Update link to Slack invite

---

library/common/config/config.cc

Description: Enable proxy support for requests that go through the `base_h3` cluster. Fixes https://github.com/envoyproxy/envoy-mobile/issues/2556.
Risk Level: Low, guarded with an engine builder feature flag (set with `enableProxying(true/falase)` call.
Testing: Tests

proxy: wrap QUIC socket with h_11 proxy wrapper

---

BUILD
bazel/envoy_mobile_repositories.bzl
examples/BUILD

Relevant to us are:
* a nicer API for simulator+device apps
* performance improvements
* support for runtime sanitizers
* support for pre-build run scripts
I tried getting SwiftLint and DrString set up as pre-build scripts but couldn't get that to work, so I'll add that in the future when I figure it out.

Update rules_xcodeproj to 0.9.0

---

library/common/config/config.cc

Description: Emit stats that include the specific error code for cases when a request fails with 3xx, 4xx or 5xx. These stats are created only when a failure with a given status code happens so most of them are never created which is great as it reduces the memory footprint that these stats have.
Risk Level: Low, more stats for cases where you have enabled virtual clusters only.

core: enable more detailed virtual cluster stats

---

library/cc/engine_builder.cc
library/cc/engine_builder.h

Make generateConfigStr() const (to ensure that it produces the same output if called multiple times).
Add a small helper method for inserting custom filter configs into the template.
Testing: No behavior change

Slight cleanup of C++ EngineBuilder

---

.github/workflows/android_build.yml
.github/workflows/android_tests.yml
.github/workflows/asan.yml
.github/workflows/cc_tests.yml
.github/workflows/core.yml
.github/workflows/format.yml
.github/workflows/ios_build.yml
.github/workflows/ios_tests.yml
.github/workflows/perf.yml
.github/workflows/python_tests.yml
.github/workflows/release.yml
.github/workflows/release_validation.yml
.github/workflows/tsan.yml

Description:
Only configure Bazel to run against remote execution if the GITHUB_TOKEN environment variable is set. This should prevent forked repos (that do not have a valid GITHUB_TOKEN) from attempting to run against the remote execution cluster.
Signed-off-by: Will Martin <will@engflow.com>

ci: Conditionally run on remote execution

---

docs/root/intro/version_history.rst
library/java/io/envoyproxy/envoymobile/engine/EnvoyConfiguration.java

Description: `String.join` is only available in Android 8 and later.
Testing: Unit tests.
Release Notes: Added.
Fixes #2622

android: fix engine builder crash on Android 6/7

---

docs/root/intro/version_history.rst
library/cc/engine_builder.cc
library/cc/engine_builder.h
test/cc/unit/envoy_config_test.cc

As discussed in the weekly meeting, this does not provide a C++ implementation of Platform filters, merely the ability to configure Envoy to use them.
Part of: #2498
Testing: New unit tests
Release Notes: Updated version_history.rst

Add support for Platform and Native filters to C++ EngineBuilder

---

library/java/org/chromium/net/BUILD

Signed-off-by: Renjie Tang <renjietang@chromium.org>
Description: Add proguard specs to Cronvoy build target. This will produce a cronet_proguard.jar(51k) which is a lot smaller than the original cronet_deploy.jar(2.6m)
Testing: manual test

[Cronvoy]Allow Cronvoy to build with proguard.

---

library/cc/engine_builder.h

Follow up from #2626.
Testing: N/A

Add a comment to C++ Engine Builder addPlatformFilter

---

.github/workflows/android_tests.yml
.github/workflows/asan.yml
.github/workflows/coverage.yml
.github/workflows/ios_tests.yml
.github/workflows/python_tests.yml
.github/workflows/submodule_update.yml
.github/workflows/tsan.yml
tools/bump_lyft_support_rotation.sh

The former is deprecated and will stop working soon: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

ci: migrate from `set-output` to `GITHUB_OUTPUT`

---

test/cc/unit/envoy_config_test.cc

Disable flaky TestConfig.StringAccessors util the cause of flakiness is addressed.
#2641
Testing: N/A

Disable flaky TestConfig.StringAccessors

---

library/common/bridge/utility.h
test/common/http/BUILD
test/common/http/header_utility_test.cc

Use safe_malloc instead of new when creating new_envoy_map_entry
since release_envoy_map uses free instead of delete. Found when 
building this code internally with some sort of strict checking enabled

Use safe_malloc instead of new when creating new_envoy_map_entry

---

WORKSPACE
bazel/envoy_mobile_dependencies.bzl
library/python/BUILD
test/python/BUILD

This is a follow up to #2643 
`pip_install` has been deprecated and now points to `pip_parse` anyway so rather switch to using it directly
the benefit of `pip_parse` is that it dynamically figures out the transitive pip requirements of a particular target - ie it only installs/downloads the requirements that are needed and there is no need to maintain separate requirements files per target/s
Signed-off-by: Ryan Northey <ryan@synca.io>
Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:

repo: Switch `pip_install` -> `pip_parse`

---

bazelw
ci/linux_ci_setup.sh
ci/mac_ci_setup.sh
ci/mac_start_emulator.sh
ci/test_size_regression.sh
docs/build.sh
docs/publish.sh
tools/bump_lyft_support_rotation.sh
tools/check_format.sh

This resolves shellcheck errors - which would trigger when the envoy linter runs against the code
Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:

repo: Shellcheck cleanups

---

.github/lyft_maintainers.yml

Remove @snowp from the Lyft Envoy Mobile rotation (@snowp is not leaving Lyft).

ci: remove Snow from Lyft EM rotation

---

envoy_build_config/extensions_build_config.bzl
test/swift/integration/IdleTimeoutTest.swift

Fixing issue merging in https://github.com/envoyproxy/envoy/pull/23676

fix one issue blocking bumping Envoy

---

library/swift/EngineBuilder.swift

Was set to true inadvertently in #2638.

set enablePlatformCertificateValidation to false on iOS by default

---

docs/root/development/performance/binary_size.rst

As per https://github.com/envoyproxy/envoy-mobile/issues/1274#issuecomment-954305795, this patch is no longer required.

Remove note about DWARF patch being required

---

bazel/envoy_mobile_repositories.bzl

https://github.com/bazelbuild/rules_jvm_external/releases/tag/4.5
Description: bazel: update rules_jvm_external to 4.5
Testing: Local & CI builds and unit tests

bazel: update rules_jvm_external to 4.5

---

library/common/config/config.cc
library/common/extensions/cert_validator/platform_bridge/BUILD
library/common/extensions/cert_validator/platform_bridge/platform_bridge.proto

Signed-off-by: Renjie Tang <renjietang@chromium.org>
Description:
I got this error message when running Envoy-mobile with platform cert validator:
`error initializing configuration '': Proto constraint validation failed (UpstreamTlsContextValidationError.CommonTlsContext: embedded message failed validation | caused by CommonTlsContextValidationError.ValidationContext: embedded message failed validation | caused by CertificateValidationContextValidationError.CustomValidatorConfig: embedded message failed validation | caused by TypedExtensionConfigValidationError.TypedConfig: value is required):`
For the other extensions, I notice they all have a typed_config field. So I guess I need to add one for PlatformBridgeCertValidator too?
Testing: n/a
Release …

Add Typed_config for PlatformBridgeCertValidator

---

envoy_build_config/extensions_build_config.bzl

The variable is required by the `envoy_mobile_package` build package declared in Envoy:
https://github.com/envoyproxy/envoy/blob/91eccaf7d75161676e90adae58722c4bfa7d0c2e/bazel/envoy_build_system.bzl#L74

build: Add MOBILE_PACKAGE_VISIBILITY to the build config

---

.bazelrc
.github/workflows/format.yml
.github/workflows/release_validation.yml
ci/BUILD
ci/mac_ci_setup.sh
docs/root/intro/version_history.rst
docs/root/start/building/building.rst

Updates the version of Xcode Envoy Mobile is compatible with to the latest stable version.
Testing: Local & CI.
Docs Changes: Done.
Release Notes: Done.
Fixes #2664

xcode: update to 14.1

---

test/common/integration/rtds_integration_test.cc
test/common/integration/sds_integration_test.cc

While we figure out and fix
https://github.com/envoyproxy/envoy-mobile/issues/2678, this commit reduces the initial_fetch_timeout on the xDS config sources in the integration tests from 15s to 1s, preventing issues like test timeouts.

test: Set initial_fetch_timeout on the xDS integration tests

---

docs/conf.py
docs/requirements.txt

Fixes https://github.com/envoyproxy/envoy-mobile/issues/2680

website: add Google Analytics to envoymobile.io

---

library/proguard.txt

Do not strip AndroidCertVerifyResult methods with proguard
Testing: Manual with Kotlin Hello World App

Do not strip AndroidCertVerifyResult methods with proguard

---

test/common/integration/rtds_integration_test.cc
test/common/integration/sds_integration_test.cc

The `initial_fetch_timeout` is needed in the tests, as described in https://github.com/envoyproxy/envoy-mobile/issues/2678#issuecomment-1322948208.

test: Remove obsolete comments

---

test/common/integration/rtds_integration_test.cc

This fixes a bug where sometimes the RtdsIntegrationTest would fail because we would check the updates after the DiscoveryResponse was sent but before ensuring the RTDS updates in the response have been applied by the Envoy engine.

test: Wait for RTDS updates to be applied in the integration test

---

test/common/integration/base_client_integration_test.cc

Instead of requiring adding the code `addLogLevel()` to an integration test to get finer-grained logging, now we can specify the log level on the command line via `--test_arg="-l LOG_LEVEL"`, just like for the Envoy integration tests.  For example:
`bazel test --test_arg="-l trace" //test/common/integration:rtds_integration_test`
Limitations:
- This flag only applies to C++ integration tests (not unit tests or other language tests).

Honor the `-l` log level command line setting for C++ integration tests

---

library/common/extensions/cert_validator/platform_bridge/config.h

This fixes up issues exposed in https://github.com/envoyproxy/envoy/pull/24151 where the PlatformBridgeCertValidatorFactory was not associated with the PlatformBridgeCertValidator proto.
Testing:  https://github.com/envoyproxy/envoy/pull/24151

bridge: fix up proto registration

---

library/common/extensions/cert_validator/platform_bridge/c_types.h
library/common/extensions/cert_validator/platform_bridge/platform_bridge_cert_validator.cc
library/common/jni/android_network_utility.cc
library/common/network/apple_platform_cert_verifier.cc

Rename release_validator to validation_cleanup.
The release_validator function does not actually release the validator.
On iOS is does nothing and on Android it merely detaches the JVM from the current thread.
So "cleanup validation" is a better description of it's function than "release validator" and
matches the existing description "to clean up after validation completion."

Rename release_validator to validation_cleanup

---

library/common/extensions/cert_validator/platform_bridge/platform_bridge_cert_validator.cc
library/common/extensions/cert_validator/platform_bridge/platform_bridge_cert_validator.h

Remove unused next_iteration_callback_ member.
Remove unused config_ member.
Make some members const.
Use hostname instead of host_name.
Pass in the list of subject alt names instead of passing in the transport socket options.
Testing: No behavior change

Various small cleanups to PlatformBridgeCertValidator

---

docs/root/api/starting_envoy.rst

Fix typo in starting_envoy.rst
Backport of https://github.com/envoyproxy/envoy/pull/24187/files

Fix typo in starting_envoy.rst

---

library/common/config/config.cc

Description: Disable histograms used to track the duration of time requests routed to a given virtual cluster take. That's to reduce the potential impact of adding a lot of virtual cluster stats to Envoy Mobile.
Testing: 
Docs Changes:
Release Notes:

stats: disable virtual cluster histograms

---

library/common/extensions/cert_validator/platform_bridge/platform_bridge_cert_validator.cc
library/common/extensions/cert_validator/platform_bridge/platform_bridge_cert_validator.h

Cleanup threading/ownership semantics of PlatformBridgeCertValidator by only running static methods on the worker thread. The worker thread is owned by the Validator which join()s the thread before deleting it. So by making the worker thread only operate on data copied (or moved) into the the thread, we avoid multi-threaded access.
Risk Level: Low - Not in production
Testing: Existing unit

Cleanup threading/ownership semantics of PlatformBridgeCertValidator
